"""PC-CM-IMP-WP01: the Project Controls Constraint Management domain foundation.

`constraint.py` is the first-class `ProjectConstraint` aggregate with its
lifecycle vocabulary, transition rule, terminal invariants, Publish
completeness, record-quality/attention vocabulary, and the In My Court rule;
`category.py` is the Project-scoped Constraint Category and its prefix lock;
`party.py` is the BIC/Responsible party-reference vocabulary;
`business_time.py` is the project calendar date and the Monday-Friday
business-day, default Due, Due Soon, and Overdue rules. Pure domain: nothing
here persists, allocates a public code, syncs, or reaches `domain.task`.

PC-CM-IMP-WP03 adds `read_models.py`: the read plane's projections, its bounded
list request, and its opaque keyset cursor. They are projections rather than
aggregates — `PersistedConstraintRecord` in particular matches the stored
nullability instead of the write invariants, so a legally persisted legacy
import stays readable while the aggregate above stays strict.
"""

from __future__ import annotations

from my_pa.domain.project_controls.business_time import (
    DEFAULT_DUE_BUSINESS_DAYS,
    DUE_SOON_BUSINESS_DAYS,
    BusinessDayError,
    ProjectTimezoneError,
    business_day_add,
    business_days_elapsed,
    default_due_date,
    due_soon_through,
    is_due_soon,
    is_overdue,
    is_weekday,
    project_today,
)
from my_pa.domain.project_controls.category import (
    CONSTRAINT_CATEGORY_PREFIX_PATTERN,
    ConstraintCategory,
    ConstraintCategoryError,
    ConstraintCategoryState,
    revise_category,
)
from my_pa.domain.project_controls.constraint import (
    ACTIVE_CONSTRAINT_LIFECYCLE_STATES,
    DRAFT_CONSTRAINT_LIFECYCLE_STATES,
    TERMINAL_CONSTRAINT_LIFECYCLE_STATES,
    ConstraintAttention,
    ConstraintAttentionReason,
    ConstraintFieldKey,
    ConstraintInvariantError,
    ConstraintLifecycleError,
    ConstraintLifecycleMove,
    ConstraintLifecycleOperation,
    ConstraintLifecycleState,
    ConstraintOrigin,
    ConstraintPublishError,
    ConstraintRecordQuality,
    ProjectConstraint,
    check_lifecycle_move,
    in_my_court,
    missing_publish_fields,
    validate_publish_completeness,
)
from my_pa.domain.project_controls.history import (
    CONSTRAINT_IDEMPOTENCY_KEY_PATTERN,
    MAX_CONSTRAINT_CLIENT_CONTEXT_CHARACTERS,
    MAX_CONSTRAINT_FAILURE_REASON_CHARACTERS,
    ConstraintCategoryHistoryEntry,
    ConstraintCategoryMutationOperation,
    ConstraintHistoryEntry,
    ConstraintHistoryError,
    ConstraintMutationActor,
    ConstraintMutationOperation,
    ConstraintMutationOutcome,
)
from my_pa.domain.project_controls.party import PartyKind, PartyRef, PartyRefError
from my_pa.domain.project_controls.read_models import (
    DEFAULT_LIST_LIMIT,
    LIST_CURSOR_VERSION,
    MAX_CURSOR_CHARACTERS,
    MAX_LIST_LIMIT,
    MAX_SEARCH_CHARACTERS,
    MIN_SEARCH_CHARACTERS,
    PRINCIPAL_DISPLAY_LABEL,
    PRINCIPAL_PARTY_REF,
    RECENT_WINDOW_DAYS,
    UNKNOWN_DISPLAY_LABEL,
    UNRESOLVED_PARTY_REF,
    ConstraintCategoryRef,
    ConstraintCategoryRow,
    ConstraintCategoryView,
    ConstraintCompletionView,
    ConstraintCursorError,
    ConstraintEvidenceLinkRow,
    ConstraintEvidenceLinkView,
    ConstraintGrouping,
    ConstraintHistoryEntryView,
    ConstraintHistoryPage,
    ConstraintHistoryPosition,
    ConstraintHistoryRow,
    ConstraintListCursor,
    ConstraintListEntry,
    ConstraintListPage,
    ConstraintListQuery,
    ConstraintListScope,
    ConstraintListSpec,
    ConstraintOverview,
    ConstraintOverviewFacts,
    ConstraintPartyRow,
    ConstraintQueryError,
    ConstraintRecentFilter,
    ConstraintRelationshipRow,
    ConstraintRelationshipView,
    ConstraintSort,
    ConstraintSyncFacts,
    ConstraintSyncHealthView,
    ConstraintSyncStateView,
    ConstraintSyncSummaryView,
    ConstraintView,
    ConstraintVoidView,
    PartyRefView,
    PersistedConstraintRecord,
    RelationshipDirection,
    SortDirection,
    attention_for,
    legacy_missing_fields,
    list_binding_digest,
    party_refs_of,
)
from my_pa.domain.project_controls.revision import ConstraintRevision, ConstraintRevisionError
from my_pa.domain.project_controls.settings import (
    MAX_PROJECT_TIMEZONE_NAME_CHARACTERS,
    ConstraintProjectSettings,
    ConstraintProjectSettingsError,
)

__all__ = [
    "ACTIVE_CONSTRAINT_LIFECYCLE_STATES",
    "CONSTRAINT_CATEGORY_PREFIX_PATTERN",
    "CONSTRAINT_IDEMPOTENCY_KEY_PATTERN",
    "DEFAULT_DUE_BUSINESS_DAYS",
    "DEFAULT_LIST_LIMIT",
    "DRAFT_CONSTRAINT_LIFECYCLE_STATES",
    "DUE_SOON_BUSINESS_DAYS",
    "LIST_CURSOR_VERSION",
    "MAX_CONSTRAINT_CLIENT_CONTEXT_CHARACTERS",
    "MAX_CONSTRAINT_FAILURE_REASON_CHARACTERS",
    "MAX_CURSOR_CHARACTERS",
    "MAX_LIST_LIMIT",
    "MAX_PROJECT_TIMEZONE_NAME_CHARACTERS",
    "MAX_SEARCH_CHARACTERS",
    "MIN_SEARCH_CHARACTERS",
    "PRINCIPAL_DISPLAY_LABEL",
    "PRINCIPAL_PARTY_REF",
    "RECENT_WINDOW_DAYS",
    "TERMINAL_CONSTRAINT_LIFECYCLE_STATES",
    "UNKNOWN_DISPLAY_LABEL",
    "UNRESOLVED_PARTY_REF",
    "BusinessDayError",
    "ConstraintAttention",
    "ConstraintAttentionReason",
    "ConstraintCategory",
    "ConstraintCategoryError",
    "ConstraintCategoryHistoryEntry",
    "ConstraintCategoryMutationOperation",
    "ConstraintCategoryRef",
    "ConstraintCategoryRow",
    "ConstraintCategoryState",
    "ConstraintCategoryView",
    "ConstraintCompletionView",
    "ConstraintCursorError",
    "ConstraintEvidenceLinkRow",
    "ConstraintEvidenceLinkView",
    "ConstraintFieldKey",
    "ConstraintGrouping",
    "ConstraintHistoryEntry",
    "ConstraintHistoryEntryView",
    "ConstraintHistoryError",
    "ConstraintHistoryPage",
    "ConstraintHistoryPosition",
    "ConstraintHistoryRow",
    "ConstraintInvariantError",
    "ConstraintLifecycleError",
    "ConstraintLifecycleMove",
    "ConstraintLifecycleOperation",
    "ConstraintLifecycleState",
    "ConstraintListCursor",
    "ConstraintListEntry",
    "ConstraintListPage",
    "ConstraintListQuery",
    "ConstraintListScope",
    "ConstraintListSpec",
    "ConstraintMutationActor",
    "ConstraintMutationOperation",
    "ConstraintMutationOutcome",
    "ConstraintOrigin",
    "ConstraintOverview",
    "ConstraintOverviewFacts",
    "ConstraintPartyRow",
    "ConstraintProjectSettings",
    "ConstraintProjectSettingsError",
    "ConstraintPublishError",
    "ConstraintQueryError",
    "ConstraintRecentFilter",
    "ConstraintRecordQuality",
    "ConstraintRelationshipRow",
    "ConstraintRelationshipView",
    "ConstraintRevision",
    "ConstraintRevisionError",
    "ConstraintSort",
    "ConstraintSyncFacts",
    "ConstraintSyncHealthView",
    "ConstraintSyncStateView",
    "ConstraintSyncSummaryView",
    "ConstraintView",
    "ConstraintVoidView",
    "PartyKind",
    "PartyRef",
    "PartyRefError",
    "PartyRefView",
    "PersistedConstraintRecord",
    "ProjectConstraint",
    "ProjectTimezoneError",
    "RelationshipDirection",
    "SortDirection",
    "attention_for",
    "business_day_add",
    "business_days_elapsed",
    "check_lifecycle_move",
    "default_due_date",
    "due_soon_through",
    "in_my_court",
    "is_due_soon",
    "is_overdue",
    "is_weekday",
    "legacy_missing_fields",
    "list_binding_digest",
    "missing_publish_fields",
    "party_refs_of",
    "project_today",
    "revise_category",
    "validate_publish_completeness",
]
