"""Alembic environment for the canonical `my_pa` PostgreSQL database.

The URL comes from `MY_PA_DATABASE_URL` through the process settings, never from
`alembic.ini`, so a credential cannot be committed and a migration cannot target
a different server than the application does.

There is no `target_metadata`. The target schema is written by hand rather than
autogenerated from ORM models: this database is populated by migrating an
existing SQLite corpus, so the schema follows that corpus, not a model layer
that does not exist yet.

The `alembic_version` table stays in the default schema. Putting it in
`migration_control` would make the first revision's downgrade drop the table
Alembic is in the middle of updating.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context

from my_pa.bootstrap.settings import load_settings
from my_pa.infrastructure.database.engine import create_database_engine

config = context.config

if config.config_file_name is not None:
    # `disable_existing_loggers=False` because the tests run Alembic in the same
    # process as everything else; the default would silence every logger already
    # configured by whatever called us.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

database_url = load_settings().parsed_database_url()


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting, for review or manual application."""
    context.configure(
        url=database_url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations over a real connection, **one transaction per revision**.

    It was one transaction for the whole run until WP-11, and the change is a
    repair rather than a preference. PostgreSQL takes an `ACCESS EXCLUSIVE` lock
    on every relation a statement creates or drops and holds it to the end of
    the transaction, and the lock table is fixed at
    `max_locks_per_transaction * (max_connections + max_prepared_transactions)`
    entries for the whole cluster. The chain creates 484 target tables and some
    two and a half thousand indexes, so a single-transaction `upgrade head` or
    `downgrade base` accumulated a lock entry for **every relation in the
    database at once** — nearly four thousand of them against a default ceiling
    of 64 x 100.

    That was already within a dozen relations of the ceiling before this package,
    and it was measured rather than inferred: with the chain at `7a1e5f3c9d24`,
    `downgrade base` succeeded; adding four tables and **no indexes at all**
    made it fail with `out of shared memory / You might need to increase
    max_locks_per_transaction`. The next table anyone added would have broken
    every migration round trip in the suite, and the failure would have looked
    like a defect in whatever revision happened to add it.

    Per-revision transactions bound the lock set to the relations *one revision*
    touches, which is what the ceiling is actually sized for. **Each revision
    stays atomic**, which is the property that matters: a revision still denotes
    one schema, and a failure inside one still leaves that revision unapplied.
    What is given up is whole-run atomicity — a chain that fails at revision
    twenty leaves the database at nineteen rather than at zero. That is the
    better direction for a chain this long: the alternative to resuming is
    re-running four hundred and eighty-four table creations to reach the same
    point, and Alembic records the position either way.

    Tuning `max_locks_per_transaction` upward would also work and is what the
    server's own hint suggests, but it would leave the ceiling as a property of
    whichever machine the migration runs on rather than of the migration.
    """
    # statement-timeout-exempt: a revision is the bounded unit and may rebuild indexes.
    engine = create_database_engine(database_url, statement_timeout_ms=None)
    try:
        with engine.connect() as connection:
            context.configure(connection=connection, transaction_per_migration=True)
            with context.begin_transaction():
                context.run_migrations()
    finally:
        engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
