"""Alembic environment for the canonical `my_pa` PostgreSQL database.

The URL comes from `MY_PA_DATABASE_URL` through the process settings, never from
`alembic.ini`, so a credential cannot be committed and a migration cannot target
a different server than the application does.

There is no `target_metadata`. The target schema is written by hand rather than
autogenerated from ORM models: this database is populated by migrating an
existing SQLite corpus, so the schema follows that corpus, not a model layer
that does not exist yet.

The `alembic_version` table stays in the default schema. Putting it in
`migration_control` would make the first revision's downgrade drop the table
Alembic is in the middle of updating.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context

from my_pa.bootstrap.settings import load_settings
from my_pa.infrastructure.database.engine import create_database_engine

config = context.config

if config.config_file_name is not None:
    # `disable_existing_loggers=False` because the tests run Alembic in the same
    # process as everything else; the default would silence every logger already
    # configured by whatever called us.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

database_url = load_settings().database_url


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting, for review or manual application."""
    context.configure(
        url=database_url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations over a real connection, one transaction for the run.

    **No `statement_timeout`, and the omission is the decision.** Every other
    process that builds an engine passes `MY_PA_STATEMENT_TIMEOUT_MS`, because
    its statements are sized to a request. A migration's are sized to the corpus:
    this chain creates functional GIN indexes over `knowledge.extractions` and
    `knowledge.capture_versions` and adds constrained columns to tables the
    legacy corpus fills, and a `CREATE INDEX` cancelled halfway leaves the
    database between revisions — a strictly worse failure than the unbounded
    query the bound exists to prevent. A migration that runs too long is an
    operator's decision to interrupt, not a timer's.
    """
    # statement-timeout-exempt: DDL and index builds are sized to the corpus.
    engine = create_database_engine(database_url)
    try:
        with engine.connect() as connection:
            context.configure(connection=connection)
            with context.begin_transaction():
                context.run_migrations()
    finally:
        engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
