"""Canonical Task and Commitment continuity objects.

A Task is executable work the Principal holds. A Commitment is a social
obligation with a direction. Closing a Task never closes a Commitment.
"""

from my_pa.domain.tasks.attention import AttentionItem, AttentionReason, rank_attention
from my_pa.domain.tasks.models import (
    ALLOWED_TRANSITIONS,
    IDEMPOTENCY_KEY_PATTERN,
    MAX_DESCRIPTION_CHARACTERS,
    MAX_SUMMARY_CHARACTERS,
    MAX_TITLE_CHARACTERS,
    AcceptanceKind,
    Commitment,
    CommitmentDirection,
    CommitmentState,
    ContextLinkKind,
    ContinuityEvidenceState,
    RecurrenceFrequency,
    RecurrenceRule,
    Task,
    TaskContextLink,
    TaskError,
    TaskOrigin,
    TaskPriority,
    TaskRevision,
    TaskRole,
    TaskState,
    TemporalFields,
    Weekday,
    can_transition,
    next_occurrence,
    normalize_priority,
    occurrence_key_for,
    validate_temporal_pair,
)
from my_pa.domain.tasks.resolution import (
    ResolutionOutcome,
    ResolvedReference,
    resolve_task_reference,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "IDEMPOTENCY_KEY_PATTERN",
    "MAX_DESCRIPTION_CHARACTERS",
    "MAX_SUMMARY_CHARACTERS",
    "MAX_TITLE_CHARACTERS",
    "AcceptanceKind",
    "AttentionItem",
    "AttentionReason",
    "Commitment",
    "CommitmentDirection",
    "CommitmentState",
    "ContextLinkKind",
    "ContinuityEvidenceState",
    "RecurrenceFrequency",
    "RecurrenceRule",
    "ResolutionOutcome",
    "ResolvedReference",
    "Task",
    "TaskContextLink",
    "TaskError",
    "TaskOrigin",
    "TaskPriority",
    "TaskRevision",
    "TaskRole",
    "TaskState",
    "TemporalFields",
    "Weekday",
    "can_transition",
    "next_occurrence",
    "normalize_priority",
    "occurrence_key_for",
    "rank_attention",
    "resolve_task_reference",
    "validate_temporal_pair",
]
