"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SurfaceState } from "@/components/ui/surface-state";
import { Textarea } from "@/components/ui/textarea";
import type { DisclosureEnvelope } from "@/contracts/envelope";
import type { CommitmentDetail, TaskDetail, WorkHistoryRow } from "@/contracts/work";
import { captureEvidence, createAttemptKey, isDefinitiveAttemptFailure, workRequest, type ApiFailure } from "@/lib/api/work-client";

function Labeled({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1 text-sm font-medium text-moss-slate"><span>{label}</span>{children}</label>; }
function display(value: string | null | undefined) { return value ? value.replaceAll("_", " ") : "Not set"; }
function dateInput(value: string | null | undefined) { return value?.slice(0, 16) ?? ""; }
function failureTitle(error: unknown, subject: string) { const failure = error as ApiFailure; if (failure.status === 401 || failure.errorClass === "authentication") return "Session expired"; if (failure.status === 403 || failure.errorClass === "authorization" || failure.errorClass === "policy_denied") return `${subject} access was refused`; if (failure.status === 404 || failure.errorClass === "not_found") return `${subject} was not found`; if (failure.status === 400 || failure.status === 422 || failure.errorClass === "validation") return `${subject} request was not valid`; if (failure.status === undefined) return "You appear to be offline"; return `${subject} is unavailable`; }

interface TaskDraft { title: string; description: string; priority: string; dueAt: string; scheduledAt: string; deferredUntil: string; commitmentId: string; role: string; archived: boolean }
function taskDraft(task: TaskDetail): TaskDraft { return { title: task.title, description: task.description ?? "", priority: task.priority ?? "", dueAt: dateInput(task.due_at), scheduledAt: dateInput(task.scheduled_at), deferredUntil: dateInput(task.deferred_until), commitmentId: task.commitment_id ?? "", role: task.role ?? "", archived: Boolean(task.archived_at) }; }

export function TaskDetailView({ taskId }: { taskId: string }) {
  const [task, setTask] = useState<TaskDetail>(); const [draft, setDraft] = useState<TaskDraft>();
  const [history, setHistory] = useState<readonly WorkHistoryRow[]>([]); const [historyDisclosure, setHistoryDisclosure] = useState<DisclosureEnvelope>();
  const [status, setStatus] = useState("Loading task…"); const [failure, setFailure] = useState<{ title: string; detail: string }>();
  const [conflict, setConflict] = useState(false); const [proposal, setProposal] = useState<Record<string, unknown>>();
  const [transitionState, setTransitionState] = useState("open"); const [closureNote, setClosureNote] = useState("");
  const updateAttempt = useRef(createAttemptKey("task-update")); const transitionAttempt = useRef(createAttemptKey("task-transition")); const closureCaptureAttempt = useRef(createAttemptKey("task-closure"));
  const load = useCallback(async () => { try { const [detail, trail] = await Promise.all([workRequest<{ task: TaskDetail }>(`/api/tasks/${encodeURIComponent(taskId)}`), workRequest<{ history: readonly WorkHistoryRow[]; disclosure?: DisclosureEnvelope }>(`/api/tasks/${encodeURIComponent(taskId)}/history?pageSize=50`)]); setTask(detail.task); setDraft(taskDraft(detail.task)); setTransitionState(detail.task.lifecycle_state); setHistory(trail.history ?? []); setHistoryDisclosure(trail.disclosure); setStatus(""); setFailure(undefined); } catch (error) { setFailure({ title: failureTitle(error, "Task"), detail: error instanceof Error ? error.message : "Task could not be read" }); } }, [taskId]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function loadMoreHistory() { const after = historyDisclosure?.nextCursor; if (!after) return; setStatus("Reading more Task history…"); try { const trail = await workRequest<{ history: readonly WorkHistoryRow[]; disclosure?: DisclosureEnvelope }>(`/api/tasks/${encodeURIComponent(taskId)}/history?pageSize=50&after=${encodeURIComponent(after)}`); setHistory((current) => [...current, ...(trail.history ?? []).filter((row) => !current.some((existing) => existing.history_id === row.history_id))]); setHistoryDisclosure(trail.disclosure); setStatus(""); } catch (error) { setStatus(error instanceof Error ? error.message : "More Task history could not be read"); } }
  async function applyProposal(values: Record<string, unknown>) { if (!task) return; const material = { ...values, expectedVersion: task.version }; setStatus("Saving one atomic patch…"); setConflict(false); try { await workRequest(`/api/tasks/${encodeURIComponent(taskId)}`, { method: "PATCH", body: JSON.stringify({ ...material, idempotencyKey: updateAttempt.current.forPayload(material) }) }); updateAttempt.current.succeeded(); setProposal(undefined); setStatus("Task update persisted."); await load(); } catch (error) { const problem = error as ApiFailure; const isConflict = problem.status === 409; setConflict(isConflict); setProposal(isConflict ? values : undefined); if (isConflict && problem.current) setTask(problem.current as TaskDetail); if (isDefinitiveAttemptFailure(error)) updateAttempt.current.succeeded(); setStatus(isConflict ? "The task changed on the server. Compare the canonical record with the controlled proposal, then reapply deliberately." : problem.message || "Task was not updated"); } }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!draft) return; await applyProposal({ title: draft.title, description: draft.description || undefined, priority: draft.priority || undefined, dueAt: draft.dueAt ? new Date(draft.dueAt).toISOString() : undefined, scheduledAt: draft.scheduledAt ? new Date(draft.scheduledAt).toISOString() : undefined, deferredUntil: draft.deferredUntil ? new Date(draft.deferredUntil).toISOString() : undefined, commitmentId: draft.commitmentId || undefined, role: draft.role || undefined, archived: draft.archived, clearFields: [!draft.description && "description", !draft.priority && "priority", !draft.dueAt && "due_at", !draft.scheduledAt && "scheduled_at", !draft.deferredUntil && "deferred_until", !draft.commitmentId && "commitment_id", !draft.role && "role"].filter(Boolean) }); }
  async function transition(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!task) return; setStatus("Preparing transition…"); try { const terminal = transitionState === "completed" || transitionState === "cancelled"; const closureEvidenceRef = terminal ? await captureEvidence(closureNote, "task-closure", closureCaptureAttempt.current.forPayload({ note: closureNote })) : undefined; const material = { toState: transitionState, closureEvidenceRef, expectedVersion: task.version }; await workRequest(`/api/tasks/${encodeURIComponent(taskId)}/transition`, { method: "POST", body: JSON.stringify({ ...material, idempotencyKey: transitionAttempt.current.forPayload(material) }) }); closureCaptureAttempt.current.succeeded(); transitionAttempt.current.succeeded(); setClosureNote(""); setStatus("Task transition persisted. A linked commitment was not changed."); await load(); } catch (error) { const problem = error as ApiFailure; if (problem.status === 409 && problem.current) { setTask(problem.current as TaskDetail); setDraft(taskDraft(problem.current as TaskDetail)); } if (isDefinitiveAttemptFailure(error)) transitionAttempt.current.succeeded(); setStatus(problem.message || "Task transition failed"); } }
  if (failure) return <SurfaceState kind="unavailable" title={failure.title} detail={failure.detail}><Button className="mt-3" variant="secondary" onClick={() => void load()}>Retry Task read</Button></SurfaceState>;
  if (!task || !draft) return <p role="status">{status}</p>;
  return <article className="mx-auto max-w-4xl"><Link href="/work?view=all-open" className="text-sm text-moss-green underline">← Work</Link><header className="mt-4"><h1 className="text-2xl font-semibold text-moss-slate">{task.title}</h1><p className="mt-1 text-sm text-muted">{display(task.lifecycle_state)} · version {task.version} · evidence {display(task.evidence_state)}</p></header>
    {conflict && proposal ? <Conflict title="Canonical versus proposed"><p>Canonical version {task.version}. Every editable field is compared before reapply.</p><dl className="mt-2 grid gap-2"><dt>Title</dt><dd>Canonical: {task.title} · Proposed: {String(proposal.title ?? task.title)}</dd><dt>Description</dt><dd>Canonical: {task.description ?? "Not set"} · Proposed: {String(proposal.description ?? "Clear")}</dd><dt>Priority</dt><dd>Canonical: {task.priority ?? "Not set"} · Proposed: {String(proposal.priority ?? "Clear")}</dd><dt>Due</dt><dd>Canonical: {task.due_at ?? "Not set"} · Proposed: {String(proposal.dueAt ?? "Clear")}</dd><dt>Scheduled</dt><dd>Canonical: {task.scheduled_at ?? "Not set"} · Proposed: {String(proposal.scheduledAt ?? "Clear")}</dd><dt>Deferred until</dt><dd>Canonical: {task.deferred_until ?? "Not set"} · Proposed: {String(proposal.deferredUntil ?? "Clear")}</dd><dt>Archived</dt><dd>Canonical: {task.archived_at ? "Yes" : "No"} · Proposed: {proposal.archived ? "Yes" : "No"}</dd><dt>Commitment</dt><dd>Canonical: {task.commitment_id ?? "Not set"} · Proposed: {String(proposal.commitmentId ?? "Clear")}</dd><dt>Role</dt><dd>Canonical: {task.role ?? "Not set"} · Proposed: {String(proposal.role ?? "Clear")}</dd></dl><Button type="button" variant="secondary" onClick={() => void applyProposal(proposal)}>Reapply proposed patch to version {task.version}</Button></Conflict> : null}
    <p role="status" className="mt-4 text-sm text-muted">{status}</p><div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={update} className="grid gap-4 rounded-xl border border-moss-slate/15 bg-surface p-4"><h2 className="font-semibold">Edit task</h2><Labeled label="Title"><Input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required /></Labeled><Labeled label="Description"><Textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></Labeled><Labeled label="Priority"><select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value })} className="h-10 rounded-md border bg-surface px-3"><option value="">Unset</option>{["p1","p2","p3","p4"].map((p)=><option key={p}>{p}</option>)}</select></Labeled><Labeled label="Due"><Input type="datetime-local" value={draft.dueAt} onChange={(event) => setDraft({ ...draft, dueAt: event.target.value })} /></Labeled><Labeled label="Scheduled"><Input type="datetime-local" value={draft.scheduledAt} onChange={(event) => setDraft({ ...draft, scheduledAt: event.target.value })} /></Labeled><Labeled label="Deferred until"><Input type="datetime-local" value={draft.deferredUntil} onChange={(event) => setDraft({ ...draft, deferredUntil: event.target.value })} /></Labeled><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.archived} onChange={(event) => setDraft({ ...draft, archived: event.target.checked })} /> Archived</label><Labeled label="Commitment ID"><Input value={draft.commitmentId} onChange={(event) => setDraft({ ...draft, commitmentId: event.target.value })} /></Labeled><Labeled label="Role"><select value={draft.role} onChange={(event) => setDraft({ ...draft, role: event.target.value })} className="h-10 rounded-md border bg-surface px-3"><option value="">None</option><option value="follow_up">Follow up</option></select></Labeled><Button type="submit">Save atomic patch</Button></form>
      <form onSubmit={transition} className="grid content-start gap-4 rounded-xl border border-moss-slate/15 bg-surface p-4"><h2 className="font-semibold">Lifecycle</h2><Labeled label="Move to"><select value={transitionState} onChange={(event) => setTransitionState(event.target.value)} className="h-10 rounded-md border bg-surface px-3">{["open","in_progress","waiting","blocked","completed","cancelled"].map((value)=><option key={value}>{value}</option>)}</select></Labeled><Labeled label="Closure note"><Textarea value={closureNote} onChange={(event) => setClosureNote(event.target.value)} placeholder="Required for completed or cancelled" /></Labeled><Button type="submit">Apply transition</Button><p className="text-xs text-muted">Completing this Task never closes its linked Commitment.</p></form></div>
    <Evidence origin={task.origin_evidence_ref} closure={task.closure_evidence_ref} /><History subject="Task" rows={history} disclosure={historyDisclosure} onContinue={() => void loadMoreHistory()} />
  </article>;
}

interface CommitmentDraft { summary: string; counterparty: string; dueAt: string }
function commitmentDraft(record: CommitmentDetail): CommitmentDraft { return { summary: record.title, counterparty: record.counterparty_person_id ?? "", dueAt: dateInput(record.due_date) }; }

export function CommitmentDetailView({ commitmentId }: { commitmentId: string }) {
  const [record, setRecord] = useState<CommitmentDetail>(); const [draft, setDraft] = useState<CommitmentDraft>(); const [history, setHistory] = useState<readonly WorkHistoryRow[]>([]); const [historyDisclosure, setHistoryDisclosure] = useState<DisclosureEnvelope>();
  const [status, setStatus] = useState("Loading commitment…"); const [failure, setFailure] = useState<{ title: string; detail: string }>(); const [conflict, setConflict] = useState(false); const [proposal, setProposal] = useState<Record<string, unknown>>(); const [closureNote, setClosureNote] = useState("");
  const updateAttempt = useRef(createAttemptKey("commitment-update")); const closeAttempt = useRef(createAttemptKey("commitment-close")); const closureCaptureAttempt = useRef(createAttemptKey("commitment-closure"));
  const load = useCallback(async () => { try { const [detail, trail] = await Promise.all([workRequest<{ commitment: CommitmentDetail }>(`/api/commitments/${encodeURIComponent(commitmentId)}`), workRequest<{ history: readonly WorkHistoryRow[]; disclosure?: DisclosureEnvelope }>(`/api/commitments/${encodeURIComponent(commitmentId)}/history?pageSize=50`)]); setRecord(detail.commitment); setDraft(commitmentDraft(detail.commitment)); setHistory(trail.history ?? []); setHistoryDisclosure(trail.disclosure); setStatus(""); setFailure(undefined); } catch (error) { setFailure({ title: failureTitle(error, "Commitment"), detail: error instanceof Error ? error.message : "Commitment could not be read" }); } }, [commitmentId]); useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function loadMoreHistory() { const after = historyDisclosure?.nextCursor; if (!after) return; setStatus("Reading more Commitment history…"); try { const trail = await workRequest<{ history: readonly WorkHistoryRow[]; disclosure?: DisclosureEnvelope }>(`/api/commitments/${encodeURIComponent(commitmentId)}/history?pageSize=50&after=${encodeURIComponent(after)}`); setHistory((current) => [...current, ...(trail.history ?? []).filter((row) => !current.some((existing) => existing.history_id === row.history_id))]); setHistoryDisclosure(trail.disclosure); setStatus(""); } catch (error) { setStatus(error instanceof Error ? error.message : "More Commitment history could not be read"); } }
  async function applyProposal(values: Record<string, unknown>) { if (!record) return; const material = { ...values, expectedVersion: record.version }; setStatus("Saving commitment…"); setConflict(false); try { await workRequest(`/api/commitments/${encodeURIComponent(commitmentId)}`, { method: "PATCH", body: JSON.stringify({ ...material, idempotencyKey: updateAttempt.current.forPayload(material) }) }); updateAttempt.current.succeeded(); setProposal(undefined); setStatus("Commitment update persisted."); await load(); } catch (error) { const problem = error as ApiFailure; const isConflict = problem.status === 409; setConflict(isConflict); setProposal(isConflict ? values : undefined); if (isConflict && problem.current) setRecord(problem.current as CommitmentDetail); setStatus(isConflict ? "Conflict: compare every canonical field with the retained proposal, then reapply deliberately." : problem.message || "Commitment was not updated"); if (isDefinitiveAttemptFailure(error)) updateAttempt.current.succeeded(); } }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!draft) return; await applyProposal({ summary: draft.summary, counterpartyPersonId: draft.counterparty, dueAt: draft.dueAt ? new Date(draft.dueAt).toISOString() : undefined, clearDueAt: !draft.dueAt }); }
  async function close(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!record) return; setStatus("Saving closure evidence…"); try { const evidence = await captureEvidence(closureNote, "commitment-closure", closureCaptureAttempt.current.forPayload({ note: closureNote })); const material = { expectedVersion: record.version, closureEvidenceRef: evidence }; await workRequest(`/api/commitments/${encodeURIComponent(commitmentId)}/close`, { method: "POST", body: JSON.stringify({ ...material, idempotencyKey: closeAttempt.current.forPayload(material) }) }); closureCaptureAttempt.current.succeeded(); closeAttempt.current.succeeded(); setClosureNote(""); setStatus("Commitment explicitly closed."); await load(); } catch (error) { const problem = error as ApiFailure; if (problem.status === 409 && problem.current) { setRecord(problem.current as CommitmentDetail); setDraft(commitmentDraft(problem.current as CommitmentDetail)); } if (isDefinitiveAttemptFailure(error)) closeAttempt.current.succeeded(); setStatus(problem.message || "Commitment was not closed"); } }
  if (failure) return <SurfaceState kind="unavailable" title={failure.title} detail={failure.detail}><Button className="mt-3" variant="secondary" onClick={() => void load()}>Retry Commitment read</Button></SurfaceState>;
  if (!record || !draft) return <p role="status">{status}</p>;
  return <article className="mx-auto max-w-4xl"><Link href="/work?view=commitments" className="text-sm text-moss-green underline">← Commitments</Link><header className="mt-4"><h1 className="text-2xl font-semibold text-moss-slate">{record.title}</h1><p className="mt-1 text-sm text-muted">{display(record.direction)} · {record.state} · version {record.version}</p></header>{conflict && proposal ? <Conflict title="Canonical versus proposed"><dl><dt>Summary</dt><dd>Canonical: {record.title} · Proposed: {String(proposal.summary ?? "")}</dd><dt>Counterparty</dt><dd>Canonical: {record.counterparty_person_id ?? "Not set"} · Proposed: {String(proposal.counterpartyPersonId ?? "Not set")}</dd><dt>Due</dt><dd>Canonical: {record.due_date ?? "Not set"} · Proposed: {String(proposal.dueAt ?? "Clear")}</dd></dl><Button type="button" variant="secondary" onClick={() => void applyProposal(proposal)}>Reapply proposed update to version {record.version}</Button></Conflict> : null}<p role="status" className="mt-4 text-sm text-muted">{status}</p><div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={update} className="grid gap-4 rounded-xl border border-moss-slate/15 bg-surface p-4"><h2 className="font-semibold">Edit commitment</h2><Labeled label="Summary"><Input value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} required /></Labeled><Labeled label="Counterparty person ID"><Input value={draft.counterparty} onChange={(event) => setDraft({ ...draft, counterparty: event.target.value })} required /></Labeled><Labeled label="Due"><Input type="datetime-local" value={draft.dueAt} onChange={(event) => setDraft({ ...draft, dueAt: event.target.value })} /></Labeled><Button type="submit">Save commitment</Button></form><form onSubmit={close} className="grid content-start gap-4 rounded-xl border border-moss-slate/15 bg-surface p-4"><h2 className="font-semibold">Close explicitly</h2><Labeled label="Closure note"><Textarea value={closureNote} onChange={(event) => setClosureNote(event.target.value)} required /></Labeled><Button type="submit" variant="danger" disabled={record.state === "closed"}>{record.state === "closed" ? "Already closed" : "Close commitment"}</Button></form></div><Evidence origin={record.origin_evidence_ref} closure={record.closure_evidence_ref} /><History subject="Commitment" rows={history} disclosure={historyDisclosure} onContinue={() => void loadMoreHistory()} /></article>;
}

function Conflict({ title, children }: { title: string; children: ReactNode }) { return <section role="alert" className="mt-4 rounded-lg border border-moss-coral-strong p-3 text-sm"><h2 className="font-semibold">{title}</h2>{children}</section>; }
function Evidence({ origin, closure }: { origin: string; closure: string | null }) { return <section aria-labelledby="evidence-heading" className="mt-6 rounded-xl border border-moss-slate/15 bg-surface p-4"><h2 id="evidence-heading" className="font-semibold">Evidence</h2><dl className="mt-3 grid gap-2 text-sm"><div><dt className="text-muted">Origin</dt><dd className="break-all font-mono">{origin}</dd></div><div><dt className="text-muted">Closure</dt><dd className="break-all font-mono">{closure ?? "Not closed"}</dd></div></dl></section>; }
function History({ subject, rows, disclosure, onContinue }: { subject: string; rows: readonly WorkHistoryRow[]; disclosure?: DisclosureEnvelope; onContinue: () => void }) { return <section aria-labelledby="history-heading" className="mt-6"><h2 id="history-heading" className="font-semibold">History</h2>{rows.length ? <ol className="mt-3 grid gap-2">{rows.map((row)=><li key={row.history_id} className="rounded-lg border border-moss-slate/15 bg-surface p-3 text-sm"><span className="font-medium">{display(row.action)}</span> · {row.outcome} · v{row.before_version}→v{row.after_version}<time className="block text-xs text-muted" dateTime={row.recorded_at}>{new Date(row.recorded_at).toLocaleString()}</time></li>)}</ol> : <p className="mt-2 text-sm text-muted">No history rows were returned.</p>}{disclosure ? <aside aria-label={`${subject} history disclosure`} className="mt-3 rounded-lg border border-moss-slate/15 bg-surface p-3 text-xs text-muted"><p>Authority: {disclosure.authority.replaceAll("_", " ")} · Coverage: {disclosure.coverage} · Freshness: {disclosure.freshnessAt ? new Date(disclosure.freshnessAt).toLocaleString() : "not disclosed"} · Truncated: {disclosure.truncated ? "yes" : "no"}</p>{disclosure.limitations.length ? <ul className="mt-1 list-inside list-disc">{disclosure.limitations.map((item) => <li key={item}>{item}</li>)}</ul> : null}</aside> : null}{disclosure?.nextCursor ? <Button className="mt-3" type="button" variant="secondary" onClick={onContinue}>Continue {subject} history</Button> : null}</section>; }
