/**
 * The per-principal content key that queued capture text is encrypted under.
 *
 * ## What this is
 *
 * One AES-GCM 256 key per `principalId`, generated by
 * `crypto.subtle.generateKey` with `extractable: false`, stored as a
 * `CryptoKey` in IndexedDB, and used only to encrypt and decrypt the payload of
 * a note that is waiting to be replayed to the server. The key is never
 * exported, never serialised, never sent anywhere, and never logged. A fresh
 * 96-bit IV is drawn for every record, so no two records share a nonce under the
 * same key.
 *
 * The key being *per principal* is the part that carries an isolation property
 * rather than a storage property: a record queued while A was signed in is
 * encrypted under A's key, and B's key does not decrypt it. That is a second
 * lock behind the queue's own principal binding (`queue.ts`), not a replacement
 * for it — the queue refuses to decrypt a foreign entry at all rather than
 * trying and failing.
 *
 * ## What this is NOT — read this before relying on it
 *
 * Browser key storage has real and well-known bounds, and the honest summary is
 * that this raises the bar against casual local inspection and against someone
 * reading the profile directory off a disk. **It is not a confidentiality
 * guarantee against an attacker who can run script on this origin.**
 * Specifically:
 *
 * * **Not hardware-backed** in most browsers. `extractable: false` is enforced
 *   by the browser's own object model, not by a secure element or a TPM. A
 *   browser or platform that chooses to back it with hardware may; nothing here
 *   requires or verifies that, and this code cannot tell the difference.
 * * **Same-origin script reaches the decryption capability.** Anything that can
 *   execute JavaScript on this origin — an XSS, a compromised dependency, a
 *   malicious browser extension with host access, a devtools console — can open
 *   this database, obtain the same `CryptoKey` handle, and call `decrypt` with
 *   it. `extractable: false` prevents the raw bytes from being read out; it does
 *   not prevent the key from being *used*. Against that attacker the encryption
 *   buys essentially nothing.
 * * **Local profile access is a partial, not total, defence.** Someone with the
 *   browser's own tooling and access to the profile on disk may be able to reach
 *   both the wrapped key material and the database, depending on the browser and
 *   the platform. Reading the raw IndexedDB files with an unrelated tool does
 *   not yield the plaintext; using the browser itself against the same profile
 *   may.
 * * **No protection against a compromised device.** A keylogger, a screen
 *   reader, a hostile OS account, or a full-disk image taken while the profile is
 *   unlocked are all outside what this can address.
 * * **Storage is evictable.** The browser may clear this database under storage
 *   pressure, in private-browsing modes, or when the user clears site data. If
 *   the key is evicted the queued ciphertext becomes permanently undecryptable;
 *   if the whole database is evicted the queued notes are gone. Neither is
 *   recoverable, and there is no copy anywhere else.
 *
 * ## Fail closed, and never downgrade
 *
 * If this environment cannot store a non-extractable `CryptoKey`, the answer is
 * `OfflineKeyUnavailableError` and the enqueue is refused. There is no fallback
 * to an extractable key, no fallback to a raw key held in memory, and no
 * fallback to storing plaintext. A stored key that reads back `extractable ===
 * true` is refused for the same reason rather than used: it is evidence that
 * something wrote a key this module would not have written.
 */
import {
  KEY_STORE,
  openOfflineDatabase,
  request,
  transactionDone,
} from "@/lib/offline/db";

/** AES-GCM's nonce size in bytes. 96 bits is the size the construction is defined for. */
export const IV_BYTES = 12;

/** The one algorithm this module generates, and the one it will use. */
export const CONTENT_KEY_ALGORITHM = { name: "AES-GCM", length: 256 } as const;

/**
 * Raised when a usable, non-extractable content key cannot be established.
 *
 * Every construction path that could have produced a weaker key ends here
 * instead. The message names the reason so an operator sees which bound was hit,
 * and the caller's only correct response is to refuse the enqueue.
 */
export class OfflineKeyUnavailableError extends Error {
  constructor(detail: string) {
    super(
      `no non-extractable offline content key is available: ${detail}. Nothing was ` +
        "queued and nothing was written in plaintext: this module refuses rather than " +
        "downgrading to an extractable key or to unencrypted storage.",
    );
    this.name = "OfflineKeyUnavailableError";
  }
}

interface StoredKeyRecord {
  readonly principalId: string;
  readonly key: CryptoKey;
  readonly createdAt: number;
}

/**
 * The content key for `principalId`, generated on first use.
 *
 * Both the read and the generate-and-store path check `extractable`, because the
 * two failures are different: a stored extractable key means something else
 * wrote it, and a generated extractable key would mean this environment ignored
 * the argument. Neither is used.
 */
export async function principalContentKey(
  db: IDBDatabase,
  principalId: string,
): Promise<CryptoKey> {
  const existing = await readKey(db, principalId);
  if (existing) {
    if (existing.extractable) {
      throw new OfflineKeyUnavailableError(
        "the stored key for this principal is extractable, which this module never writes",
      );
    }
    return existing;
  }

  let generated: CryptoKey;
  try {
    generated = (await crypto.subtle.generateKey(CONTENT_KEY_ALGORITHM, false, [
      "encrypt",
      "decrypt",
    ])) as CryptoKey;
  } catch (error) {
    throw new OfflineKeyUnavailableError(
      error instanceof Error ? error.message : "generateKey refused",
    );
  }
  if (generated.extractable) {
    throw new OfflineKeyUnavailableError(
      "generateKey returned an extractable key despite being asked for a non-extractable one",
    );
  }

  const record: StoredKeyRecord = { principalId, key: generated, createdAt: Date.now() };
  try {
    const tx = db.transaction(KEY_STORE, "readwrite");
    tx.objectStore(KEY_STORE).put(record);
    await transactionDone(tx);
  } catch (error) {
    // A `CryptoKey` that will not survive a structured clone into IndexedDB is
    // the environment saying it cannot hold this key. Storing the raw bytes
    // instead is exactly the downgrade this module exists to refuse.
    throw new OfflineKeyUnavailableError(
      error instanceof Error
        ? `the key could not be stored (${error.message})`
        : "the key could not be stored",
    );
  }

  const readBack = await readKey(db, principalId);
  if (!readBack) {
    throw new OfflineKeyUnavailableError("the stored key did not read back");
  }
  if (readBack.extractable) {
    throw new OfflineKeyUnavailableError("the key read back as extractable");
  }
  return readBack;
}

async function readKey(db: IDBDatabase, principalId: string): Promise<CryptoKey | null> {
  const tx = db.transaction(KEY_STORE, "readonly");
  const record = (await request(tx.objectStore(KEY_STORE).get(principalId))) as
    | StoredKeyRecord
    | undefined;
  await transactionDone(tx).catch(() => undefined);
  if (!record) return null;
  const key = record.key;
  if (!key || typeof key !== "object" || !("algorithm" in key)) {
    throw new OfflineKeyUnavailableError("the stored key record does not hold a CryptoKey");
  }
  return key;
}

/** One encrypted record: a fresh IV and the AES-GCM ciphertext of the UTF-8 text. */
export interface SealedPayload {
  readonly iv: Uint8Array;
  readonly ciphertext: ArrayBuffer;
}

/** Encrypt `text` under `key` with a fresh 96-bit IV. */
export async function seal(key: CryptoKey, text: string): Promise<SealedPayload> {
  const iv = new Uint8Array(IV_BYTES);
  crypto.getRandomValues(iv);
  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: iv as BufferSource },
    key,
    new TextEncoder().encode(text) as BufferSource,
  );
  return { iv, ciphertext };
}

/**
 * Decrypt a sealed payload under `key`.
 *
 * AES-GCM authenticates, so a payload sealed under a different principal's key —
 * or one whose bytes were altered at rest — fails here rather than yielding
 * something plausible.
 */
export async function unseal(key: CryptoKey, payload: SealedPayload): Promise<string> {
  const plaintext = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: payload.iv as BufferSource },
    key,
    payload.ciphertext,
  );
  return new TextDecoder().decode(plaintext);
}

/** Open the database and resolve the content key in one step. */
export async function openWithContentKey(
  principalId: string,
): Promise<{ db: IDBDatabase; key: CryptoKey }> {
  const db = await openOfflineDatabase();
  return { db, key: await principalContentKey(db, principalId) };
}
