"""CRL-WP-03 CP-CRL-02: the one Capture lifecycle revision, `0641c354ca85` (CRL-AC-D7).

Generated by `alembic revision` against the sole head `1d9b248e7f83`. This
module proves:

* **the graph** -- the single head, directly on `1d9b248e7f83`;
* **the freeze** -- no package import, no live declaration, no enum; the frozen
  DDL names every column, constraint and index `tables.py` declares for the two
  lifecycle tables; the frozen `captures` and `capture_jobs` declarations are
  unchanged (the root uniqueness and the jobs overlay exist only in the
  database, MR-C05); and the revision does not name the change feed at all
  (MR-C20: the never-rewritten guard is narrowed only at CP-CRL-07);
* **no backfill** -- the revision writes no row;
* **offline SQL** for both directions, with the refusal first on the way down;
* on disposable databases: an empty database reaches the head; the predecessor
  holding synthetic roots, versions and jobs upgrades with every root active at
  revision 0 (no event) and every job at generation 0 and unpaused; the
  downgrade refuses while a lifecycle event, a lifecycle receipt or a paused
  job exists; and an empty downgrade unwinds everything and re-upgrades.

The file name routes every `database` test here to migration-edge
(`tests/db/fixtures.py`); the tests with no marker also run in FAST. Every value
is synthetic.
"""

from __future__ import annotations

import ast
import io
import re
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path
from typing import Final

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import Engine, insert, text
from sqlalchemy.engine import Connection
from sqlalchemy.exc import DBAPIError

from my_pa.domain.capture.version import digest_of
from my_pa.infrastructure.database.engine import create_database_engine
from my_pa.infrastructure.persistence.tables import (
    capture_jobs,
    capture_lifecycle_events,
    capture_lifecycle_receipts,
    capture_versions,
    captures,
)

ROOT: Final = Path(__file__).resolve().parents[2]
SCHEMA: Final = "knowledge"
REVISION: Final = "0641c354ca85"
PREVIOUS: Final = "1d9b248e7f83"
MIGRATION: Final = ROOT / "migrations" / "versions" / "20261001_0641c354ca85_capture_lifecycle.py"
TABLE_NAMES: Final = frozenset({"capture_lifecycle_events", "capture_lifecycle_receipts"})
TRIGGERS: Final = frozenset(
    {"capture_lifecycle_events_are_append_only", "capture_lifecycle_receipts_are_append_only"}
)
FUNCTIONS: Final = frozenset(
    {
        "capture_lifecycle_events_stay_append_only",
        "capture_lifecycle_receipts_stay_append_only",
    }
)
ROOT_UNIQUE: Final = "a_capture_is_identified_within_its_principal"
JOB_CONSTRAINTS: Final = frozenset(
    {
        "a_capture_job_lease_generation_is_not_negative",
        "a_capture_job_pause_cause_is_known",
        "only_a_queued_capture_job_is_paused",
    }
)
PRINCIPAL: Final = "prn_clmig0001clmig0001"
CAPTURE: Final = "cap_clmig0001capture1"
VERSION: Final = "capver_clmig0001version1"
OPERATION_QUEUED: Final = "op_clmig0001queued01"
OPERATION_DONE: Final = "op_clmig0001done0001"
WHEN: Final = datetime(2026, 10, 1, 12, tzinfo=UTC)
RESTRICT_VIOLATION: Final = "23001"
_WHITESPACE: Final = re.compile(r"\s+")


def _config(buffer: io.StringIO | None = None) -> Config:
    return Config(str(ROOT / "alembic.ini"), output_buffer=buffer)


def _offline(target: str, *, down: bool = False) -> str:
    buffer = io.StringIO()
    action = command.downgrade if down else command.upgrade
    action(_config(buffer), target, sql=True)
    return _WHITESPACE.sub(" ", buffer.getvalue())


# ---- the graph ----------------------------------------------------------------------


def test_the_revision_is_the_single_head_directly_on_1d9b248e7f83() -> None:
    script = ScriptDirectory.from_config(_config())
    assert script.get_heads() == [REVISION]
    assert script.get_revision(REVISION).down_revision == PREVIOUS


# ---- the freeze -----------------------------------------------------------------------


def test_revision_imports_no_domain_or_persistence_modules() -> None:
    source = MIGRATION.read_text(encoding="utf-8")
    imported: set[str] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ImportFrom) and node.module is not None:
            imported.add(node.module)
        elif isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
    assert imported <= {"alembic", "__future__", "typing"}
    assert "my_pa" not in source
    assert "create_all" not in source


def test_the_audit_restatement_names_the_capability_token_not_the_feed_tables() -> None:
    """MR-C20: the copied vocabulary token is not a feed-table reference."""
    source = MIGRATION.read_text(encoding="utf-8")
    assert "'record_events.list'" in source
    assert "CREATE TABLE knowledge.record_events" not in source
    assert "record_event_sequences" not in source
    assert "capture.archive" in source and "capture.restore" in source


def test_the_frozen_ddl_names_every_declared_column_constraint_and_index() -> None:
    source = MIGRATION.read_text(encoding="utf-8")
    flat = _WHITESPACE.sub(" ", source)
    for table in (capture_lifecycle_events, capture_lifecycle_receipts):
        assert f"CREATE TABLE knowledge.{table.name} (" in source
        for column in table.c:
            assert re.search(rf"\b{column.name}\b", source), (table.name, column.name)
        for constraint in table.constraints:
            if constraint.name is not None and not str(constraint.name).startswith("_"):
                assert f"CONSTRAINT {constraint.name} " in flat, (table.name, constraint.name)
        for index in table.indexes:
            assert f"INDEX {index.name} ON knowledge.{table.name}" in flat, (table.name, index.name)
    for name in TRIGGERS | FUNCTIONS | JOB_CONSTRAINTS | {ROOT_UNIQUE}:
        assert name in source, name


def test_the_frozen_capture_declarations_do_not_gain_the_overlay() -> None:
    """MR-C05 / V3: historical `1a4c9e77b2d5` builds both tables from these."""
    assert "lease_generation" not in capture_jobs.c
    assert "pause_cause" not in capture_jobs.c
    assert ROOT_UNIQUE not in {str(constraint.name) for constraint in captures.constraints}


def test_the_revision_writes_no_rows() -> None:
    tree = ast.parse(MIGRATION.read_text(encoding="utf-8"))
    docstring = ast.get_docstring(tree, clean=False)
    texts = [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and node.value != docstring
    ]
    flattened = _WHITESPACE.sub(" ", " ".join(texts)).upper()
    for statement in ("INSERT INTO", "UPDATE KNOWLEDGE", "DELETE FROM", "COPY KNOWLEDGE"):
        assert statement not in flattened, statement
    assert not any(
        isinstance(node, ast.Attribute) and node.attr in {"bulk_insert", "insert", "update"}
        for node in ast.walk(tree)
    )


def test_every_new_foreign_key_restricts_and_is_not_deferrable() -> None:
    flat = _WHITESPACE.sub(" ", MIGRATION.read_text(encoding="utf-8"))
    references = re.findall(r"REFERENCES knowledge\.\w+ \([^)]*\)([^,)]*)", flat)
    assert len(references) == 4
    for tail in references:
        assert "ON DELETE RESTRICT NOT DEFERRABLE" in tail, tail


# ---- offline SQL ----------------------------------------------------------------------


def test_the_offline_upgrade_emits_the_tables_triggers_and_overlay(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("MY_PA_DATABASE_URL", "postgresql+psycopg://localhost/my_pa")
    rendered = _offline(f"{PREVIOUS}:{REVISION}")
    assert f"ADD CONSTRAINT {ROOT_UNIQUE} UNIQUE (capture_id, owner_principal_id)" in rendered
    for name in TABLE_NAMES:
        assert f"CREATE TABLE knowledge.{name} (" in rendered
    for function in FUNCTIONS:
        assert f"CREATE FUNCTION knowledge.{function}()" in rendered
    for trigger in TRIGGERS:
        assert f"CREATE TRIGGER {trigger}" in rendered
    assert "ADD COLUMN lease_generation BIGINT DEFAULT 0 NOT NULL" in rendered
    assert "ADD COLUMN pause_cause TEXT" in rendered
    assert "ADD CONSTRAINT capability_is_known CHECK" in rendered
    assert "'capture.archive'" in rendered and "'capture.restore'" in rendered
    assert f"SET version_num='{REVISION}'" in rendered


def test_the_offline_downgrade_refuses_first_and_unwinds_everything(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("MY_PA_DATABASE_URL", "postgresql+psycopg://localhost/my_pa")
    rendered = _offline(f"{REVISION}:{PREVIOUS}", down=True)
    refusal = rendered.index("refusing to downgrade")
    assert rendered.index("DROP COLUMN pause_cause") > refusal
    for name in TABLE_NAMES:
        assert rendered.index(f"DROP TABLE knowledge.{name} RESTRICT") > refusal
    for trigger in TRIGGERS:
        assert f"DROP TRIGGER {trigger}" in rendered
    assert rendered.index(f"DROP CONSTRAINT {ROOT_UNIQUE}") > rendered.index(
        "DROP TABLE knowledge.capture_lifecycle_events RESTRICT"
    )
    assert "capability IN ('capture.archive', 'capture.restore')" in rendered
    assert f"SET version_num='{PREVIOUS}'" in rendered


# ---- disposable databases -------------------------------------------------------------


@pytest.fixture
def disposable_database(empty_database_url: str) -> str:
    """An empty catalog: this module drives Alembic itself."""
    return empty_database_url


@pytest.fixture
def engine(disposable_database: str) -> Iterator[Engine]:
    built = create_database_engine(disposable_database)
    try:
        yield built
    finally:
        built.dispose()


def _scalar(engine: Engine, sql: str, **params: object) -> object:
    with engine.connect() as connection:
        return connection.execute(text(sql), params).scalar_one()


def _version(engine: Engine) -> str:
    return str(_scalar(engine, "SELECT version_num FROM alembic_version"))


def _tables(engine: Engine) -> set[str]:
    with engine.connect() as connection:
        return set(
            connection.execute(
                text("SELECT tablename FROM pg_tables WHERE schemaname = :schema"),
                {"schema": SCHEMA},
            ).scalars()
        )


def _job_columns(engine: Engine) -> set[str]:
    with engine.connect() as connection:
        return set(
            connection.execute(
                text(
                    "SELECT column_name FROM information_schema.columns "
                    "WHERE table_schema = :schema AND table_name = 'capture_jobs'"
                ),
                {"schema": SCHEMA},
            ).scalars()
        )


def _constraints(engine: Engine) -> set[str]:
    with engine.connect() as connection:
        return set(
            connection.execute(
                text(
                    "SELECT c.conname FROM pg_constraint c "
                    "JOIN pg_namespace n ON n.oid = c.connamespace WHERE n.nspname = :schema"
                ),
                {"schema": SCHEMA},
            ).scalars()
        )


def _seed_root(connection: Connection) -> None:
    connection.execute(
        insert(captures).values(capture_id=CAPTURE, owner_principal_id=PRINCIPAL, created_at=WHEN)
    )
    connection.execute(
        insert(capture_versions).values(
            version_id=VERSION,
            capture_id=CAPTURE,
            version_number=1,
            supersedes_version_id=None,
            content="Synthetic migration note.",
            content_sha256=digest_of("Synthetic migration note."),
            owner_principal_id=PRINCIPAL,
            classification="private_local",
            processing_policy="local_only",
            idempotency_key="clmig-key-1",
            correlation_id="corr_clmig0001corr01",
            audit_id="audit_clmig0001audit1",
            server_received_at=WHEN,
            accepted_at=WHEN,
            recorded_at=WHEN,
        )
    )
    connection.execute(
        insert(capture_jobs).values(
            operation_id=OPERATION_QUEUED, version_id=VERSION, principal_id=PRINCIPAL
        )
    )
    connection.execute(
        insert(capture_jobs).values(
            operation_id=OPERATION_DONE,
            version_id=VERSION,
            principal_id=PRINCIPAL,
            state="succeeded",
            attempt_count=1,
        )
    )


def _archive_event(connection: Connection) -> None:
    connection.execute(
        insert(capture_lifecycle_events).values(
            event_id="clev_clmig0001event01",
            owner_principal_id=PRINCIPAL,
            capture_id=CAPTURE,
            lifecycle_revision=1,
            operation="archive",
            resulting_state="archived",
            transitioned_at=WHEN,
            intent_digest="a" * 64,
            correlation_id="corr_clmig0001corr02",
            audit_id="audit_clmig0001audit2",
            reason_category="owner_stated",
        )
    )


@pytest.mark.database
@pytest.mark.migration_empty_to_head
def test_an_empty_database_upgrades_to_the_capture_lifecycle_head(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    assert _version(engine) == REVISION
    assert _tables(engine) >= TABLE_NAMES
    assert {"lease_generation", "pause_cause"} <= _job_columns(engine)
    assert {ROOT_UNIQUE} | JOB_CONSTRAINTS <= _constraints(engine)


@pytest.mark.database
def test_the_predecessor_with_roots_and_jobs_upgrades_with_everything_active_at_zero(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), PREVIOUS)
    with engine.begin() as connection:
        _seed_root(connection)
    command.upgrade(_config(), REVISION)
    assert _version(engine) == REVISION
    assert _scalar(engine, "SELECT count(*) FROM knowledge.capture_lifecycle_events") == 0
    assert _scalar(engine, "SELECT count(*) FROM knowledge.capture_lifecycle_receipts") == 0
    with engine.connect() as connection:
        jobs = connection.execute(
            text(
                "SELECT operation_id, state, lease_generation, pause_cause "
                "FROM knowledge.capture_jobs ORDER BY operation_id"
            )
        ).all()
    assert [tuple(row) for row in jobs] == [
        (OPERATION_DONE, "succeeded", 0, None),
        (OPERATION_QUEUED, "queued", 0, None),
    ]
    assert _scalar(engine, "SELECT count(*) FROM knowledge.capture_versions") == 1


@pytest.mark.database
def test_a_downgrade_refuses_while_a_lifecycle_event_exists(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        _seed_root(connection)
        _archive_event(connection)
    with pytest.raises(DBAPIError) as refused:
        command.downgrade(_config(), PREVIOUS)
    assert getattr(refused.value.orig, "sqlstate", None) == RESTRICT_VIOLATION
    assert _version(engine) == REVISION
    assert _scalar(engine, "SELECT count(*) FROM knowledge.capture_lifecycle_events") == 1


@pytest.mark.database
def test_a_downgrade_refuses_while_a_lifecycle_receipt_exists(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        _seed_root(connection)
        connection.execute(
            insert(capture_lifecycle_receipts).values(
                receipt_id="clrcpt_clmig0001rcpt01",
                owner_principal_id=PRINCIPAL,
                idempotency_key="clmig-no-op",
                capture_id=CAPTURE,
                operation="restore",
                intent_digest="a" * 64,
                expected_lifecycle_revision=0,
                resulting_lifecycle_revision=0,
                outcome="no_op",
                issued_at=WHEN,
                correlation_id="corr_clmig0001corr03",
                audit_id="audit_clmig0001audit3",
            )
        )
    with pytest.raises(DBAPIError) as refused:
        command.downgrade(_config(), PREVIOUS)
    assert getattr(refused.value.orig, "sqlstate", None) == RESTRICT_VIOLATION
    assert _version(engine) == REVISION


@pytest.mark.database
def test_a_downgrade_refuses_while_a_capture_job_is_paused(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        _seed_root(connection)
        connection.execute(
            text(
                "UPDATE knowledge.capture_jobs SET pause_cause = 'current_policy_ineligible' "
                "WHERE operation_id = :id"
            ),
            {"id": OPERATION_QUEUED},
        )
    with pytest.raises(DBAPIError) as refused:
        command.downgrade(_config(), PREVIOUS)
    assert getattr(refused.value.orig, "sqlstate", None) == RESTRICT_VIOLATION
    assert _version(engine) == REVISION
    assert {"lease_generation", "pause_cause"} <= _job_columns(engine)


@pytest.mark.database
def test_an_empty_downgrade_unwinds_everything_and_upgrades_again(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        _seed_root(connection)
    command.downgrade(_config(), PREVIOUS)
    assert _version(engine) == PREVIOUS
    assert not _tables(engine) & TABLE_NAMES
    assert not {"lease_generation", "pause_cause"} & _job_columns(engine)
    assert not ({ROOT_UNIQUE} | JOB_CONSTRAINTS) & _constraints(engine)
    with engine.connect() as connection:
        functions = set(
            connection.execute(
                text(
                    "SELECT p.proname FROM pg_proc p "
                    "JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = :schema"
                ),
                {"schema": SCHEMA},
            ).scalars()
        )
    assert not functions & FUNCTIONS
    # The synthetic root, version and jobs survive the round trip.
    assert _scalar(engine, "SELECT count(*) FROM knowledge.capture_jobs") == 2
    command.upgrade(_config(), "head")
    assert _version(engine) == REVISION
