"""WP-MTG-04: the one Meeting records revision (plan section 9).

`7d9a450dfd07` was generated by `alembic revision` against the sole head
`6f6ead27d122`, authenticated immediately before generation; nothing about it
was preassigned. This module proves what the plan's section 9.5/9.6 asks of it:

* **the graph** -- exactly one head, `0641c354ca85` (CRL-WP-03, Capture
  lifecycle), on `c8e4a1b70d35` (RE-DBH-01, TRUNCATE refusal), on
  `1d9b248e7f83` (WP-RE-01, Record Events), directly on this revision,
  which is directly on `6f6ead27d122`, and 111 revision files;
* **the freeze** -- the revision imports nothing from the package it migrates,
  names every table, constraint and index `tables.py` declares for the eight
  Meeting tables in frozen text, and restates the audit vocabulary from byte
  copies of `e6a4c2f91b73`, the most recent revision that stated it;
* **offline SQL** for both directions, without a server;
* on disposable databases: empty to head; the predecessor, holding synthetic
  rows on the neighbouring planes, to head; downgrade and re-upgrade; the
  downgrade refusal while a Meeting row exists; the three append-only ledgers
  and the write-request complete-once transition; and the `managed_documents`
  composite unique, which this revision adds unconditionally (operator ruling
  WP02 F-01) -- present at head, removed by the downgrade, restored by the
  re-upgrade -- together with the Meeting attachment reference that needs it.

The file name routes every test here to migration-edge (`tests/db/fixtures.py`);
the empty-to-head test carries its own marker, and the tests with no `database`
marker also run in FAST. Every value is synthetic.
"""

from __future__ import annotations

import ast
import io
import re
from collections.abc import Callable, Iterator
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Final

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import Engine, Table, insert, text, update
from sqlalchemy.engine import Connection
from sqlalchemy.exc import DBAPIError, IntegrityError

from my_pa.domain.common.identifiers import IdKind
from my_pa.domain.identity.operation import Capability, NativeSourceCapability
from my_pa.domain.identity.purpose import Purpose
from my_pa.domain.source.registry import issue_identifier
from my_pa.infrastructure.database.engine import create_database_engine
from my_pa.infrastructure.persistence.tables import (
    audit_events,
    entities,
    managed_document_versions,
    managed_documents,
    meeting_attachments,
    meeting_attendees,
    meeting_history,
    meeting_note_versions,
    meeting_series,
    meeting_series_history,
    meeting_write_requests,
    meetings,
    projects,
)

ROOT: Final = Path(__file__).resolve().parents[2]
SCHEMA: Final = "knowledge"
REVISION: Final = "7d9a450dfd07"
PREVIOUS: Final = "6f6ead27d122"
#: The chain head these tests run against. `1d9b248e7f83` (WP-RE-01, Record
#: Events) is additive on `REVISION`, and `0641c354ca85` (CRL-WP-03, Capture
#: lifecycle) is additive on that, so `REVISION` is no longer the head.
HEAD: Final = "6734f039f7a6"
#: The revision that last stated `capability_is_known` and `purpose_is_known`,
#: and therefore the only correct source for this revision's BEFORE literals.
VOCABULARY_PREDECESSOR: Final = "e6a4c2f91b73"
MIGRATIONS: Final = ROOT / "migrations" / "versions"
MIGRATION: Final = MIGRATIONS / "20260927_7d9a450dfd07_meeting_records.py"
VOCABULARY_MIGRATION: Final = (
    MIGRATIONS / "20260914_e6a4c2f91b73_project_controls_run01_integrity.py"
)

MEETING_TABLES: Final[tuple[Table, ...]] = (
    meeting_series,
    meetings,
    meeting_attendees,
    meeting_attachments,
    meeting_history,
    meeting_note_versions,
    meeting_series_history,
    meeting_write_requests,
)
MEETING_TABLE_NAMES: Final = frozenset(table.name for table in MEETING_TABLES)
TRIGGERS: Final[dict[str, str]] = {
    "meeting_history_rows_are_append_only": "meeting_history_stays_append_only",
    "meeting_note_versions_are_append_only": "meeting_note_versions_stay_append_only",
    "meeting_series_history_rows_are_append_only": "meeting_series_history_stays_append_only",
    "meeting_write_requests_complete_once": "meeting_write_request_completes_once",
}
OWNER_UNIQUE: Final = "a_managed_document_is_identified_within_its_owner"
ADMITTED_CAPABILITIES: Final = frozenset(
    {
        "meetings.create",
        "meetings.list",
        "meetings.read",
        "meetings.search",
        "meetings.series.update",
        "meetings.update",
    }
)
ADMITTED_PURPOSES: Final = frozenset({"meeting_authoring", "meeting_read"})

PRINCIPAL: Final = "prn_mtgmig0001mtgmig0001"
OTHER_PRINCIPAL: Final = "prn_mtgmig0002mtgmig0002"
WHEN: Final = datetime(2026, 9, 27, 12, tzinfo=UTC)
DIGEST: Final = "a" * 64
_WHITESPACE: Final = re.compile(r"\s+")

#: PostgreSQL's `restrict_violation`, which every Meeting trigger raises.
RESTRICT_VIOLATION: Final = "23001"


def _config(buffer: io.StringIO | None = None) -> Config:
    return Config(str(ROOT / "alembic.ini"), output_buffer=buffer)


def _constant(source: str, name: str) -> str:
    """One spelled `Final` literal, as written, including its line breaks."""
    found = re.search(rf"^{name}: Final = \(\n(.*?)^\)\n", source, re.S | re.M)
    assert found is not None, f"{name} is not spelled in the revision"
    return found.group(1)


def _literals(block: str) -> list[str]:
    return re.findall(r"'([^']+)'", block)


def _offline(target: str, *, down: bool = False) -> str:
    buffer = io.StringIO()
    action = command.downgrade if down else command.upgrade
    action(_config(buffer), target, sql=True)
    return _WHITESPACE.sub(" ", buffer.getvalue())


# ---- the graph --------------------------------------------------------------


def test_the_revision_is_the_single_head_directly_on_the_previous_head() -> None:
    script = ScriptDirectory.from_config(_config())
    assert script.get_heads() == [HEAD]
    assert script.get_revision(HEAD).down_revision == "0641c354ca85"
    assert script.get_revision("0641c354ca85").down_revision == "c8e4a1b70d35"
    assert script.get_revision("c8e4a1b70d35").down_revision == "1d9b248e7f83"
    assert script.get_revision("1d9b248e7f83").down_revision == REVISION
    assert script.get_revision(REVISION).down_revision == PREVIOUS
    assert script.get_revision(PREVIOUS).down_revision == VOCABULARY_PREDECESSOR


def test_the_chain_holds_the_files_it_claims() -> None:
    assert len(list(MIGRATIONS.glob("*.py"))) == 112


# ---- the freeze -------------------------------------------------------------


def test_revision_imports_no_domain_or_persistence_modules() -> None:
    source = MIGRATION.read_text(encoding="utf-8")
    imported: set[str] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ImportFrom) and node.module is not None:
            imported.add(node.module)
        elif isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
    assert imported <= {"alembic", "__future__", "typing"}
    assert "my_pa" not in source
    assert "create_all" not in source


def test_the_frozen_ddl_names_every_declared_table_constraint_and_index() -> None:
    """The revision's text and `tables.py` name the same Meeting schema objects.

    Parity of the *definitions* is proved on a server by the WP-MTG-02
    persistence tests and by `test_every_revision_denotes_one_schema.py`; this is
    the static half, which runs without one.
    """
    source = MIGRATION.read_text(encoding="utf-8")
    for table in MEETING_TABLES:
        assert f"CREATE TABLE knowledge.{table.name} (" in source
        for column in table.c:
            assert re.search(rf"\b{column.name}\b", source), (table.name, column.name)
        for constraint in table.constraints:
            if constraint.name is not None and not str(constraint.name).startswith("_"):
                assert str(constraint.name) in source, (table.name, constraint.name)
        for index in table.indexes:
            assert f"INDEX {index.name} ON knowledge.{table.name}" in _WHITESPACE.sub(
                " ", source
            ), (table.name, index.name)
    assert OWNER_UNIQUE in source
    for trigger, function in TRIGGERS.items():
        assert trigger in source
        assert function in source


def test_the_before_texts_are_byte_copies_of_the_vocabulary_predecessor() -> None:
    source = MIGRATION.read_text(encoding="utf-8")
    previous = VOCABULARY_MIGRATION.read_text(encoding="utf-8")
    assert _constant(source, "_CAPABILITIES_BEFORE_THIS_REVISION") == _constant(
        previous, "_CAPABILITIES_AT_THIS_REVISION"
    )
    assert _constant(source, "_PURPOSES_BEFORE_THIS_REVISION") == _constant(
        previous, "_PURPOSES_AT_THIS_REVISION"
    )


def test_no_revision_between_the_vocabulary_predecessor_and_this_one_restates_the_sets() -> None:
    script = ScriptDirectory.from_config(_config())
    between: list[str] = []
    current = script.get_revision(REVISION).down_revision
    while current != VOCABULARY_PREDECESSOR:
        assert isinstance(current, str)
        between.append(current)
        current = script.get_revision(current).down_revision
    assert between == [PREVIOUS]
    for revision in between:
        restated = Path(script.get_revision(revision).path).read_text(encoding="utf-8")
        for constraint in ("capability_is_known", "purpose_is_known"):
            assert re.search(rf"(?<![A-Za-z0-9_]){constraint}", restated) is None


def test_the_at_texts_add_exactly_the_meeting_vocabulary_and_stay_sorted() -> None:
    """Frozen literal == prior restated set, plus exactly the six and the two."""
    source = MIGRATION.read_text(encoding="utf-8")
    before = _literals(_constant(source, "_CAPABILITIES_BEFORE_THIS_REVISION"))
    at = _literals(_constant(source, "_CAPABILITIES_AT_THIS_REVISION"))
    assert set(at) == set(before) | ADMITTED_CAPABILITIES
    assert len(at) == len(before) + len(ADMITTED_CAPABILITIES)
    assert at == sorted(at)
    purposes_before = _literals(_constant(source, "_PURPOSES_BEFORE_THIS_REVISION"))
    purposes_at = _literals(_constant(source, "_PURPOSES_AT_THIS_REVISION"))
    assert set(purposes_at) == set(purposes_before) | ADMITTED_PURPOSES
    assert len(purposes_at) == len(purposes_before) + len(ADMITTED_PURPOSES)
    assert purposes_at == sorted(purposes_at)


#: What the next vocabulary restatement (`1d9b248e7f83`, WP-RE-06) admits; this
#: revision's AT set is every name declared *before* it.
ADMITTED_LATER_CAPABILITIES: Final = frozenset(
    {
        "record_events.list",
        "capture.archive",
        "capture.restore",
        # KLP-WP-03: admitted by the Knowledge revision `6734f039f7a6` (KLP-WP-02)
        # and declared since.
        "knowledge.assertions.read",
        "knowledge.assertions.list",
        "knowledge.assertions.search",
        "knowledge.assertions.history",
        "knowledge.assertions.reveal",
        "knowledge.assertions.create",
        # KLP-WP-04: the discovery pair, admitted by the same revision.
        "knowledge.assertions.submit",
        "knowledge.discovery.checkpoint",
        # KLP-WP-05: the provenance read, admitted by the same revision.
        "record_events.provenance",
    }
)
ADMITTED_LATER_PURPOSES: Final = frozenset(
    {
        "record_event_read",
        "knowledge_assertion_read",
        "knowledge_assertion_authoring",
        "knowledge_assertion_observation",
        "record_event_provenance_read",
    }
)


def test_head_admits_every_declared_capability_and_purpose() -> None:
    """A subset, not equality: the audit set also holds the operator names.

    Every name declared today is admitted here except the ones the next
    restatement admits, which `tests/schema/test_record_events_migration.py`
    holds to that revision.
    """
    source = MIGRATION.read_text(encoding="utf-8")
    at = set(_literals(_constant(source, "_CAPABILITIES_AT_THIS_REVISION")))
    purposes_at = set(_literals(_constant(source, "_PURPOSES_AT_THIS_REVISION")))
    declared = {capability.value for capability in Capability}
    assert declared - ADMITTED_LATER_CAPABILITIES <= at
    assert not ADMITTED_LATER_CAPABILITIES & at
    assert {purpose.value for purpose in Purpose} - ADMITTED_LATER_PURPOSES <= purposes_at
    assert not ADMITTED_LATER_PURPOSES & purposes_at
    assert at - declared == {capability.value for capability in NativeSourceCapability}


# ---- offline SQL -------------------------------------------------------------


def test_the_offline_upgrade_emits_the_whole_revision(monkeypatch: pytest.MonkeyPatch) -> None:
    # Rendered, not run: the settings need a URL and nothing connects to it.
    monkeypatch.setenv("MY_PA_DATABASE_URL", "postgresql+psycopg://localhost/my_pa")
    rendered = _offline(f"{PREVIOUS}:{REVISION}")
    for name in MEETING_TABLE_NAMES:
        assert f"CREATE TABLE knowledge.{name} (" in rendered
    assert (
        f"ALTER TABLE knowledge.managed_documents ADD CONSTRAINT {OWNER_UNIQUE} "
        "UNIQUE (document_id, owner_principal_id)"
    ) in rendered
    for trigger, function in TRIGGERS.items():
        assert f"CREATE FUNCTION knowledge.{function}()" in rendered
        assert f"CREATE TRIGGER {trigger}" in rendered
    assert "ADD CONSTRAINT capability_is_known CHECK" in rendered
    assert "'knowledge.search', 'meetings.create', 'meetings.list'" in rendered
    assert "'knowledge_search', 'meeting_authoring', 'meeting_read'" in rendered
    assert f"SET version_num='{REVISION}'" in rendered


def test_the_offline_downgrade_refuses_first_and_unwinds_everything(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("MY_PA_DATABASE_URL", "postgresql+psycopg://localhost/my_pa")
    rendered = _offline(f"{REVISION}:{PREVIOUS}", down=True)
    refusal = rendered.index("refusing to downgrade")
    for name in MEETING_TABLE_NAMES:
        assert rendered.index(f"DROP TABLE knowledge.{name} RESTRICT") > refusal
    for trigger, function in TRIGGERS.items():
        assert f"DROP TRIGGER {trigger}" in rendered
        assert f"DROP FUNCTION knowledge.{function}()" in rendered
    assert f"ALTER TABLE knowledge.managed_documents DROP CONSTRAINT {OWNER_UNIQUE}" in rendered
    assert "'meetings.create'" in rendered.split("ADD CONSTRAINT capability_is_known CHECK")[0]
    assert f"SET version_num='{PREVIOUS}'" in rendered


# ---- disposable databases -------------------------------------------------------


@pytest.fixture
def disposable_database(empty_database_url: str) -> str:
    """An empty catalog: this module drives Alembic itself."""
    return empty_database_url


@pytest.fixture
def engine(disposable_database: str) -> Iterator[Engine]:
    built = create_database_engine(disposable_database)
    try:
        yield built
    finally:
        built.dispose()


def _catalog(engine: Engine) -> dict[str, set[str]]:
    with engine.connect() as connection:
        tables = set(
            connection.execute(
                text("SELECT tablename FROM pg_tables WHERE schemaname = :schema"),
                {"schema": SCHEMA},
            ).scalars()
        )
        constraints = set(
            connection.execute(
                text(
                    "SELECT c.conname FROM pg_constraint c "
                    "JOIN pg_namespace n ON n.oid = c.connamespace WHERE n.nspname = :schema"
                ),
                {"schema": SCHEMA},
            ).scalars()
        )
        triggers = set(
            connection.execute(
                text(
                    "SELECT t.tgname FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid "
                    "JOIN pg_namespace n ON n.oid = c.relnamespace "
                    "WHERE NOT t.tgisinternal AND n.nspname = :schema"
                ),
                {"schema": SCHEMA},
            ).scalars()
        )
        functions = set(
            connection.execute(
                text(
                    "SELECT p.proname FROM pg_proc p "
                    "JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = :schema"
                ),
                {"schema": SCHEMA},
            ).scalars()
        )
        version = set(connection.execute(text("SELECT version_num FROM alembic_version")).scalars())
    return {
        "tables": tables,
        "constraints": constraints,
        "triggers": triggers,
        "functions": functions,
        "version": version,
    }


def _assert_meeting_schema_present(engine: Engine, *, at: str = HEAD) -> None:
    catalog = _catalog(engine)
    assert catalog["version"] == {at}
    assert catalog["tables"] >= MEETING_TABLE_NAMES
    assert OWNER_UNIQUE in catalog["constraints"]
    assert catalog["triggers"] >= set(TRIGGERS)
    assert catalog["functions"] >= set(TRIGGERS.values())


def _assert_meeting_schema_absent(engine: Engine) -> None:
    catalog = _catalog(engine)
    assert catalog["version"] == {PREVIOUS}
    assert not catalog["tables"] & MEETING_TABLE_NAMES
    assert OWNER_UNIQUE not in catalog["constraints"]
    assert not catalog["triggers"] & set(TRIGGERS)
    assert not catalog["functions"] & set(TRIGGERS.values())


def _audit(connection: Connection, *, capability: str, purpose: str, suffix: str) -> None:
    connection.execute(
        insert(audit_events).values(
            audit_id=f"audit_{suffix}",
            correlation_id=f"corr_{suffix}",
            principal_id=PRINCIPAL,
            capability=capability,
            purpose=purpose,
            outcome="allowed",
            policy_version="policy-v1",
            scope_source_id_count=0,
            recorded_at=WHEN,
        )
    )


def _seed_neighbours(connection: Connection) -> dict[str, str]:
    """Synthetic rows on the planes a Meeting references, written before it exists."""
    rows = {
        "project": "prj_mtgmig0001mtgmig0001",
        "entity": "ent_mtgmig0001mtgmig0001",
        "document": "mdoc_mtgmig0001mtgmig0001",
        "foreign_document": "mdoc_mtgmig0002mtgmig0002",
    }
    connection.execute(
        insert(projects).values(
            project_id=rows["project"],
            principal_id=PRINCIPAL,
            name="Synthetic project",
            state="active",
            participants=[],
            opened_at=WHEN,
            created_at=WHEN,
            updated_at=WHEN,
        )
    )
    connection.execute(
        insert(entities).values(
            entity_id=rows["entity"],
            principal_id=PRINCIPAL,
            entity_type="person",
            canonical_name="synthetic person",
            display_name="Synthetic person",
            status="active",
            created_at=WHEN,
            updated_at=WHEN,
            version=1,
        )
    )
    for key, owner in (("document", PRINCIPAL), ("foreign_document", OTHER_PRINCIPAL)):
        connection.execute(
            insert(managed_documents).values(
                document_id=rows[key], owner_principal_id=owner, created_at=WHEN
            )
        )
        connection.execute(
            insert(managed_document_versions).values(
                version_id=issue_identifier(IdKind.MANAGED_DOCUMENT_VERSION),
                document_id=rows[key],
                version_number=1,
                supersedes_version_id=None,
                owner_principal_id=owner,
                title="Synthetic agenda",
                media_type="text/markdown",
                content_sha256="b" * 64,
                byte_size=16,
                idempotency_key=f"doc-{key}",
                correlation_id=issue_identifier(IdKind.CORRELATION),
                recorded_at=WHEN,
            )
        )
    _audit(
        connection, capability="capture.create", purpose="capture_authoring", suffix="mtgmig0001x"
    )
    return rows


def _seed_meeting(connection: Connection, *, suffix: str = "0001") -> dict[str, str]:
    """One series-bound Meeting with its receipt, note and completed write request."""
    ids = {
        "series": f"mser_mtgmig{suffix}series",
        "meeting": f"mtg_mtgmig{suffix}meeting",
        "history": f"mhst_mtgmig{suffix}history",
        "series_history": f"mshst_mtgmig{suffix}history",
        "note": f"mnote_mtgmig{suffix}note00",
    }
    connection.execute(
        insert(meeting_series).values(
            meeting_series_id=ids["series"],
            principal_id=PRINCIPAL,
            title="A synthetic series",
            version=1,
            created_at=WHEN,
            updated_at=WHEN,
        )
    )
    connection.execute(
        insert(meeting_series_history).values(
            series_history_id=ids["series_history"],
            principal_id=PRINCIPAL,
            meeting_series_id=ids["series"],
            action="create",
            actor="principal",
            outcome="applied",
            before_version=0,
            after_version=1,
            idempotency_key=f"mig-{suffix}",
            request_digest=DIGEST,
            occurred_at=WHEN,
            recorded_at=WHEN,
        )
    )
    connection.execute(
        insert(meetings).values(
            meeting_id=ids["meeting"],
            principal_id=PRINCIPAL,
            meeting_series_id=ids["series"],
            title="A synthetic meeting",
            start_at=WHEN,
            timezone_name="UTC",
            status="scheduled",
            version=1,
            created_at=WHEN,
            updated_at=WHEN,
        )
    )
    connection.execute(
        insert(meeting_history).values(
            history_id=ids["history"],
            principal_id=PRINCIPAL,
            meeting_id=ids["meeting"],
            meeting_series_id=ids["series"],
            action="create",
            actor="principal",
            outcome="applied",
            before_version=0,
            after_version=1,
            idempotency_key=f"mig-{suffix}",
            request_digest=DIGEST,
            occurred_at=WHEN,
            recorded_at=WHEN,
        )
    )
    connection.execute(
        insert(meeting_note_versions).values(
            note_version_id=ids["note"],
            principal_id=PRINCIPAL,
            meeting_id=ids["meeting"],
            version_number=1,
            supersedes_note_version_id=None,
            content_markdown="Synthetic note.",
            content_sha256="c" * 64,
            meeting_history_id=ids["history"],
            recorded_at=WHEN,
        )
    )
    return ids


def _reserve(connection: Connection, key: str) -> None:
    connection.execute(
        insert(meeting_write_requests).values(
            principal_id=PRINCIPAL,
            capability="meetings.create",
            idempotency_key=key,
            request_digest=DIGEST,
            created_at=WHEN,
        )
    )


def _refused_by_trigger(engine: Engine, statement: Callable[[Connection], Any]) -> None:
    with pytest.raises(DBAPIError) as refused, engine.begin() as connection:
        statement(connection)
    assert getattr(refused.value.orig, "sqlstate", None) == RESTRICT_VIOLATION, refused.value


@pytest.mark.database
@pytest.mark.migration_empty_to_head
def test_an_empty_database_upgrades_to_the_meeting_head(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    _assert_meeting_schema_present(engine)
    with engine.begin() as connection:
        _audit(
            connection,
            capability="meetings.create",
            purpose="meeting_authoring",
            suffix="mtgmig0002x",
        )
        _audit(connection, capability="meetings.read", purpose="meeting_read", suffix="mtgmig0003x")


@pytest.mark.database
def test_the_previous_head_with_neighbouring_rows_upgrades_to_the_meeting_head(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), PREVIOUS)
    with engine.begin() as connection:
        rows = _seed_neighbours(connection)
    command.upgrade(_config(), REVISION)
    _assert_meeting_schema_present(engine, at=REVISION)
    with engine.begin() as connection:
        ids = _seed_meeting(connection)
        connection.execute(
            insert(meeting_attachments).values(
                attachment_id="matc_mtgmig0001attach",
                principal_id=PRINCIPAL,
                meeting_id=ids["meeting"],
                document_id=rows["document"],
                added_at=WHEN,
            )
        )
        connection.execute(
            insert(meeting_attendees).values(
                attendee_id="matt_mtgmig0001attend",
                principal_id=PRINCIPAL,
                meeting_id=ids["meeting"],
                entity_id=rows["entity"],
                added_at=WHEN,
            )
        )
        connection.execute(
            update(meetings)
            .where(meetings.c.meeting_id == ids["meeting"])
            .values(project_id=rows["project"])
        )
        stored = connection.execute(
            text("SELECT count(*) FROM knowledge.audit_events WHERE capability = 'capture.create'")
        ).scalar_one()
    assert stored == 1


@pytest.mark.database
def test_the_owner_unique_is_added_removed_and_restored_with_the_revision(
    disposable_database: str, engine: Engine
) -> None:
    """Operator ruling WP02 F-01: unconditional ADD, and its exact inverse."""
    del disposable_database
    command.upgrade(_config(), "head")
    assert OWNER_UNIQUE in _catalog(engine)["constraints"]
    command.downgrade(_config(), PREVIOUS)
    _assert_meeting_schema_absent(engine)
    command.upgrade(_config(), "head")
    _assert_meeting_schema_present(engine)


@pytest.mark.database
def test_a_downgrade_refuses_while_a_meeting_row_exists(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        _seed_meeting(connection)
    with pytest.raises(DBAPIError) as refused:
        command.downgrade(_config(), PREVIOUS)
    assert "refusing to downgrade" in str(refused.value)
    # Each revision downgrades in its own transaction, so the empty Record Event
    # head above this one has already gone when this revision refuses.
    _assert_meeting_schema_present(engine, at=REVISION)


@pytest.mark.database
def test_a_downgrade_refuses_while_an_audit_event_names_the_meeting_vocabulary(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        _audit(connection, capability="meetings.list", purpose="meeting_read", suffix="mtgmig0004x")
    with pytest.raises(DBAPIError):
        command.downgrade(_config(), PREVIOUS)
    _assert_meeting_schema_present(engine, at=REVISION)


@pytest.mark.database
def test_the_ledgers_are_append_only(disposable_database: str, engine: Engine) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        ids = _seed_meeting(connection)
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            update(meeting_history)
            .where(meeting_history.c.history_id == ids["history"])
            .values(outcome="no_op")
        ),
    )
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            meeting_history.delete().where(meeting_history.c.history_id == ids["history"])
        ),
    )
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            update(meeting_note_versions)
            .where(meeting_note_versions.c.note_version_id == ids["note"])
            .values(content_markdown="Rewritten.")
        ),
    )
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            meeting_note_versions.delete().where(
                meeting_note_versions.c.note_version_id == ids["note"]
            )
        ),
    )
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            update(meeting_series_history)
            .where(meeting_series_history.c.series_history_id == ids["series_history"])
            .values(outcome="no_op")
        ),
    )
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            meeting_series_history.delete().where(
                meeting_series_history.c.series_history_id == ids["series_history"]
            )
        ),
    )


@pytest.mark.database
def test_a_write_request_completes_exactly_once(disposable_database: str, engine: Engine) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        ids = _seed_meeting(connection)
        _reserve(connection, "mig-complete")
        _reserve(connection, "mig-identity")

    def complete(connection: Connection, key: str) -> None:
        connection.execute(
            update(meeting_write_requests)
            .where(meeting_write_requests.c.idempotency_key == key)
            .values(
                completed_at=WHEN,
                meeting_id=ids["meeting"],
                meeting_series_id=ids["series"],
                meeting_history_id=ids["history"],
                result_version=1,
            )
        )

    with engine.begin() as connection:
        complete(connection, "mig-complete")
    # A second completion, a change of identity, an update that does not
    # complete, and a delete are each refused by the transition trigger.
    _refused_by_trigger(engine, lambda c: complete(c, "mig-complete"))
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            update(meeting_write_requests)
            .where(meeting_write_requests.c.idempotency_key == "mig-identity")
            .values(request_digest="d" * 64)
        ),
    )
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            update(meeting_write_requests)
            .where(meeting_write_requests.c.idempotency_key == "mig-identity")
            .values(created_at=WHEN.replace(hour=13))
        ),
    )
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            meeting_write_requests.delete().where(
                meeting_write_requests.c.idempotency_key == "mig-identity"
            )
        ),
    )
    _refused_by_trigger(
        engine,
        lambda c: c.execute(
            meeting_write_requests.delete().where(
                meeting_write_requests.c.idempotency_key == "mig-complete"
            )
        ),
    )


@pytest.mark.database
def test_an_attachment_cannot_name_another_principals_document(
    disposable_database: str, engine: Engine
) -> None:
    """The composite unique is what the attachment's same-Principal reference needs."""
    del disposable_database
    command.upgrade(_config(), PREVIOUS)
    with engine.begin() as connection:
        rows = _seed_neighbours(connection)
    command.upgrade(_config(), "head")
    with engine.begin() as connection:
        ids = _seed_meeting(connection)
    with pytest.raises(IntegrityError) as refused, engine.begin() as connection:
        connection.execute(
            insert(meeting_attachments).values(
                attachment_id="matc_mtgmig0002attach",
                principal_id=PRINCIPAL,
                meeting_id=ids["meeting"],
                document_id=rows["foreign_document"],
                added_at=WHEN,
            )
        )
    assert "a_meeting_attachment_names_a_document_of_its_principal" in str(refused.value)
