"""WP-RE-06: the one Record Event revision, `1d9b248e7f83` (RE-AC-004, 077-083).

Generated by `alembic revision` in WP-RE-01 against the sole head
`7d9a450dfd07` (OD-4 (B)); at the WP-RE-06 re-authentication the head was
unchanged, so nothing was re-pointed, and WP-RE-06 added the audit-vocabulary
restatement. This module proves:

* **the graph** -- the single head, directly on `7d9a450dfd07` (RE-AC-082);
* **the freeze** -- no package import; the frozen DDL names every column,
  constraint and index `tables.py` declares for the two tables, and the feed's
  columns are exactly the metadata allow-list, with no payload column
  (RE-AC-004);
* **the vocabulary** -- the BEFORE literals are byte copies of `7d9a450dfd07`'s
  AT literals and the AT literals add exactly `record_events.list` and
  `record_event_read`, sorted, 190 and 48 names (RE-AC-077);
* **no backfill** -- the revision writes no row (RE-AC-083);
* **offline SQL** for both directions;
* on disposable databases: the previous head holding canonical and audit rows
  upgrades with an empty feed (RE-AC-078, 083); the head admits the new audit
  vocabulary (RE-AC-077); the downgrade refuses while a Record Event, an
  allocator row or an audit row naming the new vocabulary exists (RE-AC-080);
  an empty downgrade restores the Meeting head's vocabulary and drops
  everything (RE-AC-081); and an empty database reaches the head (RE-AC-079,
  explicit `migration_empty_to_head`).

The file name routes every `database` test here to migration-edge
(`tests/db/fixtures.py`); the tests with no marker also run in FAST. Every value
is synthetic.
"""

from __future__ import annotations

import ast
import io
import re
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path
from typing import Final

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import Engine, insert, text
from sqlalchemy.engine import Connection
from sqlalchemy.exc import DBAPIError
from tests.schema.test_meeting_records_migration import _audit, _seed_meeting

from my_pa.domain.identity.operation import Capability, NativeSourceCapability
from my_pa.domain.identity.purpose import Purpose
from my_pa.infrastructure.database.engine import create_database_engine
from my_pa.infrastructure.persistence.tables import (
    record_event_sequences,
    record_events,
)

ROOT: Final = Path(__file__).resolve().parents[2]
SCHEMA: Final = "knowledge"
REVISION: Final = "1d9b248e7f83"
#: The chain head. `0641c354ca85` (CRL-WP-03, Capture lifecycle) is additive on
#: `REVISION`, so `REVISION` is no longer the head; a database upgraded to head
#: stands there, and a refused downgrade leaves it there.
HEAD: Final = "6734f039f7a6"
PREVIOUS: Final = "7d9a450dfd07"
MIGRATIONS: Final = ROOT / "migrations" / "versions"
MIGRATION: Final = MIGRATIONS / "20260929_1d9b248e7f83_record_events.py"
HEAD_MIGRATION: Final = MIGRATIONS / "20261001_0641c354ca85_capture_lifecycle.py"
VOCABULARY_MIGRATION: Final = MIGRATIONS / "20260927_7d9a450dfd07_meeting_records.py"
TABLE_NAMES: Final = frozenset({"record_event_sequences", "record_events"})
TRIGGER: Final = "record_events_are_append_only"
FUNCTION: Final = "record_events_stay_append_only"
ADMITTED_CAPABILITIES: Final = frozenset({"record_events.list"})
ADMITTED_PURPOSES: Final = frozenset({"record_event_read"})

#: RE-AC-004: the feed row is metadata only. The exact column allow-list.
FEED_COLUMNS: Final = frozenset(
    {
        "event_id",
        "principal_id",
        "sequence_number",
        "record_family",
        "record_id",
        "event_kind",
        "record_version",
        "changed_fields",
        "source_capability",
        "source_receipt_id",
        "actor_class",
        "authority",
        "classification",
        "correlation_id",
        "causation_event_id",
        "occurred_at",
        "recorded_at",
    }
)

PRINCIPAL: Final = "prn_mtgmig0001mtgmig0001"
WHEN: Final = datetime(2026, 9, 30, 12, tzinfo=UTC)
RESTRICT_VIOLATION: Final = "23001"
_WHITESPACE: Final = re.compile(r"\s+")


def _config(buffer: io.StringIO | None = None) -> Config:
    return Config(str(ROOT / "alembic.ini"), output_buffer=buffer)


def _constant(source: str, name: str) -> str:
    found = re.search(rf"^{name}: Final = \(\n(.*?)^\)\n", source, re.S | re.M)
    assert found is not None, f"{name} is not spelled in the revision"
    return found.group(1)


def _literals(block: str) -> list[str]:
    return re.findall(r"'([^']+)'", block)


def _offline(target: str, *, down: bool = False) -> str:
    buffer = io.StringIO()
    action = command.downgrade if down else command.upgrade
    action(_config(buffer), target, sql=True)
    return _WHITESPACE.sub(" ", buffer.getvalue())


# ---- the graph (RE-AC-082) -------------------------------------------------------


def test_the_revision_is_directly_on_7d9a450dfd07_under_one_later_head() -> None:
    script = ScriptDirectory.from_config(_config())
    assert script.get_revision(REVISION).down_revision == PREVIOUS
    assert script.get_heads() == [HEAD]
    assert script.get_revision(HEAD).down_revision == "0641c354ca85"
    assert script.get_revision("0641c354ca85").down_revision == "c8e4a1b70d35"
    assert script.get_revision("c8e4a1b70d35").down_revision == REVISION


# ---- the freeze (RE-AC-004) ------------------------------------------------------


def test_revision_imports_no_domain_or_persistence_modules() -> None:
    source = MIGRATION.read_text(encoding="utf-8")
    imported: set[str] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ImportFrom) and node.module is not None:
            imported.add(node.module)
        elif isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
    assert imported <= {"alembic", "__future__", "typing"}
    assert "my_pa" not in source
    assert "create_all" not in source


def test_the_feed_columns_are_exactly_the_metadata_allow_list() -> None:
    assert {column.name for column in record_events.c} == FEED_COLUMNS
    assert {column.name for column in record_event_sequences.c} == {
        "principal_id",
        "next_sequence",
    }
    source = MIGRATION.read_text(encoding="utf-8")
    create = source[source.index("CREATE TABLE knowledge.record_events (") :]
    for forbidden in ("payload", "body", "statement", "before", "after", "snapshot", "value"):
        assert not re.search(rf"^\s+{forbidden}\w* ", create, re.M), forbidden


def test_the_frozen_ddl_names_every_declared_column_constraint_and_index() -> None:
    source = MIGRATION.read_text(encoding="utf-8")
    for table in (record_event_sequences, record_events):
        assert f"CREATE TABLE knowledge.{table.name} (" in source
        for column in table.c:
            assert re.search(rf"\b{column.name}\b", source), (table.name, column.name)
        for constraint in table.constraints:
            if constraint.name is not None and not str(constraint.name).startswith("_"):
                assert str(constraint.name) in source, (table.name, constraint.name)
        for index in table.indexes:
            assert f"INDEX {index.name} ON knowledge.{table.name}" in _WHITESPACE.sub(
                " ", source
            ), (table.name, index.name)
    assert TRIGGER in source
    assert FUNCTION in source


# ---- the vocabulary (RE-AC-077) -----------------------------------------------------


def test_the_before_texts_are_byte_copies_of_the_meeting_revision() -> None:
    source = MIGRATION.read_text(encoding="utf-8")
    previous = VOCABULARY_MIGRATION.read_text(encoding="utf-8")
    assert _constant(source, "_CAPABILITIES_BEFORE_THIS_REVISION") == _constant(
        previous, "_CAPABILITIES_AT_THIS_REVISION"
    )
    assert _constant(source, "_PURPOSES_BEFORE_THIS_REVISION") == _constant(
        previous, "_PURPOSES_AT_THIS_REVISION"
    )


def test_the_at_texts_add_exactly_the_record_event_vocabulary_and_stay_sorted() -> None:
    source = MIGRATION.read_text(encoding="utf-8")
    before = _literals(_constant(source, "_CAPABILITIES_BEFORE_THIS_REVISION"))
    at = _literals(_constant(source, "_CAPABILITIES_AT_THIS_REVISION"))
    assert set(at) == set(before) | ADMITTED_CAPABILITIES
    assert len(at) == len(before) + 1 == 190
    assert at == sorted(at)
    purposes_before = _literals(_constant(source, "_PURPOSES_BEFORE_THIS_REVISION"))
    purposes_at = _literals(_constant(source, "_PURPOSES_AT_THIS_REVISION"))
    assert set(purposes_at) == set(purposes_before) | ADMITTED_PURPOSES
    assert len(purposes_at) == len(purposes_before) + 1 == 48
    assert purposes_at == sorted(purposes_at)


def test_head_admits_every_declared_capability_and_purpose() -> None:
    """A subset, not equality: the audit set also holds the operator names.

    The chain head is `0641c354ca85`, which restates the vocabulary in place.
    This revision's own AT set is proven above and no longer is that head.
    """
    source = HEAD_MIGRATION.read_text(encoding="utf-8")
    at = set(_literals(_constant(source, "_CAPABILITIES_AT_THIS_REVISION")))
    purposes_at = set(_literals(_constant(source, "_PURPOSES_AT_THIS_REVISION")))
    declared = {capability.value for capability in Capability}
    assert declared <= at
    assert {purpose.value for purpose in Purpose} <= purposes_at
    assert at - declared == {capability.value for capability in NativeSourceCapability}


def test_the_downgrade_refusal_names_the_new_vocabulary() -> None:
    refusal = _constant_text(MIGRATION.read_text(encoding="utf-8"), "_REFUSE_DOWNGRADE")
    assert "knowledge.record_events" in refusal
    assert "knowledge.record_event_sequences" in refusal
    assert "knowledge.audit_events" in refusal
    assert "capability = 'record_events.list'" in refusal
    assert "purpose = 'record_event_read'" in refusal


def _constant_text(source: str, name: str) -> str:
    found = re.search(rf'^{name}: Final = """(.*?)"""', source, re.S | re.M)
    assert found is not None
    return found.group(1)


# ---- no backfill (RE-AC-083) --------------------------------------------------------


def test_the_revision_writes_no_rows() -> None:
    """Every SQL text the revision can execute: no INSERT, UPDATE, DELETE or COPY.

    Read from the string constants (comments and the docstring excluded), so
    the phrase "byte copy" in a comment is not mistaken for a statement.
    """
    tree = ast.parse(MIGRATION.read_text(encoding="utf-8"))
    docstring = ast.get_docstring(tree, clean=False)
    texts = [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and node.value != docstring
    ]
    flattened = _WHITESPACE.sub(" ", " ".join(texts)).upper()
    for statement in ("INSERT INTO", "UPDATE KNOWLEDGE", "DELETE FROM", "COPY KNOWLEDGE"):
        assert statement not in flattened, statement
    assert not any(
        isinstance(node, ast.Attribute) and node.attr in {"bulk_insert", "insert", "update"}
        for node in ast.walk(tree)
    )


# ---- offline SQL -------------------------------------------------------------------


def test_the_offline_upgrade_emits_the_tables_trigger_and_vocabulary(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("MY_PA_DATABASE_URL", "postgresql+psycopg://localhost/my_pa")
    rendered = _offline(f"{PREVIOUS}:{REVISION}")
    for name in TABLE_NAMES:
        assert f"CREATE TABLE knowledge.{name} (" in rendered
    assert f"CREATE FUNCTION knowledge.{FUNCTION}()" in rendered
    assert f"CREATE TRIGGER {TRIGGER}" in rendered
    assert "ADD CONSTRAINT capability_is_known CHECK" in rendered
    assert "'project_controls.status', 'record_events.list', 'relationship_memory" in rendered
    assert "'meeting_read', 'record_event_read', 'relationship_memory" in rendered
    assert f"SET version_num='{REVISION}'" in rendered


def test_the_offline_downgrade_refuses_first_and_unwinds_everything(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("MY_PA_DATABASE_URL", "postgresql+psycopg://localhost/my_pa")
    rendered = _offline(f"{REVISION}:{PREVIOUS}", down=True)
    refusal = rendered.index("refusing to downgrade")
    for name in TABLE_NAMES:
        assert rendered.index(f"DROP TABLE knowledge.{name} RESTRICT") > refusal
    assert f"DROP TRIGGER {TRIGGER}" in rendered
    assert f"DROP FUNCTION knowledge.{FUNCTION}()" in rendered
    restated = rendered.split("ADD CONSTRAINT capability_is_known CHECK")[1]
    assert "'record_events.list'" not in restated.split("ADD CONSTRAINT")[0]
    assert f"SET version_num='{PREVIOUS}'" in rendered


# ---- disposable databases -------------------------------------------------------------


@pytest.fixture
def disposable_database(empty_database_url: str) -> str:
    """An empty catalog: this module drives Alembic itself."""
    return empty_database_url


@pytest.fixture
def engine(disposable_database: str) -> Iterator[Engine]:
    built = create_database_engine(disposable_database)
    try:
        yield built
    finally:
        built.dispose()


def _tables(engine: Engine) -> set[str]:
    with engine.connect() as connection:
        return set(
            connection.execute(
                text("SELECT tablename FROM pg_tables WHERE schemaname = :schema"),
                {"schema": SCHEMA},
            ).scalars()
        )


def _version(engine: Engine) -> str:
    with engine.connect() as connection:
        return str(connection.execute(text("SELECT version_num FROM alembic_version")).scalar_one())


def _admitted(engine: Engine, constraint: str) -> frozenset[str]:
    with engine.connect() as connection:
        definition = connection.execute(
            text(
                "SELECT pg_get_constraintdef(c.oid) FROM pg_constraint c "
                "JOIN pg_class t ON t.oid = c.conrelid "
                "JOIN pg_namespace n ON n.oid = t.relnamespace "
                "WHERE n.nspname = :schema AND t.relname = 'audit_events' AND c.conname = :name"
            ),
            {"schema": SCHEMA, "name": constraint},
        ).scalar_one()
    return frozenset(re.findall(r"'([^']+)'::text", str(definition)))


def _feed_row(connection: Connection) -> None:
    connection.execute(
        insert(record_events).values(
            event_id="rcev_rcevmig0001event01",
            principal_id=PRINCIPAL,
            sequence_number=1,
            record_family="task",
            record_id="task_rcevmig0001task01",
            event_kind="created",
            record_version=1,
            changed_fields=["title"],
            source_capability="tasks.create",
            actor_class="principal",
            classification="private_local",
            occurred_at=WHEN,
        )
    )


def _counts(engine: Engine) -> tuple[int, int]:
    with engine.connect() as connection:
        return (
            int(
                connection.execute(
                    text("SELECT count(*) FROM knowledge.record_events")
                ).scalar_one()
            ),
            int(
                connection.execute(
                    text("SELECT count(*) FROM knowledge.record_event_sequences")
                ).scalar_one()
            ),
        )


@pytest.mark.database
@pytest.mark.migration_empty_to_head
def test_an_empty_database_upgrades_to_the_record_events_head(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), REVISION)
    assert _version(engine) == REVISION
    assert _tables(engine) >= TABLE_NAMES
    with engine.begin() as connection:
        _feed_row(connection)
        _audit(
            connection,
            capability="record_events.list",
            purpose="record_event_read",
            suffix="rcevmig0001x",
        )
    assert _counts(engine) == (1, 0)


@pytest.mark.database
def test_the_previous_head_with_canonical_rows_upgrades_to_the_record_events_head(
    disposable_database: str, engine: Engine
) -> None:
    """RE-AC-078 and 083: existing rows survive and the feed starts empty."""
    del disposable_database
    command.upgrade(_config(), PREVIOUS)
    with engine.begin() as connection:
        _seed_meeting(connection)
        _audit(
            connection, capability="meetings.list", purpose="meeting_read", suffix="rcevmig0002x"
        )
    command.upgrade(_config(), REVISION)
    assert _version(engine) == REVISION
    assert _counts(engine) == (0, 0)
    with engine.connect() as connection:
        meetings_kept = connection.execute(text("SELECT count(*) FROM knowledge.meetings"))
        audit_kept = connection.execute(
            text("SELECT count(*) FROM knowledge.audit_events WHERE capability = 'meetings.list'")
        )
        assert (meetings_kept.scalar_one(), audit_kept.scalar_one()) == (1, 1)


@pytest.mark.database
def test_head_admits_record_events_list_and_record_event_read(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    assert "record_events.list" in _admitted(engine, "capability_is_known")
    assert "record_event_read" in _admitted(engine, "purpose_is_known")
    with engine.begin() as connection:
        _audit(
            connection,
            capability="record_events.list",
            purpose="record_event_read",
            suffix="rcevmig0003x",
        )


@pytest.mark.database
def test_a_downgrade_refuses_while_a_record_event_exists(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), REVISION)
    with engine.begin() as connection:
        _feed_row(connection)
    with pytest.raises(DBAPIError) as refused:
        command.downgrade(_config(), PREVIOUS)
    assert getattr(refused.value.orig, "sqlstate", None) == RESTRICT_VIOLATION
    assert _version(engine) == REVISION
    assert _counts(engine) == (1, 0)


@pytest.mark.database
def test_a_downgrade_refuses_while_a_sequence_row_exists(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), REVISION)
    with engine.begin() as connection:
        connection.execute(
            insert(record_event_sequences).values(principal_id=PRINCIPAL, next_sequence=1)
        )
    with pytest.raises(DBAPIError) as refused:
        command.downgrade(_config(), PREVIOUS)
    assert getattr(refused.value.orig, "sqlstate", None) == RESTRICT_VIOLATION
    assert _version(engine) == REVISION


@pytest.mark.database
def test_a_downgrade_refuses_while_an_audit_event_names_the_record_event_vocabulary(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), REVISION)
    with engine.begin() as connection:
        _audit(
            connection,
            capability="capture.list",
            purpose="record_event_read",
            suffix="rcevmig0004x",
        )
    with pytest.raises(DBAPIError) as refused:
        command.downgrade(_config(), PREVIOUS)
    assert getattr(refused.value.orig, "sqlstate", None) == RESTRICT_VIOLATION
    assert _version(engine) == REVISION


@pytest.mark.database
def test_an_empty_downgrade_restores_the_meeting_head_vocabulary_and_drops_everything(
    disposable_database: str, engine: Engine
) -> None:
    del disposable_database
    command.upgrade(_config(), "head")
    command.downgrade(_config(), PREVIOUS)
    assert _version(engine) == PREVIOUS
    assert not _tables(engine) & TABLE_NAMES
    previous = VOCABULARY_MIGRATION.read_text(encoding="utf-8")
    assert _admitted(engine, "capability_is_known") == frozenset(
        _literals(_constant(previous, "_CAPABILITIES_AT_THIS_REVISION"))
    )
    assert _admitted(engine, "purpose_is_known") == frozenset(
        _literals(_constant(previous, "_PURPOSES_AT_THIS_REVISION"))
    )
    with engine.connect() as connection:
        functions = set(
            connection.execute(
                text(
                    "SELECT p.proname FROM pg_proc p "
                    "JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = :schema"
                ),
                {"schema": SCHEMA},
            ).scalars()
        )
    assert FUNCTION not in functions
    command.upgrade(_config(), REVISION)
    assert _version(engine) == REVISION
