"""create target tables

Creates the 484 tables the disposition registry marks for creation, in the
domain schema each one belongs to. Every table carries its source columns with
their mapped types, its primary key, its ported CHECK constraints, and the
provenance columns that let a row name the run and the source object it came
from.

Foreign keys and indexes are deliberately *not* here. SQLite never enforced its
declared foreign keys, so they are added after the rows land and any orphan can
be reported rather than silently blocking the load; and building indexes after a
bulk load is cheaper. Both arrive in the two revisions that follow, which means
the loader can stop at this revision, load, and then continue to head.

Two things the load has to honour, stated here because this is the revision it
stops at:

* 46 tables have a `bigint GENERATED BY DEFAULT AS IDENTITY` key -- those that
  declared `AUTOINCREMENT` and those whose single-column `INTEGER PRIMARY KEY`
  SQLite auto-assigned as a rowid alias without declaring it. `BY DEFAULT` lets
  the load insert the source's own key values, which leaves each sequence behind
  the data, so **every one of them must be reset to `max(key) + 1` once its
  table has loaded** or the next application insert collides.
* SQLite permits NULL in a non-`INTEGER` PRIMARY KEY and 510 source tables are
  keyed on TEXT, so a NULL key is possible in the data. PostgreSQL rejects it.
  Quarantine that row, count it, and name the table and column in the
  reconciliation report. Do not fabricate a key, substitute an empty string, or
  drop the primary key to make the load pass.

The statements live in `migrations/sql/target_tables.*.sql`, regenerated by
`scripts/migration/generate_target_schema.py` from the source profile.

Revision ID: 1e6c0a94f3b7
Revises: 5d75f23847c9
Created: 2026-08-01 10:08:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from alembic import op

from my_pa.infrastructure.migration.sql_files import read_statements

revision: str = "1e6c0a94f3b7"
down_revision: str | None = "5d75f23847c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SQL_DIR = Path(__file__).resolve().parents[1] / "sql"


def upgrade() -> None:
    for statement in read_statements(SQL_DIR / "target_tables.up.sql"):
        op.execute(statement)


def downgrade() -> None:
    for statement in read_statements(SQL_DIR / "target_tables.down.sql"):
        op.execute(statement)
