"""Admit the Capture root lifecycle: two append-only tables and the jobs overlay.

Revision ID: 0641c354ca85
Revises: 1d9b248e7f83
Create Date: 2026-10-01

CRL-WP-03, the single Capture lifecycle revision (archive / restore;
`docs/specs/capture-withdrawal-v0.1.md`). Generated by `alembic revision`
against the sole head `1d9b248e7f83`, authenticated immediately before
generation; no identifier was preassigned and no merge revision exists. If main
advances before merge, `down_revision` is re-pointed to the then-sole head.

It:

1. adds `UNIQUE (capture_id, owner_principal_id)` to `knowledge.captures` by
   ALTER -- the target of the two same-owner foreign keys below. It is not
   declared on the frozen `captures` declaration, which historical revision
   `1a4c9e77b2d5` builds from;
2. creates `knowledge.capture_lifecycle_events`, with contiguity, alternation
   (odd revisions archive, even ones restore, from active/0) and same-root,
   same-owner predecessor linkage declared as constraints;
3. creates `knowledge.capture_lifecycle_receipts`, one per Principal and
   idempotency key, with honest-outcome constraints and a reference to an event
   of the same root, revision and operation;
4. creates one append-only function and trigger per new table;
5. adds `lease_generation` and `pause_cause` to `knowledge.capture_jobs` by
   ALTER (MR-C05). They are not declared on the live `capture_jobs`
   declaration, because `1a4c9e77b2d5` creates that table from it.

All DDL is frozen text: no package import, no live declaration, no enum. Every
new foreign key is `ON DELETE RESTRICT NOT DEFERRABLE`.

No backfill: this revision writes no row. Existing roots are active at
lifecycle revision 0 by the absence of events; existing jobs take generation 0
and no pause. `downgrade` refuses, deleting nothing, while any lifecycle event,
any lifecycle receipt or any paused capture job exists; otherwise it removes the
jobs overlay, the triggers, the two tables (`RESTRICT`) and the `captures`
uniqueness, in that order.

The capability vocabulary for `capture.archive` / `capture.restore` is not
restated here yet; that lands in this same revision at CP-CRL-07.

Applying this revision to a persistent, shared or production database requires
separate operator authority; nothing here grants it.
"""

from __future__ import annotations

from typing import Final

from alembic import op

revision: str = "0641c354ca85"
down_revision: str | None = "1d9b248e7f83"
branch_labels: str | None = None
depends_on: str | None = None

SCHEMA: Final = "knowledge"

#: The root uniqueness the same-owner foreign keys reference. Database-only.
_CAPTURE_ROOT_UNIQUE: Final = "a_capture_is_identified_within_its_principal"

#: `(table, CREATE TABLE ...)`, in dependency order. Frozen text: a later edit to
#: `tables.py` must never change what this revision emits.
_TABLE_DDL: Final[tuple[tuple[str, str], ...]] = (
    (
        "capture_lifecycle_events",
        """
        CREATE TABLE knowledge.capture_lifecycle_events (
          event_id TEXT NOT NULL,
          owner_principal_id TEXT NOT NULL,
          capture_id TEXT NOT NULL,
          lifecycle_revision INTEGER NOT NULL,
          operation TEXT NOT NULL,
          resulting_state TEXT NOT NULL,
          predecessor_event_id TEXT,
          predecessor_revision INTEGER,
          transitioned_at TIMESTAMP WITH TIME ZONE NOT NULL,
          intent_digest TEXT NOT NULL,
          correlation_id TEXT NOT NULL,
          audit_id TEXT NOT NULL,
          reason_category TEXT NOT NULL,
          PRIMARY KEY (event_id),
          CONSTRAINT event_id_is_an_opaque_identifier CHECK (event_id ~
              '^clev_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT owner_principal_id_is_an_opaque_identifier CHECK (owner_principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT capture_id_is_an_opaque_identifier CHECK (capture_id ~
              '^cap_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT predecessor_event_id_is_an_opaque_identifier CHECK (predecessor_event_id ~
              '^clev_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT correlation_id_is_an_opaque_identifier CHECK (correlation_id ~
              '^corr_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT audit_id_is_an_opaque_identifier CHECK (audit_id ~
              '^audit_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_capture_lifecycle_operation_is_known CHECK (operation IN ('archive',
              'restore')),
          CONSTRAINT a_capture_lifecycle_state_is_known CHECK (resulting_state IN ('active',
              'archived')),
          CONSTRAINT a_capture_lifecycle_reason_category_is_known CHECK (reason_category IN
              ('owner_stated')),
          CONSTRAINT a_capture_lifecycle_intent_is_a_digest CHECK (intent_digest ~
              '^[0-9a-f]{64}$'),
          CONSTRAINT a_capture_lifecycle_revision_is_positive CHECK (lifecycle_revision >= 1),
          CONSTRAINT a_capture_lifecycle_predecessor_is_whole CHECK ((predecessor_event_id
              IS NULL) = (predecessor_revision IS NULL)),
          CONSTRAINT only_the_first_capture_lifecycle_event_has_no_predecessor CHECK
              ((lifecycle_revision = 1) = (predecessor_event_id IS NULL)),
          CONSTRAINT a_capture_lifecycle_predecessor_is_the_prior_revision CHECK
              (predecessor_revision IS NULL OR predecessor_revision = lifecycle_revision - 1),
          CONSTRAINT odd_capture_lifecycle_revisions_archive CHECK ((lifecycle_revision % 2 = 1)
              = (operation = 'archive')),
          CONSTRAINT a_capture_archive_results_in_archived CHECK ((operation = 'archive') =
              (resulting_state = 'archived')),
          CONSTRAINT one_capture_lifecycle_event_per_revision UNIQUE (owner_principal_id,
              capture_id, lifecycle_revision),
          CONSTRAINT a_capture_lifecycle_event_is_identified_within_its_root UNIQUE (event_id,
              owner_principal_id, capture_id, lifecycle_revision),
          CONSTRAINT a_capture_lifecycle_event_is_identified_with_its_operation UNIQUE
              (event_id, owner_principal_id, capture_id, lifecycle_revision, operation),
          CONSTRAINT a_capture_lifecycle_predecessor_is_an_event_of_its_root FOREIGN
              KEY(predecessor_event_id, owner_principal_id, capture_id, predecessor_revision)
              REFERENCES knowledge.capture_lifecycle_events (event_id, owner_principal_id,
              capture_id, lifecycle_revision) ON DELETE RESTRICT NOT DEFERRABLE,
          CONSTRAINT a_capture_lifecycle_event_names_a_capture_of_its_owner FOREIGN
              KEY(capture_id, owner_principal_id) REFERENCES knowledge.captures (capture_id,
              owner_principal_id) ON DELETE RESTRICT NOT DEFERRABLE
        )
        """,
    ),
    (
        "capture_lifecycle_receipts",
        """
        CREATE TABLE knowledge.capture_lifecycle_receipts (
          receipt_id TEXT NOT NULL,
          owner_principal_id TEXT NOT NULL,
          idempotency_key TEXT NOT NULL,
          capture_id TEXT NOT NULL,
          operation TEXT NOT NULL,
          intent_digest TEXT NOT NULL,
          expected_lifecycle_revision INTEGER NOT NULL,
          resulting_lifecycle_revision INTEGER NOT NULL,
          outcome TEXT NOT NULL,
          event_id TEXT,
          issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
          correlation_id TEXT NOT NULL,
          audit_id TEXT NOT NULL,
          PRIMARY KEY (receipt_id),
          CONSTRAINT receipt_id_is_an_opaque_identifier CHECK (receipt_id ~
              '^clrcpt_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT owner_principal_id_is_an_opaque_identifier CHECK (owner_principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT capture_id_is_an_opaque_identifier CHECK (capture_id ~
              '^cap_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT event_id_is_an_opaque_identifier CHECK (event_id ~
              '^clev_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT correlation_id_is_an_opaque_identifier CHECK (correlation_id ~
              '^corr_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT audit_id_is_an_opaque_identifier CHECK (audit_id ~
              '^audit_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_capture_lifecycle_receipt_operation_is_known CHECK (operation IN
              ('archive', 'restore')),
          CONSTRAINT a_capture_lifecycle_outcome_is_known CHECK (outcome IN ('applied',
              'no_op')),
          CONSTRAINT a_capture_lifecycle_receipt_intent_is_a_digest CHECK (intent_digest ~
              '^[0-9a-f]{64}$'),
          CONSTRAINT a_capture_lifecycle_receipt_records_a_bounded_key CHECK
              (length(idempotency_key) BETWEEN 1 AND 128),
          CONSTRAINT capture_lifecycle_receipt_revisions_are_not_negative CHECK
              (expected_lifecycle_revision >= 0 AND resulting_lifecycle_revision >= 0),
          CONSTRAINT an_applied_capture_lifecycle_receipt_moves_the_revision_by_one CHECK
              ((outcome = 'applied') = (resulting_lifecycle_revision =
              expected_lifecycle_revision + 1)),
          CONSTRAINT a_no_op_capture_lifecycle_receipt_moves_nothing CHECK (outcome <> 'no_op'
              OR resulting_lifecycle_revision = expected_lifecycle_revision),
          CONSTRAINT an_applied_capture_lifecycle_receipt_names_its_event CHECK (outcome <>
              'applied' OR event_id IS NOT NULL),
          CONSTRAINT a_no_op_capture_lifecycle_receipt_names_the_latest_event CHECK (outcome
              <> 'no_op' OR ((expected_lifecycle_revision = 0) = (event_id IS NULL))),
          CONSTRAINT a_capture_lifecycle_key_admits_one_request_per_principal UNIQUE
              (owner_principal_id, idempotency_key),
          CONSTRAINT a_capture_lifecycle_receipt_names_a_capture_of_its_owner FOREIGN
              KEY(capture_id, owner_principal_id) REFERENCES knowledge.captures (capture_id,
              owner_principal_id) ON DELETE RESTRICT NOT DEFERRABLE,
          CONSTRAINT a_capture_lifecycle_receipt_names_its_root_event FOREIGN KEY(event_id,
              owner_principal_id, capture_id, resulting_lifecycle_revision, operation)
              REFERENCES knowledge.capture_lifecycle_events (event_id, owner_principal_id,
              capture_id, lifecycle_revision, operation) ON DELETE RESTRICT NOT DEFERRABLE
        )
        """,
    ),
)

#: The two immutable ledgers: `(function, trigger, table)`.
_APPEND_ONLY: Final[tuple[tuple[str, str, str], ...]] = (
    (
        "capture_lifecycle_events_stay_append_only",
        "capture_lifecycle_events_are_append_only",
        "capture_lifecycle_events",
    ),
    (
        "capture_lifecycle_receipts_stay_append_only",
        "capture_lifecycle_receipts_are_append_only",
        "capture_lifecycle_receipts",
    ),
)

#: The jobs overlay (plan (e.3), MR-C05). A paused row is always queued: never
#: running, never terminal. Existing rows take generation 0 and no pause.
_JOBS_OVERLAY: Final = """
    ALTER TABLE knowledge.capture_jobs
      ADD COLUMN lease_generation BIGINT DEFAULT 0 NOT NULL,
      ADD COLUMN pause_cause TEXT,
      ADD CONSTRAINT a_capture_job_lease_generation_is_not_negative CHECK
          (lease_generation >= 0),
      ADD CONSTRAINT a_capture_job_pause_cause_is_known CHECK (pause_cause IS NULL OR
          pause_cause IN ('capture_withdrawn', 'current_policy_ineligible')),
      ADD CONSTRAINT only_a_queued_capture_job_is_paused CHECK (pause_cause IS NULL OR
          state = 'queued')
    """

_DROP_JOBS_OVERLAY: Final = """
    ALTER TABLE knowledge.capture_jobs
      DROP CONSTRAINT only_a_queued_capture_job_is_paused,
      DROP CONSTRAINT a_capture_job_pause_cause_is_known,
      DROP CONSTRAINT a_capture_job_lease_generation_is_not_negative,
      DROP COLUMN pause_cause,
      DROP COLUMN lease_generation
    """

#: `downgrade` refuses while either lifecycle table holds a row, or while any
#: capture job is paused, rather than deleting user data to make it pass.
_REFUSE_DOWNGRADE: Final = """
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM knowledge.capture_lifecycle_events)
         OR EXISTS (SELECT 1 FROM knowledge.capture_lifecycle_receipts)
         OR EXISTS (SELECT 1 FROM knowledge.capture_jobs WHERE pause_cause IS NOT NULL)
      THEN
        RAISE EXCEPTION 'capture lifecycle state exists; refusing to downgrade 0641c354ca85'
          USING ERRCODE = 'restrict_violation';
      END IF;
    END $$
    """


def upgrade() -> None:
    op.execute(
        f"ALTER TABLE {SCHEMA}.captures ADD CONSTRAINT {_CAPTURE_ROOT_UNIQUE} "
        "UNIQUE (capture_id, owner_principal_id)"
    )
    for _table, ddl in _TABLE_DDL:
        op.execute(ddl)
    for function, trigger, table in _APPEND_ONLY:
        op.execute(
            f"""
            CREATE FUNCTION {SCHEMA}.{function}() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
              RAISE EXCEPTION '{table} is append-only'
                USING ERRCODE = 'restrict_violation';
            END; $$;
            CREATE TRIGGER {trigger}
              BEFORE UPDATE OR DELETE ON {SCHEMA}.{table}
              FOR EACH ROW EXECUTE FUNCTION {SCHEMA}.{function}()
            """
        )
    op.execute(_JOBS_OVERLAY)


def downgrade() -> None:
    op.execute(_REFUSE_DOWNGRADE)
    op.execute(_DROP_JOBS_OVERLAY)
    for function, trigger, table in reversed(_APPEND_ONLY):
        op.execute(f"DROP TRIGGER {trigger} ON {SCHEMA}.{table}")
        op.execute(f"DROP FUNCTION {SCHEMA}.{function}()")
    for table, _ddl in reversed(_TABLE_DDL):
        op.execute(f"DROP TABLE {SCHEMA}.{table} RESTRICT")
    op.execute(f"ALTER TABLE {SCHEMA}.captures DROP CONSTRAINT {_CAPTURE_ROOT_UNIQUE}")
