"""Admit Meeting records: eight tables, four triggers, frozen audit vocabulary.

Revision ID: 7d9a450dfd07
Revises: 6f6ead27d122
Create Date: 2026-09-27

WP-MTG-04, the single Meeting records revision (package sections 34.21 and
35.12; plan section 9). Generated by `alembic revision` against the sole head
`6f6ead27d122` authenticated immediately before generation; no identifier was
preassigned and no merge revision exists.

In foreign-key dependency order it:

1. adds `a_managed_document_is_identified_within_its_owner UNIQUE (document_id,
   owner_principal_id)` on `knowledge.managed_documents`, **unconditionally**
   (operator ruling WP02 F-01): `4c7b2e91d8a5` freezes it out of its
   revision-local copy, so no earlier revision creates it and this one always
   does. `document_id` is already the primary key, so it admits no identity the
   table did not already admit; it exists so a Meeting attachment's composite
   `(document_id, principal_id)` reference can only name a document its own
   Principal owns;
2. creates the eight Meeting tables with every key, check, composite
   same-Principal reference and index `tables.py` declares, as frozen DDL text
   (never the live `Table` objects, never an enum);
3. creates the three append-only triggers and the one complete-once transition
   trigger, each over its own named function (the repository's per-table
   PL/pgSQL pattern);
4. restates `capability_is_known` and `purpose_is_known` on
   `knowledge.audit_events` with frozen literals: the BEFORE sets are byte
   copies of `e6a4c2f91b73`'s AT sets -- the most recent revision in the chain
   that restates them (`6f6ead27d122` does not) -- and the AT sets are those plus
   exactly the six `meetings.*` names and the two `meeting_*` purposes.

No backfill. `downgrade` refuses, deleting nothing, while any Meeting row exists
or any audit event names a Meeting capability or purpose; otherwise it restores
the BEFORE vocabulary, drops the triggers, functions and tables in reverse order,
and drops the `managed_documents` unique this revision created.

Applying this revision to a persistent, shared or production database requires
separate operator authority; nothing here grants it.
"""

from __future__ import annotations

from typing import Final

from alembic import op

revision: str = "7d9a450dfd07"
down_revision: str | None = "6f6ead27d122"
branch_labels: str | None = None
depends_on: str | None = None

SCHEMA: Final = "knowledge"

#: Frozen byte copy of `e6a4c2f91b73`'s AT capability vocabulary (183 names).
_CAPABILITIES_BEFORE_THIS_REVISION: Final = (
    "capability IN ('canvas.workspace.get', 'canvas.workspace.put', 'capabilities.get', "
    "'capture.create', 'capture.list', 'capture.read', 'capture.revise', 'capture.search', "
    "'commitments.close', 'commitments.create', 'commitments.history', 'commitments.list', "
    "'commitments.read', 'commitments.search', 'commitments.update', 'commitments.waiting_on', "
    "'constraint_categories.create', 'constraint_categories.deactivate', "
    "'constraint_categories.list', 'constraint_categories.reorder', "
    "'constraint_categories.update', 'constraint_sync.acknowledge', 'constraint_sync.apply', "
    "'constraint_sync.conflicts', 'constraint_sync.delta', 'constraint_sync.preview', "
    "'constraint_sync.resolve', 'constraint_sync.state', 'constraints.close', "
    "'constraints.close_follow_up', 'constraints.create', 'constraints.create_published', "
    "'constraints.history', 'constraints.list', 'constraints.overview', "
    "'constraints.portfolio_list', 'constraints.portfolio_overview', "
    "'constraints.portfolio_search', 'constraints.publish', 'constraints.read', "
    "'constraints.reopen', 'constraints.search', 'constraints.transition', 'constraints.update', "
    "'constraints.void', 'context.feedback', 'context.prepare', 'continuity.projects', "
    "'continuity.projects.close', 'continuity.projects.create', "
    "'continuity.projects.read', 'continuity.projects.update', 'continuity.pulse', "
    "'continuity.situations', "
    "'continuity.situations.create', 'continuity.tasks.create', 'documents.archive', "
    "'documents.create', 'documents.list', 'documents.read', 'documents.restore', "
    "'documents.revise', 'entities.addresses.add', 'entities.addresses.list', "
    "'entities.addresses.retire', 'entities.addresses.revise', 'entities.affiliations.create', "
    "'entities.affiliations.end', 'entities.affiliations.revise', 'entities.aliases.add', "
    "'entities.aliases.list', 'entities.aliases.retire', 'entities.aliases.supersede', "
    "'entities.archive', 'entities.assignments.create', 'entities.assignments.end', "
    "'entities.assignments.list', 'entities.assignments.revise', 'entities.communication.add', "
    "'entities.communication.list', 'entities.communication.retire', "
    "'entities.communication.revise', 'entities.context', 'entities.create', 'entities.get', "
    "'entities.graph', 'entities.identifiers.bind', 'entities.identifiers.list', "
    "'entities.identifiers.retire', 'entities.identifiers.supersede', 'entities.identity_history', "
    "'entities.merge', 'entities.merge.preview', 'entities.names.add', 'entities.names.list', "
    "'entities.names.retire', 'entities.names.supersede', 'entities.observations.list', "
    "'entities.observe', 'entities.participations.create', 'entities.participations.end', "
    "'entities.participations.list', 'entities.participations.revise', 'entities.profile', "
    "'entities.proposals.create', 'entities.relationships', 'entities.relationships.create', "
    "'entities.relationships.end', 'entities.relationships.revise', 'entities.resolve', "
    "'entities.restore', 'entities.search', 'entities.split', 'entities.split.preview', "
    "'entities.unresolved_mentions', 'entities.unresolved_mentions.resolve', 'entities.update', "
    "'goodnotes.complete', 'goodnotes.content', 'goodnotes.correct', 'goodnotes.notebooks.list', "
    "'goodnotes.pages.list', 'goodnotes.propose', 'goodnotes.pull', 'goodnotes.read', "
    "'goodnotes.runs.list', 'goodnotes.search', 'goodnotes.status', 'goodnotes.work', "
    "'gsqs.start', 'gsqs.status', 'knowledge.coverage', 'knowledge.read', 'knowledge.reveal', "
    "'knowledge.search', 'native_sources.backfill', 'native_sources.configure', "
    "'native_sources.disable', 'native_sources.discover', 'native_sources.pause', "
    "'native_sources.preflight', 'native_sources.reconcile', 'native_sources.resume', "
    "'native_sources.retry', 'native_sources.status', 'native_sources.sync', "
    "'project_controls.configure', 'project_controls.status', "
    "'relationship_memory.archive', 'relationship_memory.create', 'relationship_memory.get', "
    "'relationship_memory.history', 'relationship_memory.list', 'relationship_memory.propose', "
    "'relationship_memory.restore', 'relationship_memory.revise', 'relationship_memory.search', "
    "'reports.begin_cycle', 'reports.commit', 'reports.latest', 'reports.list', 'reports.read', "
    "'reports.record_run_state', 'reports.resolve_set', 'reports.search', 'review.decide', "
    "'review.list', 'sources.enroll', 'sources.fetch', 'sources.list', 'sources.metadata', "
    "'sources.status', 'tasks.bulk_confirm', 'tasks.bulk_preview', 'tasks.comments.create', "
    "'tasks.comments.list', 'tasks.create', 'tasks.history', 'tasks.list', 'tasks.read', "
    "'tasks.search', 'tasks.transition', 'tasks.update')"
)
#: Frozen byte copy of `e6a4c2f91b73`'s AT purpose vocabulary (45 names).
_PURPOSES_BEFORE_THIS_REVISION: Final = (
    "purpose IN ('bounded_enrollment', 'canvas_workspace_authoring', 'canvas_workspace_read', "
    "'capture_authoring', 'capture_review', 'commitment_authoring', 'commitment_read', "
    "'constraint_authoring', 'constraint_read', 'constraint_sync_authoring', "
    "'constraint_sync_read', 'content_extraction', 'context_preference', 'context_preparation', "
    "'continuity_authoring', 'document_authoring', 'document_read', 'entity_authoring', "
    "'entity_identity_correction', 'entity_observation_ingest', 'entity_proposal', 'entity_read', "
    "'goodnotes_browse', 'goodnotes_content', 'goodnotes_correction', 'goodnotes_proposal', "
    "'goodnotes_pull', 'goodnotes_pull_observation', 'goodnotes_read', 'goodnotes_work', "
    "'gsqs_b0_execution', 'gsqs_b0_observation', 'knowledge_read', 'knowledge_search', "
    "'relationship_memory_authoring', 'relationship_memory_proposal', 'relationship_memory_read', "
    "'report_authoring', 'report_read', 'review_disposition', 'security_validation', "
    "'source_inspection', 'status_observation', 'task_authoring', 'task_read')"
)
#: The same set plus exactly the six Meeting records names (189 names).
_CAPABILITIES_AT_THIS_REVISION: Final = (
    "capability IN ('canvas.workspace.get', 'canvas.workspace.put', 'capabilities.get', "
    "'capture.create', 'capture.list', 'capture.read', 'capture.revise', 'capture.search', "
    "'commitments.close', 'commitments.create', 'commitments.history', 'commitments.list', "
    "'commitments.read', 'commitments.search', 'commitments.update', 'commitments.waiting_on', "
    "'constraint_categories.create', 'constraint_categories.deactivate', "
    "'constraint_categories.list', 'constraint_categories.reorder', "
    "'constraint_categories.update', 'constraint_sync.acknowledge', 'constraint_sync.apply', "
    "'constraint_sync.conflicts', 'constraint_sync.delta', 'constraint_sync.preview', "
    "'constraint_sync.resolve', 'constraint_sync.state', 'constraints.close', "
    "'constraints.close_follow_up', 'constraints.create', 'constraints.create_published', "
    "'constraints.history', 'constraints.list', 'constraints.overview', "
    "'constraints.portfolio_list', 'constraints.portfolio_overview', "
    "'constraints.portfolio_search', 'constraints.publish', 'constraints.read', "
    "'constraints.reopen', 'constraints.search', 'constraints.transition', 'constraints.update', "
    "'constraints.void', 'context.feedback', 'context.prepare', 'continuity.projects', "
    "'continuity.projects.close', 'continuity.projects.create', "
    "'continuity.projects.read', 'continuity.projects.update', 'continuity.pulse', "
    "'continuity.situations', "
    "'continuity.situations.create', 'continuity.tasks.create', 'documents.archive', "
    "'documents.create', 'documents.list', 'documents.read', 'documents.restore', "
    "'documents.revise', 'entities.addresses.add', 'entities.addresses.list', "
    "'entities.addresses.retire', 'entities.addresses.revise', 'entities.affiliations.create', "
    "'entities.affiliations.end', 'entities.affiliations.revise', 'entities.aliases.add', "
    "'entities.aliases.list', 'entities.aliases.retire', 'entities.aliases.supersede', "
    "'entities.archive', 'entities.assignments.create', 'entities.assignments.end', "
    "'entities.assignments.list', 'entities.assignments.revise', 'entities.communication.add', "
    "'entities.communication.list', 'entities.communication.retire', "
    "'entities.communication.revise', 'entities.context', 'entities.create', 'entities.get', "
    "'entities.graph', 'entities.identifiers.bind', 'entities.identifiers.list', "
    "'entities.identifiers.retire', 'entities.identifiers.supersede', 'entities.identity_history', "
    "'entities.merge', 'entities.merge.preview', 'entities.names.add', 'entities.names.list', "
    "'entities.names.retire', 'entities.names.supersede', 'entities.observations.list', "
    "'entities.observe', 'entities.participations.create', 'entities.participations.end', "
    "'entities.participations.list', 'entities.participations.revise', 'entities.profile', "
    "'entities.proposals.create', 'entities.relationships', 'entities.relationships.create', "
    "'entities.relationships.end', 'entities.relationships.revise', 'entities.resolve', "
    "'entities.restore', 'entities.search', 'entities.split', 'entities.split.preview', "
    "'entities.unresolved_mentions', 'entities.unresolved_mentions.resolve', 'entities.update', "
    "'goodnotes.complete', 'goodnotes.content', 'goodnotes.correct', 'goodnotes.notebooks.list', "
    "'goodnotes.pages.list', 'goodnotes.propose', 'goodnotes.pull', 'goodnotes.read', "
    "'goodnotes.runs.list', 'goodnotes.search', 'goodnotes.status', 'goodnotes.work', "
    "'gsqs.start', 'gsqs.status', 'knowledge.coverage', 'knowledge.read', 'knowledge.reveal', "
    "'knowledge.search', 'meetings.create', 'meetings.list', 'meetings.read', "
    "'meetings.search', 'meetings.series.update', 'meetings.update', "
    "'native_sources.backfill', 'native_sources.configure', "
    "'native_sources.disable', 'native_sources.discover', 'native_sources.pause', "
    "'native_sources.preflight', 'native_sources.reconcile', 'native_sources.resume', "
    "'native_sources.retry', 'native_sources.status', 'native_sources.sync', "
    "'project_controls.configure', 'project_controls.status', "
    "'relationship_memory.archive', 'relationship_memory.create', 'relationship_memory.get', "
    "'relationship_memory.history', 'relationship_memory.list', 'relationship_memory.propose', "
    "'relationship_memory.restore', 'relationship_memory.revise', 'relationship_memory.search', "
    "'reports.begin_cycle', 'reports.commit', 'reports.latest', 'reports.list', 'reports.read', "
    "'reports.record_run_state', 'reports.resolve_set', 'reports.search', 'review.decide', "
    "'review.list', 'sources.enroll', 'sources.fetch', 'sources.list', 'sources.metadata', "
    "'sources.status', 'tasks.bulk_confirm', 'tasks.bulk_preview', 'tasks.comments.create', "
    "'tasks.comments.list', 'tasks.create', 'tasks.history', 'tasks.list', 'tasks.read', "
    "'tasks.search', 'tasks.transition', 'tasks.update')"
)
#: The same set plus exactly the two Meeting records purposes (47 names).
_PURPOSES_AT_THIS_REVISION: Final = (
    "purpose IN ('bounded_enrollment', 'canvas_workspace_authoring', 'canvas_workspace_read', "
    "'capture_authoring', 'capture_review', 'commitment_authoring', 'commitment_read', "
    "'constraint_authoring', 'constraint_read', 'constraint_sync_authoring', "
    "'constraint_sync_read', 'content_extraction', 'context_preference', 'context_preparation', "
    "'continuity_authoring', 'document_authoring', 'document_read', 'entity_authoring', "
    "'entity_identity_correction', 'entity_observation_ingest', 'entity_proposal', 'entity_read', "
    "'goodnotes_browse', 'goodnotes_content', 'goodnotes_correction', 'goodnotes_proposal', "
    "'goodnotes_pull', 'goodnotes_pull_observation', 'goodnotes_read', 'goodnotes_work', "
    "'gsqs_b0_execution', 'gsqs_b0_observation', 'knowledge_read', 'knowledge_search', "
    "'meeting_authoring', 'meeting_read', "
    "'relationship_memory_authoring', 'relationship_memory_proposal', 'relationship_memory_read', "
    "'report_authoring', 'report_read', 'review_disposition', 'security_validation', "
    "'source_inspection', 'status_observation', 'task_authoring', 'task_read')"
)

#: The eight Meeting tables in foreign-key dependency order, each with its own
#: indexes. Frozen text: a later edit to `tables.py` must never change what this
#: revision emits.
_TABLE_DDL: Final[tuple[tuple[str, str], ...]] = (
    (
        "meeting_series",
        """
        CREATE TABLE knowledge.meeting_series (
          meeting_series_id TEXT NOT NULL,
          principal_id TEXT NOT NULL,
          title TEXT NOT NULL,
          version INTEGER DEFAULT 1 NOT NULL,
          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
          PRIMARY KEY (meeting_series_id),
          CONSTRAINT meeting_series_id_is_an_opaque_identifier CHECK (meeting_series_id ~
              '^mser_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT principal_id_is_an_opaque_identifier CHECK (principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_meeting_series_title_is_bounded CHECK (length(title) BETWEEN 1 AND 200 AND
              length(trim(title)) > 0),
          CONSTRAINT a_meeting_series_version_is_positive CHECK (version >= 1),
          CONSTRAINT a_meeting_series_is_identified_within_its_principal UNIQUE (meeting_series_id,
              principal_id)
        );
        CREATE INDEX meeting_series_by_principal_updated_at ON knowledge.meeting_series
          (principal_id, updated_at DESC, meeting_series_id);
        CREATE INDEX meeting_series_title_text ON knowledge.meeting_series USING gin
          (to_tsvector('simple', coalesce(title, '')))
        """,
    ),
    (
        "meetings",
        """
        CREATE TABLE knowledge.meetings (
          meeting_id TEXT NOT NULL,
          principal_id TEXT NOT NULL,
          meeting_series_id TEXT,
          title TEXT NOT NULL,
          start_at TIMESTAMP WITH TIME ZONE NOT NULL,
          end_at TIMESTAMP WITH TIME ZONE,
          timezone_name TEXT NOT NULL,
          status TEXT DEFAULT 'scheduled' NOT NULL,
          cancelled_at TIMESTAMP WITH TIME ZONE,
          location_text TEXT,
          virtual_meeting_url TEXT,
          description TEXT,
          project_id TEXT,
          version INTEGER DEFAULT 1 NOT NULL,
          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
          PRIMARY KEY (meeting_id),
          CONSTRAINT meeting_id_is_an_opaque_identifier CHECK (meeting_id ~
              '^mtg_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT principal_id_is_an_opaque_identifier CHECK (principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_series_id_is_an_opaque_identifier CHECK (meeting_series_id ~
              '^mser_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT project_id_is_an_opaque_identifier CHECK (project_id ~
              '^prj_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_meeting_title_is_bounded CHECK (length(title) BETWEEN 1 AND 200 AND
              length(trim(title)) > 0),
          CONSTRAINT a_meeting_timezone_name_is_bounded CHECK (length(timezone_name) BETWEEN 1 AND
              64 AND length(trim(timezone_name)) > 0),
          CONSTRAINT a_meeting_status_is_known CHECK (status IN ('cancelled', 'scheduled')),
          CONSTRAINT a_meeting_does_not_end_before_it_starts CHECK (end_at IS NULL OR end_at >=
              start_at),
          CONSTRAINT a_cancelled_meeting_records_when_it_was_cancelled CHECK ((status = 'cancelled')
              = (cancelled_at IS NOT NULL)),
          CONSTRAINT a_meeting_location_is_bounded CHECK (location_text IS NULL OR
              length(location_text) <= 500),
          CONSTRAINT a_meeting_virtual_url_is_bounded CHECK (virtual_meeting_url IS NULL OR
              length(virtual_meeting_url) BETWEEN 1 AND 2048),
          CONSTRAINT a_meeting_description_is_bounded CHECK (description IS NULL OR
              length(description) <= 100000),
          CONSTRAINT a_meeting_version_is_positive CHECK (version >= 1),
          CONSTRAINT a_meeting_is_identified_within_its_principal UNIQUE (meeting_id, principal_id),
          CONSTRAINT a_meeting_belongs_to_a_series_of_its_principal FOREIGN KEY(meeting_series_id,
              principal_id) REFERENCES knowledge.meeting_series (meeting_series_id, principal_id) ON
              DELETE RESTRICT,
          CONSTRAINT a_meeting_names_a_project_of_its_principal FOREIGN KEY(project_id,
              principal_id) REFERENCES knowledge.projects (project_id, principal_id) ON DELETE
              RESTRICT
        );
        CREATE INDEX meetings_by_principal_project_start ON knowledge.meetings (principal_id,
          project_id, start_at, meeting_id);
        CREATE INDEX meetings_by_principal_series_start ON knowledge.meetings (principal_id,
          meeting_series_id, start_at, meeting_id);
        CREATE INDEX meetings_by_principal_start ON knowledge.meetings (principal_id, start_at,
          meeting_id);
        CREATE INDEX meetings_by_principal_status_start ON knowledge.meetings (principal_id, status,
          start_at, meeting_id);
        CREATE INDEX meetings_core_text ON knowledge.meetings USING gin (to_tsvector('simple',
          coalesce(title, '') || ' ' || coalesce(description, '') || ' ' || coalesce(location_text,
          '')))
        """,
    ),
    (
        "meeting_attendees",
        """
        CREATE TABLE knowledge.meeting_attendees (
          attendee_id TEXT NOT NULL,
          principal_id TEXT NOT NULL,
          meeting_id TEXT NOT NULL,
          entity_id TEXT,
          display_name TEXT,
          email_normalized TEXT,
          is_organizer BOOLEAN DEFAULT false NOT NULL,
          response_status TEXT DEFAULT 'unknown' NOT NULL,
          added_at TIMESTAMP WITH TIME ZONE NOT NULL,
          removed_at TIMESTAMP WITH TIME ZONE,
          PRIMARY KEY (attendee_id),
          CONSTRAINT attendee_id_is_an_opaque_identifier CHECK (attendee_id ~
              '^matt_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT principal_id_is_an_opaque_identifier CHECK (principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_id_is_an_opaque_identifier CHECK (meeting_id ~
              '^mtg_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT entity_id_is_an_opaque_identifier CHECK (entity_id ~
              '^ent_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_meeting_attendee_carries_an_identity_signal CHECK (entity_id IS NOT NULL OR
              display_name IS NOT NULL OR email_normalized IS NOT NULL),
          CONSTRAINT a_meeting_attendee_display_name_is_bounded CHECK (display_name IS NULL OR
              length(display_name) BETWEEN 1 AND 200),
          CONSTRAINT a_meeting_attendee_email_is_bounded CHECK (email_normalized IS NULL OR
              length(email_normalized) BETWEEN 1 AND 320),
          CONSTRAINT a_meeting_attendee_response_status_is_known CHECK (response_status IN
              ('accepted', 'declined', 'needs_action', 'tentative', 'unknown')),
          CONSTRAINT a_meeting_attendee_is_not_removed_before_it_is_added CHECK (removed_at IS NULL
              OR removed_at >= added_at),
          CONSTRAINT a_meeting_attendee_belongs_to_a_meeting_of_its_principal FOREIGN
              KEY(meeting_id, principal_id) REFERENCES knowledge.meetings (meeting_id, principal_id)
              ON DELETE RESTRICT,
          CONSTRAINT a_meeting_attendee_names_an_entity_of_its_principal FOREIGN KEY(entity_id,
              principal_id) REFERENCES knowledge.entities (entity_id, principal_id) ON DELETE
              RESTRICT
        );
        CREATE INDEX meeting_attendees_active_by_email ON knowledge.meeting_attendees (principal_id,
          email_normalized, meeting_id) WHERE removed_at IS NULL AND email_normalized IS NOT NULL;
        CREATE INDEX meeting_attendees_active_by_entity ON knowledge.meeting_attendees
          (principal_id, entity_id, meeting_id) WHERE removed_at IS NULL AND entity_id IS NOT NULL;
        CREATE INDEX meeting_attendees_active_by_meeting ON knowledge.meeting_attendees
          (principal_id, meeting_id) WHERE removed_at IS NULL;
        CREATE UNIQUE INDEX meeting_attendees_one_active_email ON knowledge.meeting_attendees
          (principal_id, meeting_id, email_normalized) WHERE removed_at IS NULL AND email_normalized
          IS NOT NULL;
        CREATE UNIQUE INDEX meeting_attendees_one_active_entity ON knowledge.meeting_attendees
          (principal_id, meeting_id, entity_id) WHERE removed_at IS NULL AND entity_id IS NOT NULL;
        CREATE UNIQUE INDEX meeting_attendees_one_active_organizer ON knowledge.meeting_attendees
          (principal_id, meeting_id) WHERE removed_at IS NULL AND is_organizer
        """,
    ),
    (
        "meeting_attachments",
        """
        CREATE TABLE knowledge.meeting_attachments (
          attachment_id TEXT NOT NULL,
          principal_id TEXT NOT NULL,
          meeting_id TEXT NOT NULL,
          document_id TEXT NOT NULL,
          added_at TIMESTAMP WITH TIME ZONE NOT NULL,
          removed_at TIMESTAMP WITH TIME ZONE,
          PRIMARY KEY (attachment_id),
          CONSTRAINT attachment_id_is_an_opaque_identifier CHECK (attachment_id ~
              '^matc_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT principal_id_is_an_opaque_identifier CHECK (principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_id_is_an_opaque_identifier CHECK (meeting_id ~
              '^mtg_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT document_id_is_an_opaque_identifier CHECK (document_id ~
              '^mdoc_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_meeting_attachment_is_not_removed_before_it_is_added CHECK (removed_at IS
              NULL OR removed_at >= added_at),
          CONSTRAINT a_meeting_attachment_belongs_to_a_meeting_of_its_principal FOREIGN
              KEY(meeting_id, principal_id) REFERENCES knowledge.meetings (meeting_id, principal_id)
              ON DELETE RESTRICT,
          CONSTRAINT a_meeting_attachment_names_a_document_of_its_principal FOREIGN KEY(document_id,
              principal_id) REFERENCES knowledge.managed_documents (document_id, owner_principal_id)
              ON DELETE RESTRICT
        );
        CREATE INDEX meeting_attachments_active_by_meeting ON knowledge.meeting_attachments
          (principal_id, meeting_id) WHERE removed_at IS NULL;
        CREATE UNIQUE INDEX meeting_attachments_one_active_document ON knowledge.meeting_attachments
          (principal_id, meeting_id, document_id) WHERE removed_at IS NULL
        """,
    ),
    (
        "meeting_history",
        """
        CREATE TABLE knowledge.meeting_history (
          history_id TEXT NOT NULL,
          principal_id TEXT NOT NULL,
          meeting_id TEXT NOT NULL,
          meeting_series_id TEXT,
          action TEXT NOT NULL,
          actor TEXT NOT NULL,
          outcome TEXT NOT NULL,
          before_version INTEGER NOT NULL,
          after_version INTEGER NOT NULL,
          idempotency_key TEXT NOT NULL,
          request_digest TEXT NOT NULL,
          occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
          recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
          PRIMARY KEY (history_id),
          CONSTRAINT history_id_is_an_opaque_identifier CHECK (history_id ~
              '^mhst_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT principal_id_is_an_opaque_identifier CHECK (principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_id_is_an_opaque_identifier CHECK (meeting_id ~
              '^mtg_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_series_id_is_an_opaque_identifier CHECK (meeting_series_id ~
              '^mser_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_meeting_history_action_is_known CHECK (action IN ('create', 'update')),
          CONSTRAINT a_meeting_history_actor_is_known CHECK (actor IN ('assistant', 'principal',
              'system')),
          CONSTRAINT a_meeting_history_outcome_is_known CHECK (outcome IN ('applied', 'no_op')),
          CONSTRAINT a_meeting_history_before_version_is_non_negative CHECK (before_version >= 0),
          CONSTRAINT a_meeting_history_after_version_is_positive CHECK (after_version >= 1),
          CONSTRAINT a_meeting_history_create_is_version_zero_to_one CHECK (action <> 'create' OR
              (before_version = 0 AND after_version = 1 AND outcome = 'applied')),
          CONSTRAINT a_meeting_history_applied_update_advances_one_version CHECK (action <> 'update'
              OR outcome <> 'applied' OR (before_version >= 1 AND after_version = before_version +
              1)),
          CONSTRAINT a_meeting_history_no_op_changes_no_version CHECK (outcome <> 'no_op' OR (action
              = 'update' AND before_version >= 1 AND after_version = before_version)),
          CONSTRAINT a_meeting_history_key_is_bounded CHECK (length(idempotency_key) BETWEEN 1 AND
              128),
          CONSTRAINT a_meeting_history_digest_is_sha256 CHECK (request_digest ~ '^[0-9a-f]{64}$'),
          CONSTRAINT a_meeting_history_is_identified_within_its_meeting UNIQUE (history_id,
              meeting_id, principal_id),
          CONSTRAINT a_meeting_history_belongs_to_a_meeting_of_its_principal FOREIGN KEY(meeting_id,
              principal_id) REFERENCES knowledge.meetings (meeting_id, principal_id) ON DELETE
              RESTRICT
        );
        CREATE INDEX meeting_history_by_principal_meeting ON knowledge.meeting_history
          (principal_id, meeting_id, recorded_at, history_id)
        """,
    ),
    (
        "meeting_note_versions",
        """
        CREATE TABLE knowledge.meeting_note_versions (
          note_version_id TEXT NOT NULL,
          principal_id TEXT NOT NULL,
          meeting_id TEXT NOT NULL,
          version_number INTEGER NOT NULL,
          supersedes_note_version_id TEXT,
          content_markdown TEXT NOT NULL,
          content_sha256 TEXT NOT NULL,
          meeting_history_id TEXT NOT NULL,
          recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
          PRIMARY KEY (note_version_id),
          CONSTRAINT note_version_id_is_an_opaque_identifier CHECK (note_version_id ~
              '^mnote_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT principal_id_is_an_opaque_identifier CHECK (principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_id_is_an_opaque_identifier CHECK (meeting_id ~
              '^mtg_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT supersedes_note_version_id_is_an_opaque_identifier CHECK
              (supersedes_note_version_id ~ '^mnote_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_history_id_is_an_opaque_identifier CHECK (meeting_history_id ~
              '^mhst_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_meeting_note_version_number_is_positive CHECK (version_number >= 1),
          CONSTRAINT only_the_first_meeting_note_supersedes_nothing CHECK ((version_number = 1) =
              (supersedes_note_version_id IS NULL)),
          CONSTRAINT a_meeting_note_body_is_bounded CHECK (length(content_markdown) BETWEEN 1 AND
              100000),
          CONSTRAINT a_meeting_note_digest_is_sha256 CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
          CONSTRAINT a_meeting_note_is_identified_within_its_meeting UNIQUE (note_version_id,
              meeting_id, principal_id),
          CONSTRAINT one_meeting_note_version_number_per_meeting UNIQUE (meeting_id,
              version_number),
          CONSTRAINT a_meeting_note_version_is_superseded_once UNIQUE (supersedes_note_version_id),
          CONSTRAINT a_meeting_note_belongs_to_a_meeting_of_its_principal FOREIGN KEY(meeting_id,
              principal_id) REFERENCES knowledge.meetings (meeting_id, principal_id) ON DELETE
              RESTRICT,
          CONSTRAINT a_meeting_note_supersedes_a_note_of_its_meeting FOREIGN
              KEY(supersedes_note_version_id, meeting_id, principal_id) REFERENCES
              knowledge.meeting_note_versions (note_version_id, meeting_id, principal_id) ON DELETE
              RESTRICT,
          CONSTRAINT a_meeting_note_names_a_receipt_of_its_meeting FOREIGN KEY(meeting_history_id,
              meeting_id, principal_id) REFERENCES knowledge.meeting_history (history_id,
              meeting_id, principal_id) ON DELETE RESTRICT
        );
        CREATE INDEX meeting_note_versions_by_principal_meeting ON knowledge.meeting_note_versions
          (principal_id, meeting_id, version_number DESC);
        CREATE INDEX meeting_note_versions_text ON knowledge.meeting_note_versions USING gin
          (to_tsvector('simple', content_markdown))
        """,
    ),
    (
        "meeting_series_history",
        """
        CREATE TABLE knowledge.meeting_series_history (
          series_history_id TEXT NOT NULL,
          principal_id TEXT NOT NULL,
          meeting_series_id TEXT NOT NULL,
          action TEXT NOT NULL,
          actor TEXT NOT NULL,
          outcome TEXT NOT NULL,
          before_version INTEGER NOT NULL,
          after_version INTEGER NOT NULL,
          idempotency_key TEXT NOT NULL,
          request_digest TEXT NOT NULL,
          occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
          recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
          PRIMARY KEY (series_history_id),
          CONSTRAINT series_history_id_is_an_opaque_identifier CHECK (series_history_id ~
              '^mshst_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT principal_id_is_an_opaque_identifier CHECK (principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_series_id_is_an_opaque_identifier CHECK (meeting_series_id ~
              '^mser_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_meeting_series_history_action_is_known CHECK (action IN ('create',
              'update')),
          CONSTRAINT a_meeting_series_history_actor_is_known CHECK (actor IN ('assistant',
              'principal', 'system')),
          CONSTRAINT a_meeting_series_history_outcome_is_known CHECK (outcome IN ('applied',
              'no_op')),
          CONSTRAINT a_meeting_series_history_before_version_is_non_negative CHECK (before_version
              >= 0),
          CONSTRAINT a_meeting_series_history_after_version_is_positive CHECK (after_version >= 1),
          CONSTRAINT a_meeting_series_history_create_is_version_zero_to_one CHECK (action <>
              'create' OR (before_version = 0 AND after_version = 1 AND outcome = 'applied')),
          CONSTRAINT a_meeting_series_history_applied_update_advances_one_version CHECK (action <>
              'update' OR outcome <> 'applied' OR (before_version >= 1 AND after_version =
              before_version + 1)),
          CONSTRAINT a_meeting_series_history_no_op_changes_no_version CHECK (outcome <> 'no_op' OR
              (action = 'update' AND before_version >= 1 AND after_version = before_version)),
          CONSTRAINT a_meeting_series_history_key_is_bounded CHECK (length(idempotency_key) BETWEEN
              1 AND 128),
          CONSTRAINT a_meeting_series_history_digest_is_sha256 CHECK (request_digest ~
              '^[0-9a-f]{64}$'),
          CONSTRAINT a_meeting_series_history_is_identified_within_its_series UNIQUE
              (series_history_id, meeting_series_id, principal_id),
          CONSTRAINT a_meeting_series_history_belongs_to_a_series_of_its_principal FOREIGN
              KEY(meeting_series_id, principal_id) REFERENCES knowledge.meeting_series
              (meeting_series_id, principal_id) ON DELETE RESTRICT
        );
        CREATE INDEX meeting_series_history_by_principal_series ON knowledge.meeting_series_history
          (principal_id, meeting_series_id, recorded_at, series_history_id)
        """,
    ),
    (
        "meeting_write_requests",
        """
        CREATE TABLE knowledge.meeting_write_requests (
          principal_id TEXT NOT NULL,
          capability TEXT NOT NULL,
          idempotency_key TEXT NOT NULL,
          request_digest TEXT NOT NULL,
          meeting_id TEXT,
          meeting_series_id TEXT,
          meeting_history_id TEXT,
          meeting_series_history_id TEXT,
          result_version INTEGER,
          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
          completed_at TIMESTAMP WITH TIME ZONE,
          CONSTRAINT meeting_write_requests_pkey PRIMARY KEY (principal_id, capability,
              idempotency_key),
          CONSTRAINT principal_id_is_an_opaque_identifier CHECK (principal_id ~
              '^prn_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_id_is_an_opaque_identifier CHECK (meeting_id ~
              '^mtg_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_series_id_is_an_opaque_identifier CHECK (meeting_series_id ~
              '^mser_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_history_id_is_an_opaque_identifier CHECK (meeting_history_id ~
              '^mhst_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT meeting_series_history_id_is_an_opaque_identifier CHECK
              (meeting_series_history_id ~ '^mshst_[A-Za-z0-9]{8,64}$'),
          CONSTRAINT a_meeting_write_request_capability_is_known CHECK (capability IN
              ('meetings.create', 'meetings.series.update', 'meetings.update')),
          CONSTRAINT a_meeting_write_request_key_is_bounded CHECK (length(idempotency_key) BETWEEN 1
              AND 128),
          CONSTRAINT a_meeting_write_request_digest_is_sha256 CHECK (request_digest ~
              '^[0-9a-f]{64}$'),
          CONSTRAINT a_meeting_write_request_result_version_is_positive CHECK (result_version IS
              NULL OR result_version >= 1),
          CONSTRAINT an_incomplete_meeting_write_request_names_no_result CHECK (completed_at IS NOT
              NULL OR (meeting_id IS NULL AND meeting_series_id IS NULL AND meeting_history_id IS
              NULL AND meeting_series_history_id IS NULL AND result_version IS NULL)),
          CONSTRAINT a_completed_meeting_create_names_its_result CHECK (completed_at IS NULL OR
              capability <> 'meetings.create' OR (meeting_id IS NOT NULL AND meeting_history_id IS
              NOT NULL AND result_version IS NOT NULL)),
          CONSTRAINT a_completed_meeting_update_names_its_result CHECK (completed_at IS NULL OR
              capability <> 'meetings.update' OR (meeting_id IS NOT NULL AND meeting_history_id IS
              NOT NULL AND result_version IS NOT NULL AND meeting_series_history_id IS NULL)),
          CONSTRAINT a_completed_meeting_series_update_names_its_result CHECK (completed_at IS NULL
              OR capability <> 'meetings.series.update' OR (meeting_series_id IS NOT NULL AND
              meeting_series_history_id IS NOT NULL AND result_version IS NOT NULL AND meeting_id IS
              NULL AND meeting_history_id IS NULL)),
          CONSTRAINT a_meeting_write_request_names_a_meeting_of_its_principal FOREIGN
              KEY(meeting_id, principal_id) REFERENCES knowledge.meetings (meeting_id,
              principal_id),
          CONSTRAINT a_meeting_write_request_names_a_series_of_its_principal FOREIGN
              KEY(meeting_series_id, principal_id) REFERENCES knowledge.meeting_series
              (meeting_series_id, principal_id),
          CONSTRAINT a_meeting_write_request_names_a_receipt_of_its_meeting FOREIGN
              KEY(meeting_history_id, meeting_id, principal_id) REFERENCES knowledge.meeting_history
              (history_id, meeting_id, principal_id),
          CONSTRAINT a_meeting_write_request_names_a_receipt_of_its_series FOREIGN
              KEY(meeting_series_history_id, meeting_series_id, principal_id) REFERENCES
              knowledge.meeting_series_history (series_history_id, meeting_series_id, principal_id)
        )
        """,
    ),
)

_MANAGED_DOCUMENT_OWNER_UNIQUE: Final = "a_managed_document_is_identified_within_its_owner"

#: The three immutable ledgers: `(function, trigger, table)`.
_APPEND_ONLY: Final[tuple[tuple[str, str, str], ...]] = (
    (
        "meeting_history_stays_append_only",
        "meeting_history_rows_are_append_only",
        "meeting_history",
    ),
    (
        "meeting_note_versions_stay_append_only",
        "meeting_note_versions_are_append_only",
        "meeting_note_versions",
    ),
    (
        "meeting_series_history_stays_append_only",
        "meeting_series_history_rows_are_append_only",
        "meeting_series_history",
    ),
)

#: The one legal `meeting_write_requests` transition (package section 35.7): a
#: DELETE is refused; an UPDATE of a completed row is refused; an UPDATE of an
#: incomplete row is legal only as the completion itself, leaving every
#: immutable request-identity column unchanged and setting `completed_at`. The
#: capability-specific completed invariant is the table's CHECKs.
_COMPLETES_ONCE: Final = """
    CREATE FUNCTION knowledge.meeting_write_request_completes_once() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'a meeting write request is never deleted'
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF OLD.completed_at IS NOT NULL THEN
        RAISE EXCEPTION 'a meeting write request completes once'
          USING ERRCODE = 'restrict_violation';
      END IF;
      IF NEW.completed_at IS NULL
         OR NEW.principal_id IS DISTINCT FROM OLD.principal_id
         OR NEW.capability IS DISTINCT FROM OLD.capability
         OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
         OR NEW.request_digest IS DISTINCT FROM OLD.request_digest
         OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'a meeting write request changes only by completing'
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN NEW;
    END; $$;
    CREATE TRIGGER meeting_write_requests_complete_once
      BEFORE UPDATE OR DELETE ON knowledge.meeting_write_requests
      FOR EACH ROW EXECUTE FUNCTION knowledge.meeting_write_request_completes_once()
    """

#: `downgrade` refuses while any of these holds a row, rather than deleting user
#: data to make the downgrade pass (package section 24).
_REFUSE_DOWNGRADE: Final = """
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM knowledge.meeting_series)
         OR EXISTS (SELECT 1 FROM knowledge.meetings)
         OR EXISTS (SELECT 1 FROM knowledge.meeting_attendees)
         OR EXISTS (SELECT 1 FROM knowledge.meeting_attachments)
         OR EXISTS (SELECT 1 FROM knowledge.meeting_history)
         OR EXISTS (SELECT 1 FROM knowledge.meeting_note_versions)
         OR EXISTS (SELECT 1 FROM knowledge.meeting_series_history)
         OR EXISTS (SELECT 1 FROM knowledge.meeting_write_requests)
         OR EXISTS (
           SELECT 1 FROM knowledge.audit_events
           WHERE capability IN (
                   'meetings.create', 'meetings.list', 'meetings.read',
                   'meetings.search', 'meetings.series.update', 'meetings.update'
                 )
              OR purpose IN ('meeting_authoring', 'meeting_read')
         ) THEN
        RAISE EXCEPTION 'meeting records exist; refusing to downgrade 7d9a450dfd07'
          USING ERRCODE = 'restrict_violation';
      END IF;
    END $$
    """


def _restate_audit(capability: str, purpose: str) -> None:
    for name, expression in (("capability_is_known", capability), ("purpose_is_known", purpose)):
        op.drop_constraint(name, "audit_events", schema=SCHEMA, type_="check")
        op.create_check_constraint(name, "audit_events", expression, schema=SCHEMA)


def upgrade() -> None:
    op.create_unique_constraint(
        _MANAGED_DOCUMENT_OWNER_UNIQUE,
        "managed_documents",
        ["document_id", "owner_principal_id"],
        schema=SCHEMA,
    )
    for _table, ddl in _TABLE_DDL:
        op.execute(ddl)
    for function, trigger, table in _APPEND_ONLY:
        op.execute(
            f"""
            CREATE FUNCTION {SCHEMA}.{function}() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
              RAISE EXCEPTION '{table} is append-only'
                USING ERRCODE = 'restrict_violation';
            END; $$;
            CREATE TRIGGER {trigger}
              BEFORE UPDATE OR DELETE ON {SCHEMA}.{table}
              FOR EACH ROW EXECUTE FUNCTION {SCHEMA}.{function}()
            """
        )
    op.execute(_COMPLETES_ONCE)
    _restate_audit(_CAPABILITIES_AT_THIS_REVISION, _PURPOSES_AT_THIS_REVISION)


def downgrade() -> None:
    op.execute(_REFUSE_DOWNGRADE)
    _restate_audit(_CAPABILITIES_BEFORE_THIS_REVISION, _PURPOSES_BEFORE_THIS_REVISION)
    op.execute(
        f"DROP TRIGGER meeting_write_requests_complete_once ON {SCHEMA}.meeting_write_requests"
    )
    op.execute(f"DROP FUNCTION {SCHEMA}.meeting_write_request_completes_once()")
    for function, trigger, table in reversed(_APPEND_ONLY):
        op.execute(f"DROP TRIGGER {trigger} ON {SCHEMA}.{table}")
        op.execute(f"DROP FUNCTION {SCHEMA}.{function}()")
    for table, _ddl in reversed(_TABLE_DDL):
        op.execute(f"DROP TABLE {SCHEMA}.{table} RESTRICT")
    op.drop_constraint(
        _MANAGED_DOCUMENT_OWNER_UNIQUE, "managed_documents", schema=SCHEMA, type_="unique"
    )
