"""Fixtures for the loader tests.

Everything here is synthetic. The legacy corpus is personal data and never
appears in a test, a fixture, or an assertion (`AGENTS.md` sections 5 and 7);
what the fixtures reproduce is its *shape* — a TEXT primary key that permits
NULL, an INTEGER column holding text, an AUTOINCREMENT key, a rowid-alias key,
and a table with no key at all.

The target schema under test is generated by the real DDL generator from the
synthetic source, so the loader is tested against the same DDL the migration
applies rather than against a hand-written approximation of it.

Every database test runs against a disposable database created and dropped by
its fixture. The canonical `my_pa` database now holds the real target schema and
is never the target of a test.
"""

from __future__ import annotations

import sqlite3
from collections.abc import Iterator, Sequence
from pathlib import Path

import pytest
from sqlalchemy import Engine, text
from sqlalchemy.engine import make_url

from my_pa.bootstrap.settings import load_settings
from my_pa.infrastructure.database.engine import create_database_engine
from my_pa.infrastructure.migration.control_plane import METADATA
from my_pa.infrastructure.migration.generator import generate
from my_pa.infrastructure.migration.source import (
    Disposition,
    SourceColumn,
    SourceIndex,
    SourceTable,
)

#: Fixed name so a run interrupted before teardown is cleaned up by the next one.
DISPOSABLE_DATABASE = "my_pa_loader_test"

#: The one schema the synthetic tables land in, plus the control plane.
TARGET_SCHEMA = "core"
CONTROL_SCHEMA = "migration_control"

#: A stand-in for the Alembic revision the run binds to. The loader only ever
#: compares this value with itself, so a test does not need the real chain.
FAKE_REVISION = "0000loadertest"

SCHEMA_VERSION = 128

#: Each statement reproduces one shape the real corpus has, and nothing else.
SYNTHETIC_SCHEMA: tuple[str, ...] = (
    "CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, name TEXT NOT NULL)",
    # A TEXT primary key, a promoted boolean, a REAL, and an INTEGER that will be
    # handed a value it cannot hold.
    "CREATE TABLE widget_records ("
    " widget_id TEXT PRIMARY KEY,"
    " label TEXT NOT NULL,"
    " weight REAL,"
    " tally INTEGER,"
    " is_current INTEGER NOT NULL DEFAULT 0 CHECK(is_current IN (0, 1)),"
    " created_utc TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)",
    # AUTOINCREMENT: `GENERATED BY DEFAULT AS IDENTITY` in the target, so its
    # sequence has to be reset after the load (OD-016).
    "CREATE TABLE widget_events ("
    " event_id INTEGER PRIMARY KEY AUTOINCREMENT,"
    " widget_id TEXT NOT NULL,"
    " detail TEXT)",
    # A rowid alias with no AUTOINCREMENT. SQLite assigns it anyway, so it needs
    # the same identity and the same reset (OD-022).
    "CREATE TABLE widget_notes (note_id INTEGER PRIMARY KEY, body TEXT)",
    # No primary key and no unique index: surrogate key plus a row hash (OD-014).
    "CREATE TABLE widget_metrics (sample REAL, taken_utc TEXT)",
    # Where the NULL primary key and the NUL byte live (OD-023).
    "CREATE TABLE widget_defects (defect_id TEXT PRIMARY KEY, note TEXT)",
    # Operational state: created, deliberately empty by design (OD-025).
    "CREATE TABLE widget_cursors (cursor_id TEXT PRIMARY KEY, position INTEGER)",
)

#: Two phases, so a `--phase` selection has something to select between.
PHASE_ONE = "PHASE-03"
PHASE_TWO = "PHASE-04"

_TREATMENTS: dict[str, tuple[str, str, str]] = {
    "schema_migrations": ("NOT_CREATED", "DO_NOT_MIGRATE_EMPTY_OR_OBSOLETE", PHASE_ONE),
    "widget_records": ("SCHEMA_AND_DATA", "MIGRATE_DATA", PHASE_ONE),
    "widget_defects": ("SCHEMA_AND_DATA", "MIGRATE_DATA", PHASE_ONE),
    "widget_metrics": ("SCHEMA_AND_DATA", "MIGRATE_DATA", PHASE_ONE),
    "widget_notes": ("SCHEMA_AND_DATA", "MIGRATE_DATA", PHASE_ONE),
    "widget_events": ("SCHEMA_AND_DATA", "MIGRATE_DATA", PHASE_TWO),
    "widget_cursors": ("SCHEMA_ONLY_EMPTY_BY_DESIGN", "REINITIALIZE_OPERATIONAL_STATE", PHASE_TWO),
}


def synthetic_registry() -> dict[str, Disposition]:
    """The disposition registry for the synthetic source."""
    return {
        name: Disposition(
            legacy_object=name,
            object_type="table",
            target_schema=TARGET_SCHEMA,
            target_treatment=treatment,
            planning_disposition=planning,
            ordering_group=f"{phase}:CROSS_CUTTING",
        )
        for name, (treatment, planning, phase) in _TREATMENTS.items()
    }


def _source_indexes(connection: sqlite3.Connection, table: str) -> tuple[SourceIndex, ...]:
    indexes = []
    for _, name, unique, origin, partial in connection.execute(
        f'PRAGMA index_list("{table}")'
    ).fetchall():
        columns = tuple(
            row[2] for row in connection.execute(f'PRAGMA index_info("{name}")').fetchall()
        )
        sql = connection.execute(
            "SELECT sql FROM sqlite_master WHERE type = 'index' AND name = ?", (name,)
        ).fetchone()
        indexes.append(
            SourceIndex(
                name=str(name),
                unique=bool(unique),
                origin=str(origin),
                partial=bool(partial),
                columns=columns,
                sql=None if sql is None else sql[0],
            )
        )
    return tuple(indexes)


def read_source_tables(path: Path) -> tuple[SourceTable, ...]:
    """Introspect a synthetic SQLite file into the generator's input records."""
    connection = sqlite3.connect(f"file:{path}?immutable=1", uri=True)
    try:
        names = [
            str(row[0])
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table' "
                "AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
        ]
        tables = []
        for name in names:
            sql = connection.execute(
                "SELECT sql FROM sqlite_master WHERE name = ?", (name,)
            ).fetchone()[0]
            info = connection.execute(f'PRAGMA table_info("{name}")').fetchall()
            columns = tuple(
                SourceColumn(
                    name=str(row[1]),
                    declared_type=str(row[2] or ""),
                    not_null=bool(row[3]),
                    default=None if row[4] is None else str(row[4]),
                    pk_position=int(row[5]),
                )
                for row in info
            )
            primary_key = tuple(
                column.name
                for column in sorted(columns, key=lambda item: item.pk_position)
                if column.pk_position > 0
            )
            tables.append(
                SourceTable(
                    name=name,
                    object_type="table",
                    sql=str(sql),
                    columns=columns,
                    primary_key=primary_key,
                    foreign_keys=(),
                    indexes=_source_indexes(connection, name),
                    row_count=0,
                    is_fts=False,
                    is_virtual=False,
                    is_internal=False,
                    without_rowid=False,
                )
            )
        return tuple(tables)
    finally:
        connection.close()


def build_source(path: Path, rows: Sequence[tuple[str, Sequence[object]]]) -> Path:
    """Write a synthetic source database at `path` and insert `rows`."""
    connection = sqlite3.connect(path)
    try:
        for statement in SYNTHETIC_SCHEMA:
            connection.execute(statement)
        connection.execute(
            "INSERT INTO schema_migrations (version, name) VALUES (?, ?)",
            (SCHEMA_VERSION, "v128_synthetic"),
        )
        for statement, values in rows:
            connection.execute(statement, values)
        connection.commit()
    finally:
        connection.close()
    return path


@pytest.fixture
def loader_database(monkeypatch: pytest.MonkeyPatch) -> Iterator[str]:
    """An empty disposable database, with the settings pointed at it."""
    configured = make_url(load_settings().database_url)
    maintenance = create_database_engine(
        configured.set(database="postgres").render_as_string(hide_password=False)
    )
    drop = text(f'DROP DATABASE IF EXISTS "{DISPOSABLE_DATABASE}" WITH (FORCE)')

    def _administer(*statements: object) -> None:
        # CREATE and DROP DATABASE cannot run inside a transaction block.
        with maintenance.connect().execution_options(isolation_level="AUTOCOMMIT") as connection:
            for statement in statements:
                connection.execute(statement)  # type: ignore[arg-type]

    try:
        _administer(drop, text(f'CREATE DATABASE "{DISPOSABLE_DATABASE}"'))
        url = configured.set(database=DISPOSABLE_DATABASE).render_as_string(hide_password=False)
        monkeypatch.setenv("MY_PA_DATABASE_URL", url)
        yield url
    finally:
        _administer(drop)
        maintenance.dispose()


def prepare_target(engine: Engine, source: Path) -> None:
    """Create the schemas, the control plane, and the generated synthetic DDL.

    Deliberately not `alembic upgrade head`: the loader is under test here, not
    the 424-table target schema, and the revision that creates that schema has
    its own test.
    """
    schema = generate(read_source_tables(source), synthetic_registry())
    with engine.begin() as connection:
        connection.execute(text(f'CREATE SCHEMA "{TARGET_SCHEMA}"'))
        connection.execute(text(f'CREATE SCHEMA "{CONTROL_SCHEMA}"'))
        connection.execute(
            text("CREATE TABLE public.alembic_version (version_num varchar(32) PRIMARY KEY)")
        )
        connection.execute(
            text("INSERT INTO public.alembic_version (version_num) VALUES (:revision)"),
            {"revision": FAKE_REVISION},
        )
        METADATA.create_all(connection)
        for statement in schema.create_tables:
            connection.execute(text(statement))
        for statement in schema.create_indexes:
            connection.execute(text(statement))


@pytest.fixture
def target(loader_database: str) -> Iterator[Engine]:
    """An engine on the disposable database, with schemas but no synthetic tables yet."""
    engine = create_database_engine(loader_database)
    try:
        yield engine
    finally:
        engine.dispose()
