"""Opaque, server-issued identifiers.

Each identifier is a short type prefix joined to an opaque suffix by a single
underscore. `INV-PKL-005` requires that public identifiers not encode filesystem
paths, provider names, hosts, accounts, or database keys.

Validation here enforces *shape* only: the alphanumeric suffix rule rules out
path separators, dots, colons, and `@`, so a raw path or host cannot appear
verbatim. It cannot tell that `src_taxreturn2025` is semantic. Keeping suffixes
non-semantic is the issuer's responsibility, not something this module can check.
"""

from __future__ import annotations

import re
from enum import StrEnum
from typing import Final

__all__ = [
    "IdKind",
    "InvalidIdentifierError",
    "make_identifier",
    "parse_identifier",
    "validate_identifier",
]

_SUFFIX_PATTERN: Final = re.compile(r"\A[A-Za-z0-9]{8,64}\Z")
_MAX_LENGTH: Final = 72


class IdKind(StrEnum):
    """Identifier types defined by the v1 contract."""

    SOURCE = "src"
    SOURCE_OBJECT = "obj"
    VERSION = "ver"
    ENROLLMENT = "enr"
    OPERATION = "op"
    KNOWLEDGE = "kn"
    AUDIT = "audit"
    PRINCIPAL = "prn"
    CORRELATION = "corr"


class InvalidIdentifierError(ValueError):
    """Raised when a value is not a well-formed opaque identifier."""


def make_identifier(kind: IdKind, suffix: str) -> str:
    """Build an identifier of `kind` from an already-opaque `suffix`.

    The suffix must be generated by the caller from a non-semantic source. This
    function validates shape only; it cannot detect that a suffix leaks meaning.
    """
    candidate = f"{kind.value}_{suffix}"
    validate_identifier(candidate, kind)
    return candidate


def parse_identifier(value: str) -> tuple[IdKind, str]:
    """Return the kind and suffix of `value`, or raise `InvalidIdentifierError`."""
    validate_identifier(value)
    prefix, _, suffix = value.partition("_")
    return IdKind(prefix), suffix


def validate_identifier(value: str, expected: IdKind | None = None) -> str:
    """Validate `value` as an opaque identifier and return it unchanged.

    Fails closed: anything not matching the documented shape is rejected rather
    than normalised or guessed.
    """
    if len(value) > _MAX_LENGTH:
        raise InvalidIdentifierError(f"identifier exceeds {_MAX_LENGTH} characters")
    prefix, separator, suffix = value.partition("_")
    if not separator:
        raise InvalidIdentifierError("identifier must contain a type prefix and suffix")
    try:
        kind = IdKind(prefix)
    except ValueError as exc:
        raise InvalidIdentifierError(f"unknown identifier prefix: {prefix!r}") from exc
    if not _SUFFIX_PATTERN.fullmatch(suffix):
        raise InvalidIdentifierError("identifier suffix must be 8-64 alphanumeric characters")
    if expected is not None and kind is not expected:
        raise InvalidIdentifierError(f"expected {expected.value!r} identifier, got {prefix!r}")
    return value
