"""Product-owned Intelligence Artifact / Report plane.

This is not capture, not a managed document, and not extraction-plane knowledge.
Durable cycle runs, producer runs, and immutable artifact bodies live here so a
Morning Intelligence workflow can persist every stage with exact lineage.
"""

from my_pa.domain.intelligence.catalog import (
    ALLOWED_PROVENANCE_URL_SCHEMES,
    ARTIFACT_KIND_FOR_STAGE,
    CYCLE_MORNING_INTELLIGENCE,
    EXPECTED_FOCUS_AREAS,
    EXPECTED_SOURCE_LANES,
    FOCUS_AREA_IDS,
    MAX_ARTIFACT_BODY_BYTES,
    MAX_IDEMPOTENCY_KEY_LENGTH,
    MAX_STRUCTURED_CONTENT_BYTES,
    REQUIRED_DEPENDENCY_COUNT,
    RESOLVER_SET_IDS,
    SOURCE_LANE_IDS,
    STAGE_FOR_KIND,
    ArtifactKind,
    ArtifactState,
    CycleState,
    FocusAreaId,
    IntelligenceStage,
    ProducerRunState,
    ProvenanceRelation,
    ReadinessMemberState,
    ResolverAggregateState,
    ResolverSetId,
    SourceLaneId,
    expected_members,
    validate_stage_coordinates,
)
from my_pa.domain.intelligence.errors import (
    IntelligenceConflictError,
    IntelligenceCoordinateError,
    IntelligenceDependencyError,
    IntelligenceDigestMismatchError,
    IntelligenceIdempotencyConflictError,
    IntelligenceLimitError,
    IntelligenceStaleReferenceError,
    IntelligenceVersionConflictError,
)
from my_pa.domain.intelligence.models import (
    IntelligenceArtifact,
    IntelligenceCommitReceipt,
    IntelligenceCycleRun,
    IntelligencePipelineDependency,
    IntelligenceProducerRun,
    IntelligenceProvenanceRef,
    MutationAdmission,
    content_digest,
    content_utf8_bytes,
    fingerprint_payload,
)

__all__ = [
    "ALLOWED_PROVENANCE_URL_SCHEMES",
    "ARTIFACT_KIND_FOR_STAGE",
    "CYCLE_MORNING_INTELLIGENCE",
    "EXPECTED_FOCUS_AREAS",
    "EXPECTED_SOURCE_LANES",
    "FOCUS_AREA_IDS",
    "MAX_ARTIFACT_BODY_BYTES",
    "MAX_IDEMPOTENCY_KEY_LENGTH",
    "MAX_STRUCTURED_CONTENT_BYTES",
    "REQUIRED_DEPENDENCY_COUNT",
    "RESOLVER_SET_IDS",
    "SOURCE_LANE_IDS",
    "STAGE_FOR_KIND",
    "ArtifactKind",
    "ArtifactState",
    "CycleState",
    "FocusAreaId",
    "IntelligenceArtifact",
    "IntelligenceCommitReceipt",
    "IntelligenceConflictError",
    "IntelligenceCoordinateError",
    "IntelligenceCycleRun",
    "IntelligenceDependencyError",
    "IntelligenceDigestMismatchError",
    "IntelligenceIdempotencyConflictError",
    "IntelligenceLimitError",
    "IntelligencePipelineDependency",
    "IntelligenceProducerRun",
    "IntelligenceProvenanceRef",
    "IntelligenceStage",
    "IntelligenceStaleReferenceError",
    "IntelligenceVersionConflictError",
    "MutationAdmission",
    "ProducerRunState",
    "ProvenanceRelation",
    "ReadinessMemberState",
    "ResolverAggregateState",
    "ResolverSetId",
    "SourceLaneId",
    "content_digest",
    "content_utf8_bytes",
    "expected_members",
    "fingerprint_payload",
    "validate_stage_coordinates",
]
