"""What a client credential is made of, and what it refuses to be.

WP-10, at the level where a secret is a string and a binding is a comparison.
Everything here is `domain.capture.client`: no database, no transport, no
process. The claims that need a store are elsewhere; these are the ones a store
cannot make, because they are about the value objects the store writes.

Every secret in this module is generated by the code under test or is an
obviously synthetic literal. Nothing here is, or resembles, a working credential.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Final

import pytest

from my_pa.domain.capture.client import (
    SECRET_DIGEST_CHARACTERS,
    ClientBindingRefusedError,
    ClientCredential,
    ClientState,
    RegisteredCaptureClient,
    admit_client_binding,
    hash_client_secret,
    issue_client_secret,
    parse_client_credential,
    secret_matches,
)
from my_pa.domain.capture.errors import CaptureError
from my_pa.domain.common.identifiers import IdKind, InvalidIdentifierError, make_identifier

WHEN: Final = datetime(2026, 8, 10, 12, 0, tzinfo=UTC)

CLIENT_ID: Final = make_identifier(IdKind.CAPTURE_CLIENT, "clienttest000000000000000000")
OTHER_PRINCIPAL: Final = make_identifier(IdKind.PRINCIPAL, "syntheticbprincipal000000000")
PRINCIPAL: Final = make_identifier(IdKind.PRINCIPAL, "syntheticaprincipal000000000")


def test_a_minted_secret_is_long_random_and_paired_with_its_digest() -> None:
    """The mint produces both halves at once and never the same secret twice.

    Two calls differing is not a statistical claim about entropy — it is the
    minimum a caller can check — but the pairing is the property that matters:
    there is no way to obtain a digest without holding the plaintext it came
    from, so no code path can store a secret it did not just generate.
    """
    secret, digest = issue_client_secret()
    again, _ = issue_client_secret()

    assert secret != again
    assert len(secret) >= 40, "a client secret is 32 bytes of CSPRNG output, URL-safe"
    assert len(digest) == SECRET_DIGEST_CHARACTERS
    assert digest == hash_client_secret(secret)
    assert secret not in digest


def test_a_secret_verifies_against_its_own_digest_and_nothing_else() -> None:
    secret, digest = issue_client_secret()
    other, _ = issue_client_secret()

    assert secret_matches(secret, digest)
    assert not secret_matches(other, digest)
    assert not secret_matches(secret + "a", digest)
    assert not secret_matches("", digest)


def test_an_absent_client_is_answered_by_the_same_comparison() -> None:
    """ "No such client" and "wrong secret" take one path through the check.

    `None` is what the store returns for a client identifier that names nothing,
    and the comparison still happens — against a digest no mint can produce — so
    the function cannot become an existence oracle by returning early.
    """
    secret, _ = issue_client_secret()
    assert not secret_matches(secret, None)
    assert not secret_matches("", None)


def test_an_empty_secret_cannot_be_stored() -> None:
    """Otherwise `<client_id>:` would be a working credential.

    An empty string has a perfectly good SHA-256, so a hash function that
    accepted one would happily store it — and the credential parser would then
    have to be the only thing standing between an empty secret and a match.
    """
    with pytest.raises(CaptureError):
        hash_client_secret("")


def test_a_credential_splits_at_the_first_colon_and_refuses_everything_else() -> None:
    """Shape only, and one refusal for every shape that is not one."""
    secret, _ = issue_client_secret()
    parsed = parse_client_credential(f"{CLIENT_ID}:{secret}")
    assert parsed == ClientCredential(client_id=CLIENT_ID, secret=secret)

    for malformed in (
        "",
        CLIENT_ID,
        f"{CLIENT_ID}:",
        f":{secret}",
    ):
        with pytest.raises(CaptureError):
            parse_client_credential(malformed)


@pytest.mark.parametrize(
    "presented",
    [
        f"{PRINCIPAL}:synthetic-secret",
        ":synthetic-secret",
        "not-an-identifier:synthetic-secret",
        "cclt_short:synthetic-secret",
        "cclt_has spaces in it here:synthetic-secret",
    ],
    ids=["principal-prefix", "empty", "no-prefix", "too-short", "spaces"],
)
def test_every_malformed_identifier_refuses_as_one_capture_error(presented: str) -> None:
    """One exception type out of this function, and the reason is a real escape.

    `validate_identifier` raises `InvalidIdentifierError`, a `ValueError`. The
    composition root catches `CaptureError` on its way to the transport's single
    `401`, so an identifier refusal that kept its own type left the authenticator
    as an unclassified exception and the caller received a `500` — a server fault
    for a credential the server understood perfectly well. Asserting the *type*
    here is what keeps that closed.
    """
    with pytest.raises(CaptureError):
        parse_client_credential(presented)
    assert not issubclass(InvalidIdentifierError, CaptureError), (
        "the two error families merged, which would make the assertion above "
        "pass without the conversion it exists to check"
    )


def test_a_credentials_repr_carries_the_identifier_and_not_the_secret() -> None:
    """The channel `CreateCapture.text` closes, closed here for the same reason.

    A dataclass `repr` reaches a traceback, a log record, and pytest's own
    assertion output without anyone deciding it should. This is the one value in
    the tree that is a live credential.
    """
    secret, _ = issue_client_secret()
    rendered = repr(parse_client_credential(f"{CLIENT_ID}:{secret}"))
    assert CLIENT_ID in rendered
    assert secret not in rendered


def test_a_registered_client_holds_no_secret_and_no_digest() -> None:
    """Structural rather than tidy: a listing cannot print what a type cannot hold."""
    client = RegisteredCaptureClient(
        client_id=CLIENT_ID, principal_id=PRINCIPAL, state=ClientState.ACTIVE, created_at=WHEN
    )
    fields = set(RegisteredCaptureClient.__dataclass_fields__)
    assert not any("secret" in name or "sha" in name or "digest" in name for name in fields)
    assert client.usable


def test_revocation_and_its_timestamp_cannot_disagree() -> None:
    """A revoked client records when; an active one records nothing."""
    revoked = RegisteredCaptureClient(
        client_id=CLIENT_ID,
        principal_id=PRINCIPAL,
        state=ClientState.REVOKED,
        created_at=WHEN,
        revoked_at=WHEN + timedelta(minutes=1),
    )
    assert not revoked.usable

    with pytest.raises(CaptureError):
        RegisteredCaptureClient(
            client_id=CLIENT_ID,
            principal_id=PRINCIPAL,
            state=ClientState.REVOKED,
            created_at=WHEN,
        )
    with pytest.raises(CaptureError):
        RegisteredCaptureClient(
            client_id=CLIENT_ID,
            principal_id=PRINCIPAL,
            state=ClientState.ACTIVE,
            created_at=WHEN,
            revoked_at=WHEN,
        )


def test_a_client_identifier_must_be_a_client_identifier() -> None:
    with pytest.raises(InvalidIdentifierError):
        RegisteredCaptureClient(
            client_id=PRINCIPAL, principal_id=PRINCIPAL, state=ClientState.ACTIVE, created_at=WHEN
        )


# ---- the binding rule ---------------------------------------------------------


def test_a_pinned_process_admits_only_its_own_principal() -> None:
    """The WP-08 NOTE 1 avoidance, at the level it is decided.

    Under `local_operator` the process serves exactly one Principal, so a client
    bound to any other one is refused. That refusal is what keeps a minted
    credential from introducing a *second* Principal holding real data, which is
    the condition WP-08's replay check names as its release blocker.
    """
    admit_client_binding(bound=PRINCIPAL, admissible=PRINCIPAL)

    with pytest.raises(ClientBindingRefusedError):
        admit_client_binding(bound=OTHER_PRINCIPAL, admissible=PRINCIPAL)


def test_an_unpinned_process_admits_the_principal_it_authenticated() -> None:
    """`None` means "this process authenticates real people", not "anything goes".

    In `entra` mode two real Principals are two real datasets, so a client binds
    to whichever one was authenticated when it was minted, and there is no single
    admissible identifier for this function to compare against. The refusal that
    matters there is the authentication itself.
    """
    admit_client_binding(bound=PRINCIPAL, admissible=None)
    admit_client_binding(bound=OTHER_PRINCIPAL, admissible=None)


def test_the_refusal_names_no_principal() -> None:
    """The message says what the rule is, never which identifiers failed it."""
    with pytest.raises(ClientBindingRefusedError) as refused:
        admit_client_binding(bound=OTHER_PRINCIPAL, admissible=PRINCIPAL)
    assert OTHER_PRINCIPAL not in str(refused.value)
    assert PRINCIPAL not in str(refused.value)
