"""What the loader loads, and the shape it loads into.

A plan is built from three things that have to agree: the disposition registry
(which tables are loaded at all, and into which schema), the live SQLite source
(which columns exist and which of them are the key), and the target database's
own catalogue (what the generated DDL actually produced).

Reading the target from `information_schema` rather than re-deriving it from the
DDL generator is deliberate. The generator's output has already been applied by
Alembic; asking the database what it has makes the plan a *check* on that DDL
instead of a second opinion about it, and the loader fails closed when the two
disagree rather than discovering it a million rows later.

What is loaded is OD-025's scope: 98% of the corpus. What is not is a short,
named list — operational state that must start empty, tables a newer table
already supersedes, obsolete and privacy-gated objects, and FTS internals — and
every one of them keeps the empty table the DDL created or no table at all.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from enum import StrEnum
from sqlite3 import Connection as SqliteConnection

from sqlalchemy import Connection, text

from my_pa.infrastructure.migration.generator import (
    PROVENANCE_COLUMNS,
    SOURCE_ROW_HASH_COLUMN,
    SURROGATE_KEY_COLUMN,
)
from my_pa.infrastructure.migration.identifiers import target_name
from my_pa.infrastructure.migration.reader import SourceTableShape, read_shape
from my_pa.infrastructure.migration.source import Disposition

#: OD-025. The treatments that carry rows. `SCHEMA_AND_DATA_REBUILDABLE` is
#: loaded like any other and marked so a later rebuild knows it may truncate and
#: recompute; the plan's "leave it for the application to rebuild" was a 40%
#: data loss, because the application that would rebuild it is the legacy one and
#: it is not being ported. Everything else keeps the empty table the DDL created,
#: which is an outcome, not a shortfall.
LOADED_TREATMENTS = frozenset({"SCHEMA_AND_DATA", "SCHEMA_AND_DATA_REBUILDABLE", "PROVENANCE_ONLY"})

#: OD-026. Provenance-only tables carry identity and run binding but no payload.
#: All four are empty at schema version 128, so the treatment is satisfied by
#: loading them normally; a non-empty one is refused rather than truncated,
#: because the generated DDL keeps their NOT NULL payload columns and a stripped
#: row could not satisfy them.
PROVENANCE_ONLY = "PROVENANCE_ONLY"


class PlanError(RuntimeError):
    """The source, the registry, and the target database do not agree."""


class TargetType(StrEnum):
    """The `information_schema` type names the generated DDL produces."""

    TEXT = "text"
    BIGINT = "bigint"
    DOUBLE_PRECISION = "double precision"
    BOOLEAN = "boolean"
    UUID = "uuid"
    INTEGER = "integer"


@dataclass(frozen=True)
class ColumnPlan:
    """One source column and the target column it lands in."""

    source_name: str
    target_name: str
    target_type: TargetType
    is_primary_key: bool


@dataclass(frozen=True)
class TableLoadPlan:
    """One legacy table's load.

    `identity_column` names the target column whose sequence must be reset to
    `max + 1` after the load (OD-016, OD-022): the DDL made those columns
    `GENERATED BY DEFAULT AS IDENTITY` so the load can insert the source's own
    keys, which leaves the sequence behind the data.
    """

    legacy_table: str
    phase: str
    ordering_group: str
    treatment: str
    target_schema: str
    target_table: str
    columns: tuple[ColumnPlan, ...]
    key_columns: tuple[str, ...]
    identity_column: str | None
    row_hash_column: str | None
    provenance_columns: tuple[str, ...]

    @property
    def has_natural_key(self) -> bool:
        """False for a table the source gave neither a primary key nor a unique index.

        Such a table is identified by a hash of its whole tuple (OD-014), and two
        byte-identical source rows are two rows, so it is not deduplicated.
        """
        return bool(self.key_columns)


@dataclass(frozen=True)
class _TargetColumn:
    name: str
    data_type: str
    is_identity: bool


def phase_of(disposition: Disposition) -> str:
    """Return the phase a table loads in.

    `ordering_group` is built as ``<phase_id>:<primary_domain>`` by
    `scripts/migration/build_disposition_registry.py`, so the prefix is the
    phase.
    """
    return disposition.ordering_group.split(":", 1)[0]


def _read_target_columns(
    connection: Connection, schemas: Sequence[str]
) -> dict[str, list[_TargetColumn]]:
    rows = connection.execute(
        text(
            "SELECT table_schema, table_name, column_name, data_type, is_identity "
            "FROM information_schema.columns WHERE table_schema = ANY(:schemas) "
            "ORDER BY table_schema, table_name, ordinal_position"
        ),
        {"schemas": list(schemas)},
    ).all()
    catalogue: dict[str, list[_TargetColumn]] = {}
    for schema, table, column, data_type, is_identity in rows:
        catalogue.setdefault(f"{schema}.{table}", []).append(
            _TargetColumn(
                name=str(column),
                data_type=str(data_type),
                is_identity=str(is_identity) == "YES",
            )
        )
    return catalogue


def _read_primary_keys(
    connection: Connection, schemas: Sequence[str]
) -> dict[str, tuple[str, ...]]:
    rows = connection.execute(
        text(
            "SELECT n.nspname, c.relname, a.attname "
            "FROM pg_index i "
            "JOIN pg_class c ON c.oid = i.indrelid "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            "JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ANY(i.indkey) "
            "WHERE i.indisprimary AND n.nspname = ANY(:schemas) "
            "ORDER BY n.nspname, c.relname, a.attnum"
        ),
        {"schemas": list(schemas)},
    ).all()
    keys: dict[str, list[str]] = {}
    for schema, table, column in rows:
        keys.setdefault(f"{schema}.{table}", []).append(str(column))
    return {relation: tuple(columns) for relation, columns in keys.items()}


def _target_type(relation: str, column: _TargetColumn) -> TargetType:
    try:
        return TargetType(column.data_type)
    except ValueError as exc:
        raise PlanError(
            f"{relation}.{column.name} has target type {column.data_type!r}, "
            "which the loader has no defensible cast for"
        ) from exc


def _plan_table(
    disposition: Disposition,
    shape: SourceTableShape,
    catalogue: Mapping[str, list[_TargetColumn]],
    primary_keys: Mapping[str, tuple[str, ...]],
) -> TableLoadPlan:
    if shape.without_rowid:
        # Resume reads `rowid` as its watermark. A WITHOUT ROWID table has none,
        # so it would have no stable resume point and is refused rather than
        # loaded in one unrecoverable pass.
        raise PlanError(f"{disposition.legacy_object} is WITHOUT ROWID and cannot be resumed")
    target_table = target_name(disposition.legacy_object)
    relation = f"{disposition.target_schema}.{target_table}"
    target_columns = catalogue.get(relation)
    if target_columns is None:
        raise PlanError(f"{relation} is marked for loading but does not exist in the target")

    by_name = {column.name: column for column in target_columns}
    target_key = frozenset(primary_keys.get(relation, ()))

    columns: list[ColumnPlan] = []
    for source_column in shape.columns:
        mapped = target_name(source_column.name)
        target_column = by_name.get(mapped)
        if target_column is None:
            raise PlanError(
                f"{relation} has no column {mapped!r} for source {source_column.name!r}"
            )
        columns.append(
            ColumnPlan(
                source_name=source_column.name,
                target_name=mapped,
                target_type=_target_type(relation, target_column),
                is_primary_key=mapped in target_key,
            )
        )

    provenance = tuple(name for name, _ in PROVENANCE_COLUMNS)
    accounted = {column.target_name for column in columns} | set(provenance)
    surrogate = SURROGATE_KEY_COLUMN if SURROGATE_KEY_COLUMN in by_name else None
    row_hash = SOURCE_ROW_HASH_COLUMN if SOURCE_ROW_HASH_COLUMN in by_name else None
    accounted |= {name for name in (surrogate, row_hash) if name is not None}
    unaccounted = sorted(set(by_name) - accounted)
    if unaccounted:
        raise PlanError(f"{relation} has target columns the source does not explain: {unaccounted}")
    missing = sorted(set(provenance) - set(by_name))
    if missing:
        raise PlanError(f"{relation} is missing provenance columns {missing}")

    key_columns = shape.primary_key
    if key_columns and frozenset(target_name(name) for name in key_columns) != target_key:
        raise PlanError(f"{relation} primary key does not match the source key")
    if not key_columns and row_hash is None:
        raise PlanError(f"{relation} has no source key and no {SOURCE_ROW_HASH_COLUMN} column")

    # A surrogate identity is `GENERATED ALWAYS`: the load never supplies it, so
    # its sequence is never left behind the data and needs no reset. The identity
    # that does need one is the `BY DEFAULT` key the load fills from the source.
    identity = next(
        (
            column.name
            for column in target_columns
            if column.is_identity and column.name != surrogate
        ),
        None,
    )

    return TableLoadPlan(
        legacy_table=disposition.legacy_object,
        phase=phase_of(disposition),
        ordering_group=disposition.ordering_group,
        treatment=disposition.target_treatment,
        target_schema=disposition.target_schema,
        target_table=target_table,
        columns=tuple(columns),
        key_columns=key_columns,
        identity_column=identity,
        row_hash_column=None if key_columns else row_hash,
        provenance_columns=provenance,
    )


def build_plans(
    source: SqliteConnection,
    connection: Connection,
    registry: Mapping[str, Disposition],
    *,
    phases: Iterable[str] | None = None,
    tables: Iterable[str] | None = None,
) -> tuple[TableLoadPlan, ...]:
    """Build the load plan, in `ordering_group` then name order.

    Ordering follows DEP-001..019 so parents generally precede children. It is a
    convenience, not a guarantee: the foreign keys are added after the load
    (OD-017) precisely because the source never enforced them.
    """
    wanted = None if tables is None else frozenset(tables)
    selected = [
        disposition
        for disposition in registry.values()
        if disposition.object_type == "table"
        and disposition.target_treatment in LOADED_TREATMENTS
        and (phases is None or phase_of(disposition) in frozenset(phases))
        and (wanted is None or disposition.legacy_object in wanted)
    ]
    if wanted is not None:
        unknown = sorted(wanted - {item.legacy_object for item in selected})
        if unknown:
            raise PlanError(f"not loadable tables: {unknown}")
    if not selected:
        return ()

    schemas = sorted({disposition.target_schema for disposition in selected})
    catalogue = _read_target_columns(connection, schemas)
    primary_keys = _read_primary_keys(connection, schemas)

    plans = [
        _plan_table(
            disposition, read_shape(source, disposition.legacy_object), catalogue, primary_keys
        )
        for disposition in sorted(
            selected, key=lambda item: (item.ordering_group, item.legacy_object)
        )
    ]
    return tuple(plans)
